// iconaut-react — archive (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M4.97 3.5L19.02 3.5A2.48 2.48 0 0 1 21.5 5.98L21.5 8.32A0.68 0.68 0 0 1 20.83 9L20 9L20 18.29A2.71 2.71 0 0 1 17.29 21L6.71 21A2.71 2.71 0 0 1 4 18.29L4 9L3.18 9A0.68 0.68 0 0 1 2.5 8.32L2.5 5.98A2.48 2.48 0 0 1 4.97 3.5Z M14 13.5L10 13.5L10 12.5L14 12.5ZM19 8.5L5 8.5L5 7.5L19 7.5Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M4.99 3.66L19.01 3.66A2.33 2.33 0 0 1 21.34 5.99L21.34 8.16A0.68 0.68 0 0 1 20.67 8.84L19.84 8.84L19.84 18.29A2.55 2.55 0 0 1 17.29 20.84L6.71 20.84A2.55 2.55 0 0 1 4.16 18.29L4.16 8.84L3.34 8.84A0.68 0.68 0 0 1 2.66 8.16L2.66 5.99A2.33 2.33 0 0 1 4.99 3.66Z M14 13.5L10 13.5L10 12.5L14 12.5ZM19 8.5L5 8.5L5 7.5L19 7.5Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M4.71 3.16L19.29 3.16A2.55 2.55 0 0 1 21.84 5.71L21.84 8.16A0.68 0.68 0 0 1 21.17 8.84L20.34 8.84L20.34 18.29A2.55 2.55 0 0 1 17.79 20.84L6.21 20.84A2.55 2.55 0 0 1 3.66 18.29L3.66 8.84L2.84 8.84A0.68 0.68 0 0 1 2.16 8.16L2.16 5.71A2.55 2.55 0 0 1 4.71 3.16Z M14 13.5L10 13.5L10 12.5L14 12.5ZM19.5 8.5L4.5 8.5L4.5 7.5L19.5 7.5Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M4.71 3.15L19.29 3.15A2.56 2.56 0 0 1 21.85 5.71L21.85 8.17A0.68 0.68 0 0 1 21.18 8.85L20.35 8.85L20.35 18.29A2.56 2.56 0 0 1 17.79 20.85L6.21 20.85A2.56 2.56 0 0 1 3.65 18.29L3.65 8.85L2.83 8.85A0.68 0.68 0 0 1 2.15 8.17L2.15 5.71A2.56 2.56 0 0 1 4.71 3.15Z M14 13.5L10 13.5L10 12.5L14 12.5ZM19.5 8.5L4.5 8.5L4.5 7.5L19.5 7.5Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function ArchiveSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
