// iconaut-react — armchair (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5.95 17.75 Q3.95 17.75 3.95 15.75 L3.95 10.28 Q3.95 8.55 5.68 8.55 L5.68 8.55 Q7.4 8.55 7.4 6.83 L7.4 5.95 Q7.4 3.95 9.4 3.95 L14.6 3.95 Q16.6 3.95 16.6 5.95 L16.6 6.83 Q16.6 8.55 18.33 8.55 L18.33 8.55 Q20.05 8.55 20.05 10.28 L20.05 15.75 Q20.05 17.75 18.05 17.75 Z\"/><g class=\"primary\"><path d=\"M5.95 17.75 Q3.95 17.75 3.95 15.75 L3.95 10.28 Q3.95 8.55 5.68 8.55 L5.68 8.55 Q7.4 8.55 7.4 6.83 L7.4 5.95 Q7.4 3.95 9.4 3.95 L14.6 3.95 Q16.6 3.95 16.6 5.95 L16.6 6.83 Q16.6 8.55 18.33 8.55 L18.33 8.55 Q20.05 8.55 20.05 10.28 L20.05 15.75 Q20.05 17.75 18.05 17.75 Z\"/><path d=\"M3.95 13.15 L 20.05 13.15\"/><path d=\"M6.83 17.75 L 6.83 20.05 M17.18 17.75 L 17.18 20.05\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function ArmchairDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
