// iconaut-react — arrow-big-up (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M11.5 20.5 Q9.5 20.5 9.5 18.5 L9.5 14.5 Q9.5 12.5 7.5 12.5 L7.5 12.5 Q5.5 12.5 6.76 10.95 L10.74 6.05 Q12 4.5 13.26 6.05 L17.24 10.95 Q18.5 12.5 16.5 12.5 L16.5 12.5 Q14.5 12.5 14.5 14.5 L14.5 18.5 Q14.5 20.5 12.5 20.5 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function ArrowBigUp({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
