// iconaut-react — barbell (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.6 6.6 A1.1 1.1 0 0 1 5.7 5.5 L6.1 5.5 A1.1 1.1 0 0 1 7.2 6.6 L7.2 17.4 A1.1 1.1 0 0 1 6.1 18.5 L5.7 18.5 A1.1 1.1 0 0 1 4.6 17.4 Z\"/><path d=\"M16.8 6.6 A1.1 1.1 0 0 1 17.9 5.5 L18.3 5.5 A1.1 1.1 0 0 1 19.4 6.6 L19.4 17.4 A1.1 1.1 0 0 1 18.3 18.5 L17.9 18.5 A1.1 1.1 0 0 1 16.8 17.4 Z\"/><path d=\"M7.2 12 L 16.8 12\"/><path d=\"M2.9 12 L 4.6 12 M19.4 12 L 21.1 12\"/>";
const M1 = "<path d=\"M4.6 6.6 A1.1 1.1 0 0 1 5.7 5.5 L6.1 5.5 A1.1 1.1 0 0 1 7.2 6.6 L7.2 17.4 A1.1 1.1 0 0 1 6.1 18.5 L5.7 18.5 A1.1 1.1 0 0 1 4.6 17.4 Z\"/><path d=\"M16.8 6.6 A1.1 1.1 0 0 1 17.9 5.5 L18.3 5.5 A1.1 1.1 0 0 1 19.4 6.6 L19.4 17.4 A1.1 1.1 0 0 1 18.3 18.5 L17.9 18.5 A1.1 1.1 0 0 1 16.8 17.4 Z\"/><path d=\"M7.2 12 L 16.8 12\"/><path d=\"M2.9 12 L 4.6 12 M19.4 12 L 21.1 12\"/><path d=\"M9.4 9.2 L 9.4 14.8 M14.6 9.2 L 14.6 14.8\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function Barbell({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
