// iconaut-react — barcode (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.5 6 L 4.5 18 M7 6 L 7 18 M9.5 6 L 9.5 18 M12 6 L 12 18 M14.5 6 L 14.5 18 M17 6 L 17 18 M19.5 6 L 19.5 18\"/>";
const M1 = "<path d=\"M4.5 5.5 L 4.5 18.5 M7 5.5 L 7 18.5 M9.5 5.5 L 9.5 18.5 M12 5.5 L 12 18.5 M14.5 5.5 L 14.5 18.5 M17 5.5 L 17 18.5 M19.5 5.5 L 19.5 18.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function BarcodeDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
