// iconaut-react — beer (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M7.1 4.46L14.9 4.46A2.64 2.64 0 0 1 17.54 7.1L17.54 17.9A2.64 2.64 0 0 1 14.9 20.54L7.1 20.54A2.64 2.64 0 0 1 4.46 17.9L4.46 7.1A2.64 2.64 0 0 1 7.1 4.46Z M15.6 7.92L15.6 7.92L15.6 9.88L15.54 9.89L15.4 9.9L6.6 9.9L6.4 9.88L6.4 9.88L6.4 7.93L6.46 7.91L6.6 7.9L15.4 7.9Z\"/><path d=\"M17.2 8.65 L17.8 8.65 A3.35 3.35 0 0 1 17.8 15.35 L17.2 15.35 Q16.6 15.35 16.6 14.75 L16.6 14.45 Q16.6 13.85 17.2 13.85 L17.8 13.85 A1.85 1.85 0 0 0 17.8 10.15 L17.2 10.15 Q16.6 10.15 16.6 9.55 L16.6 9.25 Q16.6 8.65 17.2 8.65 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M7.11 4.5L14.89 4.5A2.61 2.61 0 0 1 17.5 7.11L17.5 17.89A2.61 2.61 0 0 1 14.89 20.5L7.11 20.5A2.61 2.61 0 0 1 4.5 17.89L4.5 7.11A2.61 2.61 0 0 1 7.11 4.5Z M15.6 7.92L15.6 7.92L15.6 9.88L15.54 9.89L15.4 9.9L6.6 9.9L6.4 9.88L6.4 9.88L6.4 7.93L6.46 7.91L6.6 7.9L15.4 7.9Z\"/><path d=\"M17.2 8.65 L17.8 8.65 A3.35 3.35 0 0 1 17.8 15.35 L17.2 15.35 Q16.6 15.35 16.6 14.75 L16.6 14.45 Q16.6 13.85 17.2 13.85 L17.8 13.85 A1.85 1.85 0 0 0 17.8 10.15 L17.2 10.15 Q16.6 10.15 16.6 9.55 L16.6 9.25 Q16.6 8.65 17.2 8.65 Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M7.11 4.52L14.9 4.53A2.58 2.58 0 0 1 17.48 7.11L17.48 17.9A2.58 2.58 0 0 1 14.9 20.48L7.11 20.48A2.58 2.58 0 0 1 4.53 17.9L4.53 7.1A2.58 2.58 0 0 1 7.11 4.52Z M15.6 7.92L15.6 7.92L15.6 9.88L15.54 9.89L15.4 9.9L6.6 9.9L6.4 9.88L6.4 9.88L6.4 7.93L6.46 7.91L6.6 7.9L15.4 7.9Z\"/><path d=\"M17.2 8.65 L17.8 8.65 A3.35 3.35 0 0 1 17.8 15.35 L17.2 15.35 Q16.6 15.35 16.6 14.75 L16.6 14.45 Q16.6 13.85 17.2 13.85 L17.8 13.85 A1.85 1.85 0 0 0 17.8 10.15 L17.2 10.15 Q16.6 10.15 16.6 9.55 L16.6 9.25 Q16.6 8.65 17.2 8.65 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function BeerSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
