// iconaut-react — bike (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M2.8 16 A3.2 3.2 0 1 0 9.2 16 A3.2 3.2 0 1 0 2.8 16 Z\"/><path d=\"M14.8 16 A3.2 3.2 0 1 0 21.2 16 A3.2 3.2 0 1 0 14.8 16 Z\"/><path d=\"M9.2 16 L11 16 Q12 16 11.67 15.06 L10.23 10.94 Q9.9 10 10.9 10 L14.4 10 Q15.4 10 14.91 10.87 L12 16\"/><path d=\"M9.7 7.8 L 9.9 10\"/><path d=\"M8.3 7.8 L 11.1 7.8\"/><path d=\"M15.4 10 L 16.7 13.1\"/><path d=\"M15.9 7.8 L 15.4 10\"/><path d=\"M15.9 7.8 L 17.9 7.8\"/>";
const M1 = "<path d=\"M2.8 16 A3.2 3.2 0 1 0 9.2 16 A3.2 3.2 0 1 0 2.8 16 Z\"/><path d=\"M14.8 16 A3.2 3.2 0 1 0 21.2 16 A3.2 3.2 0 1 0 14.8 16 Z\"/><path d=\"M9.2 16 L11 16 Q12 16 11.67 15.06 L10.23 10.94 Q9.9 10 9.35 10.83 L7.7 13.3\"/><path d=\"M9.9 10 L14.4 10 Q15.4 10 14.91 10.87 L12 16\"/><path d=\"M9.7 7.8 L 9.9 10\"/><path d=\"M8.3 7.8 L 11.1 7.8\"/><path d=\"M15.4 10 L 16.7 13.1\"/><path d=\"M15.9 7.8 L 15.4 10\"/><path d=\"M15.9 7.8 L 17.9 7.8\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function Bike({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
