// iconaut-react — bluesky (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 8.2 C10.8 5.6 8.2 3.6 5.9 3.6 C4.3 3.6 3.4 4.7 3.4 6.5 C3.4 9.6 5.9 13.1 9.3 13.3 C7.6 13.9 6.6 15.2 6.6 16.6 C6.6 18.3 7.9 19.5 9.6 19.5 C10.7 19.5 11.5 18.9 12 17.9 C12.5 18.9 13.3 19.5 14.4 19.5 C16.1 19.5 17.4 18.3 17.4 16.6 C17.4 15.2 16.4 13.9 14.7 13.3 C18.1 13.1 20.6 9.6 20.6 6.5 C20.6 4.7 19.7 3.6 18.1 3.6 C15.8 3.6 13.2 5.6 12 8.2 Z\"/><g class=\"primary\"><path d=\"M12 8.2 C10.8 5.6 8.2 3.6 5.9 3.6 C4.3 3.6 3.4 4.7 3.4 6.5 C3.4 9.6 5.9 13.1 9.3 13.3 C7.6 13.9 6.6 15.2 6.6 16.6 C6.6 18.3 7.9 19.5 9.6 19.5 C10.7 19.5 11.5 18.9 12 17.9 C12.5 18.9 13.3 19.5 14.4 19.5 C16.1 19.5 17.4 18.3 17.4 16.6 C17.4 15.2 16.4 13.9 14.7 13.3 C18.1 13.1 20.6 9.6 20.6 6.5 C20.6 4.7 19.7 3.6 18.1 3.6 C15.8 3.6 13.2 5.6 12 8.2 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function BlueskyDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
