// iconaut-react — bluesky (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6.83 5.05 C8.47 6.28 10.19 8.48 11.27 10.2 L11.64 10.86 Q12 11.51 12.37 10.86 L12.73 10.2 C13.81 8.48 15.53 6.28 17.17 5.05 C18.68 3.92 21.12 3.04 21.12 5.83 C21.12 6.39 20.8 10.51 20.61 11.18 C20.11 12.97 18.6 13.73 16.97 13.83 L16.23 13.79 Q15.48 13.74 16.2 13.92 L16.93 14.11 C19.38 14.98 19.81 16.76 18.08 18.53 C15.07 21.61 13.39 19.28 12.54 17.35 L12.27 16.65 Q12 15.95 11.73 16.65 L11.46 17.35 C10.61 19.28 8.93 21.61 5.92 18.53 C4.19 16.76 4.62 14.98 7.07 14.11 L7.8 13.92 Q8.52 13.74 7.78 13.79 L7.03 13.83 C5.4 13.73 3.89 12.97 3.39 11.18 C3.2 10.51 2.88 6.39 2.88 5.83 C2.88 3.04 5.32 3.92 6.83 5.05 Z\"/><g class=\"primary\"><path d=\"M6.83 5.05 C8.47 6.28 10.19 8.48 11.27 10.2 L11.64 10.86 Q12 11.51 12.37 10.86 L12.73 10.2 C13.81 8.48 15.53 6.28 17.17 5.05 C18.68 3.92 21.12 3.04 21.12 5.83 C21.12 6.39 20.8 10.51 20.61 11.18 C20.11 12.97 18.6 13.73 16.97 13.83 L16.23 13.79 Q15.48 13.74 16.2 13.92 L16.93 14.11 C19.38 14.98 19.81 16.76 18.08 18.53 C15.07 21.61 13.39 19.28 12.54 17.35 L12.27 16.65 Q12 15.95 11.73 16.65 L11.46 17.35 C10.61 19.28 8.93 21.61 5.92 18.53 C4.19 16.76 4.62 14.98 7.07 14.11 L7.8 13.92 Q8.52 13.74 7.78 13.79 L7.03 13.83 C5.4 13.73 3.89 12.97 3.39 11.18 C3.2 10.51 2.88 6.39 2.88 5.83 C2.88 3.04 5.32 3.92 6.83 5.05 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function BlueskyDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
