// iconaut-react — bone (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M17 11.28 C17.63 10.65 18.35 11.28 19.15 11.28 A2.16 2.16 0 1 0 17 9.12 C17 8.22 17.63 7.59 17 6.96 A2.16 2.16 0 1 0 12.85 6.96 L7.1 12.72 C6.47 13.35 5.75 12.72 4.85 12.72 A2.16 2.16 0 1 0 7.01 14.88 C7.01 15.78 6.38 16.41 7.01 17.04 A2.16 2.16 0 1 0 11.15 17.04 Z\"/><g class=\"primary\"><path d=\"M17 11.28 C17.63 10.65 18.35 11.28 19.15 11.28 A2.16 2.16 0 1 0 17 9.12 C17 8.22 17.63 7.59 17 6.96 A2.16 2.16 0 1 0 12.85 6.96 L7.1 12.72 C6.47 13.35 5.75 12.72 4.85 12.72 A2.16 2.16 0 1 0 7.01 14.88 C7.01 15.78 6.38 16.41 7.01 17.04 A2.16 2.16 0 1 0 11.15 17.04 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function BoneDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
