// iconaut-react — bookmark (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M8.71 3L15.29 3A2.71 2.71 0 0 1 18 5.71L18 18.62A1.64 1.64 0 0 1 15.3 19.88L12.71 17.71A1.1 1.1 0 0 0 11.29 17.71L8.7 19.88A1.64 1.64 0 0 1 6 18.62L6 5.71A2.71 2.71 0 0 1 8.71 3Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M8.71 3.16L15.29 3.16A2.55 2.55 0 0 1 17.84 5.71L17.84 18.58A1.51 1.51 0 0 1 15.36 19.73L12.81 17.58A1.26 1.26 0 0 0 11.19 17.58L8.64 19.73A1.51 1.51 0 0 1 6.16 18.58L6.16 5.71A2.55 2.55 0 0 1 8.71 3.16Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M8.21 3.16L15.79 3.16A2.55 2.55 0 0 1 18.34 5.71L18.34 19.07A1.52 1.52 0 0 1 15.86 20.25L12.84 17.78A1.33 1.33 0 0 0 11.16 17.78L8.14 20.25A1.52 1.52 0 0 1 5.66 19.07L5.66 5.71A2.55 2.55 0 0 1 8.21 3.16Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M8.21 3.15L15.79 3.15A2.56 2.56 0 0 1 18.35 5.71L18.35 19.07A1.53 1.53 0 0 1 15.86 20.25L12.84 17.78A1.32 1.32 0 0 0 11.16 17.78L8.14 20.25A1.53 1.53 0 0 1 5.65 19.07L5.65 5.71A2.56 2.56 0 0 1 8.21 3.15Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function BookmarkSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
