// iconaut-react — book-key (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7.5 3.5 L16.5 3.5 Q18.5 3.5 18.5 5.5 L18.5 18.5 Q18.5 20.5 16.5 20.5 L8 20.5 A2.5 2.5 0 0 1 5.5 18 L5.5 5.5 Q5.5 3.5 7.5 3.5 Z\"/><path d=\"M5.5 18 A2.5 2.5 0 0 1 8 15.5 L18.5 15.5\"/><path d=\"M9.1 9 A1.4 1.4 0 1 0 11.9 9 A1.4 1.4 0 1 0 9.1 9 Z\"/><path d=\"M11.7 10 L 14.6 12.9\"/><path d=\"M13.1 11.4 L 14.1 10.4\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function BookKey({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
