// iconaut-react — book-lock (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7.5 3.5 L16.5 3.5 Q18.5 3.5 18.5 5.5 L18.5 18.5 Q18.5 20.5 16.5 20.5 L8 20.5 A2.5 2.5 0 0 1 5.5 18 L5.5 5.5 Q5.5 3.5 7.5 3.5 Z\"/><path d=\"M5.5 18 A2.5 2.5 0 0 1 8 15.5 L18.5 15.5\"/><path d=\"M10.3 11.4 Q10.3 10 11.7 10 L12.3 10 Q13.7 10 13.7 11.4 L13.7 11.4 Q13.7 12.8 12.3 12.8 L11.7 12.8 Q10.3 12.8 10.3 11.4 Z\"/><path d=\"M11 10 L11 9 A1 1 0 0 1 13 9 L13 10\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function BookLock({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
