// iconaut-react — bookmark (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M7 6 Q7 4 9 4 L15 4 Q17 4 17 6 L17 18 Q17 20 15.47 18.71 L13.53 17.09 Q12 15.8 10.47 17.09 L8.53 18.71 Q7 20 7 18 Z\"/><g class=\"primary\"><path d=\"M7 6 Q7 4 9 4 L15 4 Q17 4 17 6 L17 18 Q17 20 15.47 18.71 L13.53 17.09 Q12 15.8 10.47 17.09 L8.53 18.71 Q7 20 7 18 Z\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6.5 6 Q6.5 4 8.5 4 L15.5 4 Q17.5 4 17.5 6 L17.5 18.5 Q17.5 20.5 15.95 19.23 L13.55 17.27 Q12 16 10.45 17.27 L8.05 19.23 Q6.5 20.5 6.5 18.5 Z\"/><g class=\"primary\"><path d=\"M6.5 6 Q6.5 4 8.5 4 L15.5 4 Q17.5 4 17.5 6 L17.5 18.5 Q17.5 20.5 15.95 19.23 L13.55 17.27 Q12 16 10.45 17.27 L8.05 19.23 Q6.5 20.5 6.5 18.5 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function BookmarkDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
