// iconaut-react — bowling (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z M8.7 9a0.8 0.8 0 1 1 1.6 0a0.8 0.8 0 1 1 -1.6 0Z M11.7 8a0.8 0.8 0 1 1 1.6 0a0.8 0.8 0 1 1 -1.6 0Z M10.2 11a0.8 0.8 0 1 1 1.6 0a0.8 0.8 0 1 1 -1.6 0Z\"/><g class=\"primary\"><path d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z\"/><path d=\"M8.7 9 A0.8 0.8 0 1 1 10.3 9 A0.8 0.8 0 1 1 8.7 9 Z\"/><path d=\"M11.7 8 A0.8 0.8 0 1 1 13.3 8 A0.8 0.8 0 1 1 11.7 8 Z\"/><path d=\"M10.2 11 A0.8 0.8 0 1 1 11.8 11 A0.8 0.8 0 1 1 10.2 11 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function BowlingDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
