// iconaut-react — broom (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M9.06 10.95 Q10.84 10.04 12.25 11.45 L12.55 11.75 Q13.96 13.16 13.05 14.94 L11.33 18.31 Q10.42 20.09 9.01 18.68 L5.32 14.99 Q3.91 13.58 5.69 12.67 Z\"/><g class=\"primary\"><path d=\"M20.8 3.2 L 12.4 11.6\"/><path d=\"M9.95 10.49 Q10.84 10.04 11.55 10.75 L13.25 12.45 Q13.96 13.16 13.51 14.05 L10.87 19.2 Q10.42 20.09 9.71 19.38 L4.62 14.29 Q3.91 13.58 4.8 13.13 Z\"/><path d=\"M8.37 12.94 L 5.82 15.49\"/><path d=\"M11.06 15.63 L 8.51 18.18\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function BroomDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
