// iconaut-react — cable-car (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5 10.9 Q5 8.9 7 8.9 L17 8.9 Q19 8.9 19 10.9 L19 16.5 Q19 18.5 17 18.5 L7 18.5 Q5 18.5 5 16.5 Z\"/><path d=\"M2.5 5.25 L 21.5 3.25\"/><path d=\"M12 4.25 L 12 8.9\"/><path d=\"M5 13.25 L 19 13.25\"/>";
const M1 = "<path d=\"M5 10.9 Q5 8.9 7 8.9 L17 8.9 Q19 8.9 19 10.9 L19 16.5 Q19 18.5 17 18.5 L7 18.5 Q5 18.5 5 16.5 Z\"/><path d=\"M2.5 5.25 L 21.5 3.25\"/><path d=\"M12 4.25 L 12 8.9\"/><path d=\"M5 13.25 L 19 13.25\"/><path d=\"M12 8.9 L 12 13.25\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function CableCar({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
