// iconaut-react — cake (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4 18.45 Q4 20.45 6 20.45 L18 20.45 Q20 20.45 20 18.45 L20 14.45 Q20 12.45 18 12.45 L6 12.45 Q4 12.45 4 14.45 Z\"/><path d=\"M4 15.35 C6 15.35 6 16.85 8 16.85 S10 15.35 12 15.35 S14 16.85 16 16.85 S18 15.35 20 15.35\"/><path d=\"M12 12.45 L 12 7\"/><path d=\"M12 3.8 C12.5 4.6 12.9 5.3 12.9 6 A0.9 0.9 0 0 1 11.1 6 C11.1 5.3 11.5 4.6 12 3.8 Z\"/>";
const M1 = "<path d=\"M4 18.45 Q4 20.45 6 20.45 L18 20.45 Q20 20.45 20 18.45 L20 14.45 Q20 12.45 18 12.45 L6 12.45 Q4 12.45 4 14.45 Z\"/><path d=\"M4 15.35 C5.3 15.35 5.3 16.85 6.7 16.85 S8 15.35 9.3 15.35 S10.7 16.85 12 16.85 S13.3 15.35 14.7 15.35 S16 16.85 17.3 16.85 S18.7 15.35 20 15.35\"/><path d=\"M12 12.45 L 12 7\"/><path d=\"M12 3.8 C12.5 4.6 12.9 5.3 12.9 6 A0.9 0.9 0 0 1 11.1 6 C11.1 5.3 11.5 4.6 12 3.8 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function Cake({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
