// iconaut-react — calendar-fold (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4 7.5 Q4 5.5 6 5.5 L18 5.5 Q20 5.5 20 7.5 L20 13 Q20 15 18.59 16.41 L15.91 19.09 Q14.5 20.5 12.5 20.5 L6 20.5 Q4 20.5 4 18.5 Z\"/><path d=\"M7.5 9.3 L 16.5 9.3 M8 3.5 L 8 5.5 M16 3.5 L 16 5.5\"/><path d=\"M14.35 20.15  L14.5 17   Q14.5 15 16.5 15   L19.65 14.85\"/>";
const M1 = "<path d=\"M3.5 7.5 Q3.5 5.5 5.5 5.5 L18.5 5.5 Q20.5 5.5 20.5 7.5 L20.5 13.9 Q20.5 15.9 19.03 17.25 L15.97 20.05 Q14.5 21.4 12.5 21.4 L5.5 21.4 Q3.5 21.4 3.5 19.4 Z\"/><path d=\"M7 9.3 L 17 9.3 M8 3.5 L 8 5.5 M16 3.5 L 16 5.5\"/><path d=\"M14.5 20.5  L14.5 17  Q14.5 15 16.5 15  L20.38 14.98\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function CalendarFold({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
