// iconaut-react — camera (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 10 Q3 8 5 8 L6.57 8 Q8 8 8.7 6.75 L8.7 6.75 Q9.4 5.5 10.83 5.5 L13.17 5.5 Q14.6 5.5 15.3 6.75 L15.3 6.75 Q16 8 17.43 8 L19 8 Q21 8 21 10 L21 17 Q21 19 19 19 L5 19 Q3 19 3 17 Z\"/><path d=\"M9 13 A3 3 0 1 0 15 13 A3 3 0 1 0 9 13 Z\"/>";
const M1 = "<path d=\"M3 9.5 Q3 7.5 5 7.5 L6.34 7.5 Q7.8 7.5 8.55 6.25 L8.55 6.25 Q9.3 5 10.76 5 L13.24 5 Q14.7 5 15.45 6.25 L15.45 6.25 Q16.2 7.5 17.66 7.5 L19 7.5 Q21 7.5 21 9.5 L21 17.5 Q21 19.5 19 19.5 L5 19.5 Q3 19.5 3 17.5 Z\"/><path d=\"M8.7 13.2 A3.3 3.3 0 1 0 15.3 13.2 A3.3 3.3 0 1 0 8.7 13.2 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Camera({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
