// iconaut-react — camera-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7.73 7.73Q8.32 7.42 8.7 6.75L8.7 6.75Q9.4 5.5 10.83 5.5L13.17 5.5Q14.6 5.5 15.3 6.75L15.3 6.75Q16 8 17.43 8L19 8Q21 8 21 10L21 17Q21 19 19 19M14.23 19L5 19Q3 19 3 17L3 10Q3 8.89 3.62 8.39\"/><path d=\"M9.14 13.92A3 3 0 0 0 11.08 15.86M14.56 14.56A3 3 0 0 0 15 13A3 3 0 0 0 10.44 10.44\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M7.33 7.33Q8.08 7.04 8.55 6.25L8.55 6.25Q9.3 5 10.76 5L13.24 5Q14.7 5 15.45 6.25L15.45 6.25Q16.2 7.5 17.66 7.5L19 7.5Q21 7.5 21 9.5L21 17.5Q21 19.25 19.47 19.47M14.83 19.5L5 19.5Q3 19.5 3 17.5L3 9.5Q3 8.58 3.42 8.09\"/><path d=\"M8.7 13.37A3.3 3.3 0 0 0 11.83 16.5M14.85 14.85A3.3 3.3 0 0 0 15.3 13.2A3.3 3.3 0 0 0 10.35 10.35\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M2 = "<path d=\"M7.33 7.33Q8.08 7.04 8.55 6.25L8.55 6.25Q9.3 5 10.76 5L13.24 5Q14.7 5 15.45 6.25L15.45 6.25Q16.2 7.5 17.66 7.5L19 7.5Q21 7.5 21 9.5L21 17.5Q21 19.25 19.47 19.47M14.9 19.5L5 19.5Q3 19.5 3 17.5L3 9.5Q3 8.55 3.45 8.05\"/><path d=\"M8.7 13.3A3.3 3.3 0 0 0 11.9 16.5M14.85 14.85A3.3 3.3 0 0 0 15.3 13.2A3.3 3.3 0 0 0 10.35 10.35\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M2, 1.75]
};
const S = [16, 20, 24];

export default function CameraOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
