// iconaut-react — caravan (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 8 Q3 6 5 6 L17 6 Q19 6 19 8 L19 14 Q19 16 17 16 L5 16 Q3 16 3 14 Z\"/><path d=\"M5.5 10 Q5.5 8.5 7 8.5 L7.5 8.5 Q9 8.5 9 10 L9 10 Q9 11.5 7.5 11.5 L7 11.5 Q5.5 11.5 5.5 10 Z\"/><path d=\"M12.5 8.5 L14.25 8.5 Q16 8.5 16 10.25 L16 16\"/><path d=\"M19 12 L 22 12\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Caravan({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
