// iconaut-react — carrot (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M11.21 19.16 L7.5 10.5 A5 5 0 0 1 16.5 10.5 L12.79 19.16 Q12 21 11.21 19.16 Z\"/><g class=\"primary\"><path d=\"M11.21 19.16 L7.5 10.5 A5 5 0 0 1 16.5 10.5 L12.79 19.16 Q12 21 11.21 19.16 Z\"/><path d=\"M12 9 L 12 4.5\"/><path d=\"M12 6.5 L 8.5 4.5 M12 6.5 L 15.5 4.5\"/><path d=\"M10.5 13 L 10.51 13 M12.5 16 L 12.51 16\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function CarrotDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
