// iconaut-react — chair (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7 3 L7.22 13.25\"/><path d=\"M7 10 L17 10\"/><path d=\"M17 10 L16.78 13.25\"/><path d=\"M6 21 L6.88 13.99 Q7 13 8 13 L16 13 Q17 13 17.12 13.99 L18 21\"/><path d=\"M6.5 17 L17.5 17\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Chair({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
