// iconaut-react — checks (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 14 L5.79 16.79 Q6.5 17.5 7.21 16.79 L17.5 6.5\"/><path d=\"M12.5 15.5 L13.79 16.79 Q14.5 17.5 15.21 16.79 L21 11\"/>";
const M1 = "<path d=\"M3.5 14 L6.29 16.79 Q7 17.5 7.71 16.79 L18 6.5\"/><path d=\"M11.5 15.5 L12.79 16.79 Q13.5 17.5 14.21 16.79 L20.5 10.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function Checks({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
