// iconaut-react — chevron-right (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M9 6.5 L14.26 11.32 Q15 12 14.26 12.68 L9 17.5\"/>";
const M1 = "<path d=\"M8.5 6 L14.74 11.35 Q15.5 12 14.74 12.65 L8.5 18\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function ChevronRight({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
