// iconaut-react — circle-off (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z\"/><g class=\"primary\"><path d=\"M18.36 18.36A9 9 0 0 0 21 12A9 9 0 0 0 5.64 5.64M3.66 8.61A9 9 0 0 0 3 12A9 9 0 0 0 15.39 20.34\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z\"/><g class=\"primary\"><path d=\"M18.36 18.36A9 9 0 0 0 21 12A9 9 0 0 0 5.64 5.64M3.79 8.3A9 9 0 0 0 3 12A9 9 0 0 0 15.7 20.21\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
const M2 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z\"/><g class=\"primary\"><path d=\"M18.36 18.36A9 9 0 0 0 21 12A9 9 0 0 0 5.64 5.64M3.8 8.3A9 9 0 0 0 3 12A9 9 0 0 0 15.7 20.2\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
const M3 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z\"/><g class=\"primary\"><path d=\"M18.36 18.36A9 9 0 0 0 21 12A9 9 0 0 0 5.64 5.64M3.79 8.31A9 9 0 0 0 3 12A9 9 0 0 0 15.69 20.21\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M1, 1.688],
  20: [M2, 1.68],
  24: [M3, 1.7]
};
const S = [12, 16, 20, 24];

export default function CircleOffDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
