// iconaut-react — clipboard-heart (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 7.5 Q5.5 5.5 7.5 5.5 L16.5 5.5 Q18.5 5.5 18.5 7.5 L18.5 18.5 Q18.5 20.5 16.5 20.5 L7.5 20.5 Q5.5 20.5 5.5 18.5 Z\"/><path d=\"M9.5 5.5 L9.5 4.5 Q9.5 3.5 10.5 3.5 L13.5 3.5 Q14.5 3.5 14.5 4.5 L14.5 5.5\"/><path d=\"M12 17 C11.52 16.7 8.8 15 8.8 12.6 A1.8 1.8 0 0 1 12 11.6 A1.8 1.8 0 0 1 15.2 12.6 C15.2 15 12.48 16.7 12 17 Z\"/>";
const M1 = "<path d=\"M5 7 Q5 5 7 5 L17 5 Q19 5 19 7 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z\"/><path d=\"M9 5 L9 4 Q9 3 10 3 L14 3 Q15 3 15 4 L15 5\"/><path d=\"M12 17 C11.52 16.7 8.8 15 8.8 12.6 A1.8 1.8 0 0 1 12 11.6 A1.8 1.8 0 0 1 15.2 12.6 C15.2 15 12.48 16.7 12 17 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function ClipboardHeart({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
