// iconaut-react — cloudy (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M9 20 L17.5 20 A3.4 3.4 0 0 0 17.7 13.3 A4.8 4.8 0 0 0 8.3 12.4 A3.6 3.6 0 0 0 9 20 Z\"/><g class=\"primary\"><path d=\"M9 20 L17.5 20 A3.4 3.4 0 0 0 17.7 13.3 A4.8 4.8 0 0 0 8.3 12.4 A3.6 3.6 0 0 0 9 20 Z\"/><path d=\"M6.42 13.1 A3.2 3.2 0 0 1 5.2 6.9 A2.6 2.6 0 0 1 6.9 6.2 A3.8 3.8 0 0 1 13.6 6.9 A3.1 3.1 0 0 1 14.25 9.1\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function CloudyDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
