// iconaut-react — cloud-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M18.23 18.23A3.71 4.15 0 0 0 17 10.21A5.2 5.82 0 0 0 7.74 7.74M4.87 9.82A4.25 4.77 0 0 0 7.5 18.5L13.55 18.5\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M18.23 18.23A3.71 4.15 0 0 0 17 10.21A5.2 5.82 0 0 0 7.74 7.74M5.13 9.64A4.25 4.77 0 0 0 7.5 18.5L13.99 18.5\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M2 = "<path d=\"M18.53 18.53A4 4.48 0 0 0 17.4 10.15A5.6 6.27 0 0 0 7.45 7.45M4.91 9.41A4.5 5.04 0 0 0 7 19L14.5 19\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M3 = "<path d=\"M18.53 18.53A4 4.48 0 0 0 17.4 10.15A5.6 6.27 0 0 0 7.45 7.45M4.89 9.42A4.5 5.04 0 0 0 7 19L14.47 19\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M1, 1.688],
  20: [M2, 1.68],
  24: [M3, 1.7]
};
const S = [12, 16, 20, 24];

export default function CloudOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
