// iconaut-react — cloud-heart (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7.5 18.5 L16.8 18.5 A3.7 4.14 0 0 0 17 10.21 A5.2 5.82 0 0 0 7.1 8.98 A4 4.48 0 0 0 7.5 18.5 Z\"/><path d=\"M11.65 15.3 C11.28 15.06 9.15 13.71 9.15 11.97 A1.41 1.41 0 0 1 11.65 11.15 A1.41 1.41 0 0 1 14.16 11.97 C14.16 13.71 12.03 15.06 11.65 15.3 Z\"/>";
const M1 = "<path d=\"M7 19 L17.2 19 A4 4.48 0 0 0 17.4 10.15 A5.6 6.27 0 0 0 6.7 8.92 A4.3 4.82 0 0 0 7 19 Z\"/><path d=\"M11.68 15.57 C11.28 15.31 9.01 13.86 9.01 12 A1.51 1.51 0 0 1 11.68 11.12 A1.51 1.51 0 0 1 14.37 12 C14.37 13.86 12.09 15.31 11.68 15.57 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function CloudHeart({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
