// iconaut-react — clover (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M12 12 C12 12 9 10 9 8 A1.6 1.6 0 0 1 12 7 A1.6 1.6 0 0 1 15 8 C15 10 12 12 12 12 Z M12 12 C12 12 14 9 16 9 A1.6 1.6 0 0 1 17 12 A1.6 1.6 0 0 1 16 15 C14 15 12 12 12 12 Z M12 12 C12 12 15 14 15 16 A1.6 1.6 0 0 1 12 17 A1.6 1.6 0 0 1 9 16 C9 14 12 12 12 12 Z M12 12 C12 12 10 15 8 15 A1.6 1.6 0 0 1 7 12 A1.6 1.6 0 0 1 8 9 C10 9 12 12 12 12 Z\"/><path d=\"M12 17 L 12 21\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Clover({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
