// iconaut-react — cocktail (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4.46 11.48 Q4.21 9.5 6.21 9.5 L13.71 9.5 Q15.71 9.5 15.46 11.48 L14.56 18.52 Q14.31 20.5 12.31 20.5 L7.61 20.5 Q5.61 20.5 5.36 18.52 Z\"/><g class=\"primary\"><path d=\"M4.46 11.48 Q4.21 9.5 6.21 9.5 L13.71 9.5 Q15.71 9.5 15.46 11.48 L14.56 18.52 Q14.31 20.5 12.31 20.5 L7.61 20.5 Q5.61 20.5 5.36 18.52 Z\"/><path d=\"M13.19 9.5 A3.4 3.4 0 1 1 15.44 11.66 L15.58 10.58 Q15.71 9.5 14.62 9.5 L13.19 9.5 Z\"/><path d=\"M8.71 9.5 L11.04 4.32 Q11.41 3.5 12.31 3.5 L13.21 3.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function CocktailDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
