// iconaut-react — coins-stack (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4 8.5 A8 2.5 0 0 1 20 8.5 L20 15.5 A8 2.5 0 0 1 4 15.5 Z\"/><path d=\"M4 8.5 A8 2.5 0 0 0 20 8.5\"/><path d=\"M4 12 A8 2.5 0 0 0 20 12\"/>";
const M1 = "<path d=\"M4 7.5 A8 2.5 0 0 1 20 7.5 L20 16.5 A8 2.5 0 0 1 4 16.5 Z\"/><path d=\"M4 7.5 A8 2.5 0 0 0 20 7.5\"/><path d=\"M4 10.5 A8 2.5 0 0 0 20 10.5\"/><path d=\"M4 13.5 A8 2.5 0 0 0 20 13.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function CoinsStack({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
