// iconaut-react — collapse (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M17.3 10.7 L14.3 10.7 Q13.3 10.7 13.3 9.7 L13.3 6.7\"/><path d=\"M6.7 13.3 L9.7 13.3 Q10.7 13.3 10.7 14.3 L10.7 17.3\"/><path d=\"M13.55 10.45 L18 6\"/><path d=\"M10.45 13.55 L6 18\"/>";
const M1 = "<path d=\"M18.2 10.5 L14.5 10.5 Q13.5 10.5 13.5 9.5 L13.5 5.8\"/><path d=\"M5.8 13.5 L9.5 13.5 Q10.5 13.5 10.5 14.5 L10.5 18.2\"/><path d=\"M13.75 10.25 L19 5\"/><path d=\"M10.25 13.75 L5 19\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function Collapse({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
