// iconaut-react — cookie (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z\"/><path d=\"M9 9 L 9.01 9 M14.5 8.5 L 14.51 8.5 M15.5 13 L 15.51 13 M9.5 15 L 9.51 15 M12 12 L 12.01 12\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Cookie({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
