// iconaut-react — cow (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5 11 A5 5 0 0 1 8 6.5 A4 4 0 0 1 16 6.5 A5 5 0 0 1 19 11 C19 15 16 18 12 18 S5 15 5 11 Z\"/><g class=\"primary\"><path d=\"M5 11 A5 5 0 0 1 8 6.5 A4 4 0 0 1 16 6.5 A5 5 0 0 1 19 11 C19 15 16 18 12 18 S5 15 5 11 Z\"/><path d=\"M5 9 L 2.5 8 M19 9 L 21.5 8\"/><path d=\"M8 6 L 7.5 3.5 M16 6 L 16.5 3.5\"/><path d=\"M9.5 10 L 9.51 10 M14.5 10 L 14.51 10\"/><path d=\"M9 14.5 A3 2 0 0 0 15 14.5\"/><path d=\"M10.5 14 L 10.51 14 M13.5 14 L 13.51 14\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function CowDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
