// iconaut-react — crown (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.02 8.76 Q3.6 6.8 5.18 8.03 L6.62 9.17 Q8.2 10.4 9.25 8.69 L10.95 5.91 Q12 4.2 13.05 5.91 L14.75 8.69 Q15.8 10.4 17.38 9.17 L18.82 8.03 Q20.4 6.8 19.98 8.76 L18.82 14.24 Q18.4 16.2 16.4 16.2 L7.6 16.2 Q5.6 16.2 5.18 14.24 Z\"/><path d=\"M12 12.4 L 12.01 12.4\"/><path d=\"M5.6 19.8 L 18.4 19.8\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Crown({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
