// iconaut-react — cup (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M9.2 4 L14.8 4 Q16.8 4 16.8 6 L16.8 8 A4.8 5.2 0 0 1 7.2 8 L7.2 6 Q7.2 4 9.2 4 Z\"/><path d=\"M7.2 5.2 C4.8 5.2 3.3 6.2 3.3 8 C3.3 10.2 5.4 11.6 8.3 11.8\"/><path d=\"M16.8 5.2 C19.2 5.2 20.7 6.2 20.7 8 C20.7 10.2 18.6 11.6 15.7 11.8\"/><path d=\"M12 13.2 L 12 16.6\"/><path d=\"M8 20.4 C8 18.2 9.8 16.8 12 16.8 C14.2 16.8 16 18.2 16 20.4 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Cup({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
