// iconaut-react — cupcake (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M7 14 A3 3 0 1 1 7 8 A5 5 0 0 1 17 8 A3 3 0 1 1 17 14 Z\"/><g class=\"primary\"><path d=\"M7 14 A3 3 0 1 1 7 8 A5 5 0 0 1 17 8 A3 3 0 1 1 17 14 Z\"/><path d=\"M5.5 14 L6.72 18.57 Q7.24 20.5 9.24 20.5 L14.76 20.5 Q16.76 20.5 17.28 18.57 L18.5 14\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function CupcakeDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
