// iconaut-react — cupcake (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6.5 12.95 Q6.25 10.97 8.25 10.97 L15.75 10.97 Q17.75 10.97 17.5 12.95 L16.85 18.19 Q16.6 20.17 14.6 20.17 L9.4 20.17 Q7.4 20.17 7.15 18.19 Z\"/><path d=\"M6.25 10.97 A5.75 4.6 0 0 1 17.75 10.97\"/><path d=\"M10.62 5.22 A1.38 1.38 0 1 1 13.38 5.22 A1.38 1.38 0 1 1 10.62 5.22 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function Cupcake({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
