// iconaut-react — database (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M4.5 6.9 C4.5 5.6 7.9 4.5 12 4.5 C16.1 4.5 19.5 5.6 19.5 6.9 L19.5 17.1 C19.5 18.4 16.1 19.5 12 19.5 C7.9 19.5 4.5 18.4 4.5 17.1 Z M4.5 6.9 C4.5 8.2 7.9 9.3 12 9.3 C16.1 9.3 19.5 8.2 19.5 6.9 L19.5 6.1 C19.5 7.4 16.1 8.5 12 8.5 C7.9 8.5 4.5 7.4 4.5 6.1 Z M4.5 12 C4.5 13.3 7.9 14.4 12 14.4 C16.1 14.4 19.5 13.3 19.5 12 L19.5 12.9 C19.5 14.2 16.1 15.3 12 15.3 C7.9 15.3 4.5 14.2 4.5 12.9 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M4 6.5 C4 5.1 7.6 4 12 4 C16.4 4 20 5.1 20 6.5 L20 17.5 C20 18.9 16.4 20 12 20 C7.6 20 4 18.9 4 17.5 Z M4 6.5 C4 7.9 7.6 9 12 9 C16.4 9 20 7.9 20 6.5 L20 5.6 C20 7 16.4 8.1 12 8.1 C7.6 8.1 4 7 4 5.6 Z M4 12 C4 13.4 7.6 14.5 12 14.5 C16.4 14.5 20 13.4 20 12 L20 12.9 C20 14.3 16.4 15.4 12 15.4 C7.6 15.4 4 14.3 4 12.9 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M0, null],
  20: [M1, null],
  24: [M1, null]
};
const S = [12, 16, 20, 24];

export default function DatabaseSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
