// iconaut-react — diamond (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M13.87 3.74L20.26 10.13A2.64 2.64 0 0 1 20.26 13.87L13.87 20.26A2.64 2.64 0 0 1 10.13 20.26L3.74 13.87A2.64 2.64 0 0 1 3.74 10.13L10.13 3.74A2.64 2.64 0 0 1 13.87 3.74Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M13.84 3.77L20.23 10.16A2.61 2.61 0 0 1 20.23 13.84L13.84 20.23A2.61 2.61 0 0 1 10.16 20.23L3.77 13.84A2.61 2.61 0 0 1 3.77 10.16L10.16 3.77A2.61 2.61 0 0 1 13.84 3.77Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M13.83 3.79L20.21 10.17A2.58 2.58 0 0 1 20.21 13.83L13.83 20.21A2.58 2.58 0 0 1 10.17 20.21L3.79 13.83A2.58 2.58 0 0 1 3.79 10.17L10.17 3.79A2.58 2.58 0 0 1 13.83 3.79Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function DiamondSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
