// iconaut-react — discord (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6.42 5.98 L8.9 5.22 Q9.42 5.06 9.67 5.55 L9.92 6.03 C11.29 5.82 12.68 5.82 14.09 6.03 L14.34 5.55 Q14.58 5.06 15.1 5.22 L17.57 5.98 Q18.33 6.21 18.75 6.89 L19.17 7.57 C20.43 9.83 21.12 12.3 21.11 15.03 L21.07 15.83 Q21.03 16.63 20.31 16.99 L17.24 18.53 Q16.42 18.94 15.95 18.16 L15.86 18.02 Q15.47 17.37 16.02 16.85 L16.58 16.33 C13.63 17.69 10.39 17.69 7.41 16.33 L7.97 16.85 Q8.52 17.37 8.13 18.02 L8.05 18.16 Q7.58 18.94 6.76 18.53 L3.69 16.99 Q2.97 16.63 2.93 15.83 L2.89 15.03 C2.88 12.57 3.43 10.1 4.83 7.57 L5.25 6.89 Q5.66 6.21 6.42 5.98 Z\"/><g class=\"primary\"><path d=\"M6.42 5.98 L8.9 5.22 Q9.42 5.06 9.67 5.55 L9.92 6.03 C11.29 5.82 12.68 5.82 14.09 6.03 L14.34 5.55 Q14.58 5.06 15.1 5.22 L17.57 5.98 Q18.33 6.21 18.75 6.89 L19.17 7.57 C20.43 9.83 21.12 12.3 21.11 15.03 L21.07 15.83 Q21.03 16.63 20.31 16.99 L17.24 18.53 Q16.42 18.94 15.95 18.16 L15.86 18.02 Q15.47 17.37 16.02 16.85 L16.58 16.33 C13.63 17.69 10.39 17.69 7.41 16.33 L7.97 16.85 Q8.52 17.37 8.13 18.02 L8.05 18.16 Q7.58 18.94 6.76 18.53 L3.69 16.99 Q2.97 16.63 2.93 15.83 L2.89 15.03 C2.88 12.57 3.43 10.1 4.83 7.57 L5.25 6.89 Q5.66 6.21 6.42 5.98 Z\"/><path d=\"M8.68 12.76 L 8.69 12.76\"/><path d=\"M15.33 12.76 L 15.34 12.76\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function DiscordDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
