// iconaut-react — dog (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 4.8 C13.5 4.8 14 5.4 14.6 6 C16 5 18.5 5.2 19 6.5 C19.6 8.5 19.4 11.5 18.2 13 C17.5 13.8 16.8 14 16 14.2 C16 16 14.5 18.8 12 18.8 C9.5 18.8 8 16 8 14.2 C7.2 14 6.5 13.8 5.8 13 C4.6 11.5 4.4 8.5 5 6.5 C5.5 5.2 8 5 9.4 6 C10 5.4 10.5 4.8 12 4.8 Z\"/><g class=\"primary\"><path d=\"M12 4.8 C13.5 4.8 14 5.4 14.6 6 C16 5 18.5 5.2 19 6.5 C19.6 8.5 19.4 11.5 18.2 13 C17.5 13.8 16.8 14 16 14.2 C16 16 14.5 18.8 12 18.8 C9.5 18.8 8 16 8 14.2 C7.2 14 6.5 13.8 5.8 13 C4.6 11.5 4.4 8.5 5 6.5 C5.5 5.2 8 5 9.4 6 C10 5.4 10.5 4.8 12 4.8 Z\"/><path d=\"M9.6 11 L 9.61 11\"/><path d=\"M14.4 11 L 14.41 11\"/><path d=\"M12 14 L 12.01 14\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function DogDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
