// iconaut-react — donut (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M11.69 3.01 A9 9 0 1 0 20.46 8.92 A3.29 3.29 0 0 1 16.31 5.62 A3.29 3.29 0 0 1 11.69 3.01 Z M9.3 12a2.7 2.7 0 1 1 5.4 0a2.7 2.7 0 1 1 -5.4 0Z\"/><g class=\"primary\"><path d=\"M11.69 3.01 A9 9 0 1 0 20.46 8.92 A3.29 3.29 0 0 1 16.31 5.62 A3.29 3.29 0 0 1 11.69 3.01 Z\"/><path d=\"M9.3 12 A2.7 2.7 0 1 0 14.7 12 A2.7 2.7 0 1 0 9.3 12 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function DonutDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
