// iconaut-react — drill (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4 7 L11 7 Q12 7 12 8 L12 12 Q12 13 11 13 L8 13 Q7 13 6.84 13.99 L6.16 18.01 Q6 19 7 19 L9 19\"/><path d=\"M12 8.5 L14 8.5 Q15 8.5 15.98 8.7 L19.02 9.3 Q20 9.5 20 10.5 L20 10.5 Q20 11.5 19.02 11.7 L15.98 12.3 Q15 12.5 14 12.5 L12 12.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Drill({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
