// iconaut-react — drum (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4 9.5 C4 8.12 7.58 7 12 7 C16.42 7 20 8.12 20 9.5 L20 17.5 C20 18.88 16.42 20 12 20 C7.58 20 4 18.88 4 17.5 Z\"/><path d=\"M4 9.5 C4 10.88 7.58 12 12 12 C16.42 12 20 10.88 20 9.5\"/><path d=\"M4.8 3 L 11.4 7\"/><path d=\"M19.2 3 L 12.6 7\"/>";
const M1 = "<path d=\"M4 9.5 C4 8.12 7.58 7 12 7 C16.42 7 20 8.12 20 9.5 L20 17.5 C20 18.88 16.42 20 12 20 C7.58 20 4 18.88 4 17.5 Z\"/><path d=\"M4 9.5 C4 10.88 7.58 12 12 12 C16.42 12 20 10.88 20 9.5\"/><path d=\"M8 11.7 L 8 19.7\"/><path d=\"M16 11.7 L 16 19.7\"/><path d=\"M4.8 3 L 11.4 7\"/><path d=\"M19.2 3 L 12.6 7\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function Drum({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
