// iconaut-react — dumbbell (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5 8.9 A1.1 1.1 0 0 1 6.1 7.8 L6.9 7.8 A1.1 1.1 0 0 1 8 8.9 L8 15.1 A1.1 1.1 0 0 1 6.9 16.2 L6.1 16.2 A1.1 1.1 0 0 1 5 15.1 Z\"/><path d=\"M16 8.9 A1.1 1.1 0 0 1 17.1 7.8 L17.9 7.8 A1.1 1.1 0 0 1 19 8.9 L19 15.1 A1.1 1.1 0 0 1 17.9 16.2 L17.1 16.2 A1.1 1.1 0 0 1 16 15.1 Z\"/><path d=\"M8 12 L 16 12\"/><path d=\"M2.9 12 L 5 12 M19 12 L 21.1 12\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function Dumbbell({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
