// iconaut-react — ear-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M8.29 3.78A6 6 0 0 1 18 8.5C18 10.18 17.43 11.3 16.68 12.17M12.97 17.47A3.25 3.25 0 0 1 6.5 17\"/><path d=\"M15 8.5A2.5 2.5 0 0 0 11 6.5\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M8.29 3.79A6 6 0 0 1 18 8.5C18 10.19 17.43 11.3 16.68 12.18M12.97 17.46A3.25 3.25 0 0 1 6.5 17\"/><path d=\"M15 8.5A2.5 2.5 0 0 0 11 6.5\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M2 = "<path d=\"M8.3 3.78A6 6 0 0 1 18 8.5C18 10.18 17.44 11.29 16.69 12.16M12.96 17.49A3.25 3.25 0 0 1 6.5 17\"/><path d=\"M15 8.5A2.5 2.5 0 0 0 11.01 6.49\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M2, 1.7]
};
const S = [16, 20, 24];

export default function EarOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
