// iconaut-react — ear-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M8.44 3.67A6 6 0 0 1 18 8.5C18 10.09 17.49 11.18 16.8 12.03M12.92 17.7A3.25 3.25 0 0 1 6.5 17\"/><path d=\"M15 8.5A2.5 2.5 0 0 0 11.16 6.39\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M8.38 3.71A6 6 0 0 1 18 8.5C18 10.13 17.47 11.23 16.75 12.09M12.94 17.61A3.25 3.25 0 0 1 6.5 17\"/><path d=\"M15 8.5A2.5 2.5 0 0 0 11.1 6.43\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M2 = "<path d=\"M8.34 3.74A6 6 0 0 1 18 8.5C18 10.15 17.45 11.26 16.72 12.13M12.95 17.55A3.25 3.25 0 0 1 6.5 17\"/><path d=\"M15 8.5A2.5 2.5 0 0 0 11.06 6.46\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M2, 1.75]
};
const S = [16, 20, 24];

export default function EarOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
