// iconaut-react — ear (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6 8.5 A6 6 0 1 1 18 8.5 C18 13.5 13 13.5 13 17 A3.2 3.2 0 1 1 6.5 17\"/><path d=\"M15 8.5 A2.5 2.5 0 0 0 10 8.5 L10 9.5 A2 2 0 1 1 10 13.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Ear({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
