// iconaut-react — edit-off (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M14.61 5.24 Q16 3.8 17.41 5.21 L18.79 6.59 Q20.2 8 18.79 9.41 L10.21 17.99 Q8.8 19.4 6.85 19.85 L5.55 20.15 Q3.6 20.6 4.05 18.65 L4.35 17.35 Q4.8 15.4 6.19 13.96 Z\"/><g class=\"primary\"><path d=\"M11.71 16.49L10.21 17.99Q8.8 19.4 6.85 19.85L5.55 20.15Q3.6 20.6 4.05 18.65L4.35 17.35Q4.8 15.4 6.19 13.96L7.66 12.44M10.01 10.01L14.61 5.24Q16 3.8 17.41 5.21L18.79 6.59Q20.2 8 18.79 9.41L14.1 14.1\"/><path d=\"M13.6 6.2L17.8 10.4\"/><path d=\"M3.75 3.75L20.25 20.25\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M14.46 5.08 Q15.8 3.6 17.21 5.01 L18.99 6.79 Q20.4 8.2 18.99 9.61 L10.01 18.59 Q8.6 20 6.65 20.45 L5.35 20.75 Q3.4 21.2 3.85 19.25 L4.15 17.95 Q4.6 16 5.94 14.52 Z\"/><g class=\"primary\"><path d=\"M11.97 16.63L10.01 18.59Q8.6 20 6.65 20.45L5.35 20.75Q3.4 21.2 3.85 19.25L4.15 17.95Q4.6 16 5.94 14.52L7.8 12.46M10.01 10.01L14.46 5.08Q15.8 3.6 17.21 5.01L18.99 6.79Q20.4 8.2 18.99 9.61L14.3 14.3\"/><path d=\"M13.4 6L18 10.6\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
const M2 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M14.46 5.08 Q15.8 3.6 17.21 5.01 L18.99 6.79 Q20.4 8.2 18.99 9.61 L10.01 18.59 Q8.6 20 6.65 20.45 L5.35 20.75 Q3.4 21.2 3.85 19.25 L4.15 17.95 Q4.6 16 5.94 14.52 Z\"/><g class=\"primary\"><path d=\"M12 16.6L10.01 18.59Q8.6 20 6.65 20.45L5.35 20.75Q3.4 21.2 3.85 19.25L4.15 17.95Q4.6 16 5.94 14.52L7.83 12.43M10.01 10.01L14.46 5.08Q15.8 3.6 17.21 5.01L18.99 6.79Q20.4 8.2 18.99 9.61L14.3 14.3\"/><path d=\"M13.4 6L18 10.6\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M2, 1.75]
};
const S = [16, 20, 24];

export default function EditOffDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
