// iconaut-react — eraser (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6.5 18.5 Q4.5 18.5 5.91 17.09 L15.59 7.41 Q17 6 18.41 7.41 L18.59 7.59 Q20 9 18.59 10.41 L11.91 17.09 Q10.5 18.5 8.5 18.5 Z\"/><g class=\"primary\"><path d=\"M6.5 18.5 Q4.5 18.5 5.91 17.09 L15.59 7.41 Q17 6 18.41 7.41 L18.59 7.59 Q20 9 18.59 10.41 L11.91 17.09 Q10.5 18.5 8.5 18.5 Z\"/><path d=\"M12.5 10.5 L 15.5 13.5\"/><path d=\"M10.35 18.15 L 20 18.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function EraserDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
