// iconaut-react — exclude (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M5.71 3.16L13.59 3.16A2.25 2.25 0 0 1 15.84 5.41L15.84 7.3A0.86 0.86 0 0 0 16.7 8.16L18.59 8.16A2.25 2.25 0 0 1 20.84 10.41L20.84 18.29A2.55 2.55 0 0 1 18.29 20.84L10.41 20.84A2.25 2.25 0 0 1 8.16 18.59L8.16 16.7A0.86 0.86 0 0 0 7.3 15.84L5.41 15.84A2.25 2.25 0 0 1 3.16 13.59L3.16 5.71A2.55 2.55 0 0 1 5.71 3.16Z M15 15L9 15L9 9L15 9Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M5.71 3.16L13.59 3.16A2.25 2.25 0 0 1 15.84 5.41L15.84 7.29A0.87 0.87 0 0 0 16.71 8.16L18.59 8.16A2.25 2.25 0 0 1 20.84 10.41L20.84 18.29A2.55 2.55 0 0 1 18.29 20.84L10.41 20.84A2.25 2.25 0 0 1 8.16 18.59L8.16 16.71A0.87 0.87 0 0 0 7.29 15.84L5.41 15.84A2.25 2.25 0 0 1 3.16 13.59L3.16 5.71A2.55 2.55 0 0 1 5.71 3.16Z M15 15L9 15L9 9L15 9Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M5.71 3.15L13.6 3.15A2.25 2.25 0 0 1 15.85 5.4L15.85 7.29A0.86 0.86 0 0 0 16.71 8.15L18.6 8.15A2.25 2.25 0 0 1 20.85 10.4L20.85 18.29A2.56 2.56 0 0 1 18.29 20.85L10.4 20.85A2.25 2.25 0 0 1 8.15 18.6L8.15 16.71A0.86 0.86 0 0 0 7.29 15.85L5.4 15.85A2.25 2.25 0 0 1 3.15 13.6L3.15 5.71A2.56 2.56 0 0 1 5.71 3.15Z M15 15L9 15L9 9L15 9Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function ExcludeSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
