// iconaut-react — expand (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M13.3 6 L17 6 Q18 6 18 7 L18 10.7\"/><path d=\"M10.7 18 L7 18 Q6 18 6 17 L6 13.3\"/><path d=\"M18 6 L 13.3 10.7\"/><path d=\"M6 18 L 10.7 13.3\"/>";
const M1 = "<path d=\"M14.3 5 L18 5 Q19 5 19 6 L19 9.7\"/><path d=\"M9.7 19 L6 19 Q5 19 5 18 L5 14.3\"/><path d=\"M19 5 L 13.5 10.5\"/><path d=\"M5 19 L 10.5 13.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function ExpandDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
