// iconaut-react — eye-off (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 6 C6.5 6 3 12 3 12 S6.5 18 12 18 S21 12 21 12 S17.5 6 12 6 Z M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0Z\"/><g class=\"primary\"><path d=\"M12 6 C6.5 6 3 12 3 12 S6.5 18 12 18 S21 12 21 12 S17.5 6 12 6 Z\"/><circle cx=\"12\" cy=\"12\" r=\"2.7\"/><path d=\"M3.75 3.75 L 20.25 20.25\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 5.5 C5.8 5.5 2.5 12 2.5 12 S5.8 18.5 12 18.5 S21.5 12 21.5 12 S18.2 5.5 12 5.5 Z M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0Z\"/><g class=\"primary\"><path d=\"M12 5.5 C5.8 5.5 2.5 12 2.5 12 S5.8 18.5 12 18.5 S21.5 12 21.5 12 S18.2 5.5 12 5.5 Z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M3.5 3.5 L 20.5 20.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function EyeOffDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
