// iconaut-react — factory (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M2.66 18.79L2.66 5.77A2.11 2.11 0 0 1 4.77 3.66L5.23 3.66A2.11 2.11 0 0 1 7.34 5.77L7.34 9.89L6.48 13.03L8.66 10.62L11.6 8.75L12.03 9.43L12.84 9.43L12.84 9.97L12.03 12.93L14.09 10.64L18.8 7.6A1.65 1.65 0 0 1 21.34 8.98L21.34 18.79A2.55 2.55 0 0 1 18.79 21.34L5.21 21.34A2.55 2.55 0 0 1 2.66 18.79Z M10.5 21.34L10.5 17.35A1.35 1.35 0 0 1 11.85 16L12.15 16A1.35 1.35 0 0 1 13.5 17.35L13.5 21.34L10.5 21.34Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M2.66 18.79L2.66 5.77A2.11 2.11 0 0 1 4.77 3.66L5.23 3.66A2.11 2.11 0 0 1 7.34 5.77L7.34 9.91L6.48 13.03L8.66 10.63L11.6 8.76L12.04 9.43L12.84 9.43L12.84 9.98L12.04 12.94L14.08 10.66L18.8 7.6A1.64 1.64 0 0 1 21.34 8.98L21.34 18.79A2.55 2.55 0 0 1 18.79 21.34L5.21 21.34A2.55 2.55 0 0 1 2.66 18.79Z M10.5 21.34L10.5 17.35A1.35 1.35 0 0 1 11.85 16L12.15 16A1.35 1.35 0 0 1 13.5 17.35L13.5 21.34L10.5 21.34Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M2.65 18.79L2.65 5.77A2.12 2.12 0 0 1 4.76 3.65L5.24 3.65A2.12 2.12 0 0 1 7.35 5.77L7.35 9.88L6.49 13.02L8.68 10.61L11.61 8.74L12.04 9.42L12.85 9.42L12.85 9.95L12.04 12.93L14.1 10.63L18.8 7.59A1.65 1.65 0 0 1 21.35 8.98L21.35 18.79A2.56 2.56 0 0 1 18.79 21.35L5.21 21.35A2.56 2.56 0 0 1 2.65 18.79Z M10.5 21.35L10.5 17.35A1.35 1.35 0 0 1 11.85 16L12.15 16A1.35 1.35 0 0 1 13.5 17.35L13.5 21.35L10.5 21.35Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function FactorySolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
