// iconaut-react — fence (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3.9 10.4 Q2.9 10.4 2.9 9.4 L2.9 7.4 Q2.9 6.4 3.5 5.6 L4.1 4.8 Q4.7 4 5.3 4.8 L5.9 5.6 Q6.5 6.4 6.5 7.4 L6.5 9.4 Q6.5 10.4 5.5 10.4 Z\"/><path d=\"M3.9 14.6 Q2.9 14.6 2.9 15.6 L2.9 19.4 Q2.9 20.4 3.9 20.4 L5.5 20.4 Q6.5 20.4 6.5 19.4 L6.5 15.6 Q6.5 14.6 5.5 14.6 Z\"/><path d=\"M11.2 10.4 Q10.2 10.4 10.2 9.4 L10.2 7.4 Q10.2 6.4 10.8 5.6 L11.4 4.8 Q12 4 12.6 4.8 L13.2 5.6 Q13.8 6.4 13.8 7.4 L13.8 9.4 Q13.8 10.4 12.8 10.4 Z\"/><path d=\"M11.2 14.6 Q10.2 14.6 10.2 15.6 L10.2 19.4 Q10.2 20.4 11.2 20.4 L12.8 20.4 Q13.8 20.4 13.8 19.4 L13.8 15.6 Q13.8 14.6 12.8 14.6 Z\"/><path d=\"M18.5 10.4 Q17.5 10.4 17.5 9.4 L17.5 7.4 Q17.5 6.4 18.1 5.6 L18.7 4.8 Q19.3 4 19.9 4.8 L20.5 5.6 Q21.1 6.4 21.1 7.4 L21.1 9.4 Q21.1 10.4 20.1 10.4 Z\"/><path d=\"M18.5 14.6 Q17.5 14.6 17.5 15.6 L17.5 19.4 Q17.5 20.4 18.5 20.4 L20.1 20.4 Q21.1 20.4 21.1 19.4 L21.1 15.6 Q21.1 14.6 20.1 14.6 Z\"/><path d=\"M2.9 11.4 Q2.9 10.4 3.9 10.4 L20.1 10.4 Q21.1 10.4 21.1 11.4 L21.1 13.6 Q21.1 14.6 20.1 14.6 L3.9 14.6 Q2.9 14.6 2.9 13.6 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Fence({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
