// iconaut-react — ferry (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6.5 13 Q4.5 13 4.5 11 L4.5 10.5 Q4.5 8.5 6.5 8.5 L13.5 8.5 Q15.5 8.5 16.61 10.16 L17.39 11.34 Q18.5 13 16.5 13 Z\"/><path d=\"M3.31 14.83 Q2.5 13 4.5 13 L19.5 13 Q21.5 13 20.69 14.83 L20.31 15.67 Q19.5 17.5 17.5 17.5 L6.5 17.5 Q4.5 17.5 3.69 15.67 Z\"/><path d=\"M8.5 8.5 L 8.5 13\"/><path d=\"M12.5 8.5 L 12.5 13\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Ferry({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
