// iconaut-react — file-pen (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5.5 5.5 Q5.5 3.5 7.5 3.5 L11.3 3.5 Q13.3 3.5 14.71 4.91 L17.09 7.29 Q18.5 8.7 18.5 10.7 L18.5 18.5 Q18.5 20.5 16.5 20.5 L7.5 20.5 Q5.5 20.5 5.5 18.5 Z M14.95 5.15L18.5 8.7L13.3 8.7L13.3 5.84A0.97 0.97 0 0 1 14.95 5.15Z M15.05 13.42L15.2 13.57A0.97 0.97 0 0 1 15.2 14.95L11.17 18.98L9.64 18.98L9.64 18.14A1.66 1.66 0 0 1 10.13 16.96L13.67 13.42A0.97 0.97 0 0 1 15.05 13.42Z\"/><g class=\"primary\"><path d=\"M5.5 5.5 Q5.5 3.5 7.5 3.5 L11.3 3.5 Q13.3 3.5 14.71 4.91 L17.09 7.29 Q18.5 8.7 18.5 10.7 L18.5 18.5 Q18.5 20.5 16.5 20.5 L7.5 20.5 Q5.5 20.5 5.5 18.5 Z\"/><path d=\"M13.15 3.85 L13.3 6.7  Q13.3 8.7 15.3 8.7  L17.9 8.7\"/><path d=\"M13.6 13.5 Q14.36 12.73 15.13 13.5 L15.13 13.5 Q15.89 14.26 15.13 15.03 L11.71 18.44 Q11.17 18.98 10.41 18.98 L10.41 18.98 Q9.64 18.98 9.64 18.22 L9.64 18.22 Q9.64 17.45 10.18 16.91 Z\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z M15.18 4.78L19 8.6L13.4 8.6L13.4 5.52A1.04 1.04 0 0 1 15.18 4.78Z M15.05 13.42L15.2 13.57A0.97 0.97 0 0 1 15.2 14.95L11.17 18.98L9.64 18.98L9.64 18.14A1.66 1.66 0 0 1 10.13 16.96L13.67 13.42A0.97 0.97 0 0 1 15.05 13.42Z\"/><g class=\"primary\"><path d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z\"/><path d=\"M13.25 3.35 L13.4 6.6  Q13.4 8.6 15.4 8.6  L18.4 8.6\"/><path d=\"M13.6 13.5 Q14.36 12.73 15.13 13.5 L15.13 13.5 Q15.89 14.26 15.13 15.03 L11.71 18.44 Q11.17 18.98 10.41 18.98 L10.41 18.98 Q9.64 18.98 9.64 18.22 L9.64 18.22 Q9.64 17.45 10.18 16.91 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function FilePenDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
