// iconaut-react — file-star (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 5.5 Q5.5 3.5 7.5 3.5 L11.3 3.5 Q13.3 3.5 14.71 4.91 L17.09 7.29 Q18.5 8.7 18.5 10.7 L18.5 18.5 Q18.5 20.5 16.5 20.5 L7.5 20.5 Q5.5 20.5 5.5 18.5 Z\"/><path d=\"M13.15 3.85 L13.3 6.7  Q13.3 8.7 15.3 8.7  L17.9 8.7\"/><path d=\"M11.58 12.71 Q12 11.8 12.43 12.71 L12.43 12.71 Q12.85 13.61 13.84 13.73 L13.84 13.73 Q14.83 13.85 14.1 14.53 L14.1 14.53 Q13.37 15.21 13.56 16.19 L13.56 16.19 Q13.75 17.17 12.88 16.69 L12.88 16.69 Q12 16.21 11.13 16.69 L11.13 16.69 Q10.25 17.17 10.44 16.19 L10.44 16.19 Q10.63 15.21 9.9 14.53 L9.9 14.53 Q9.17 13.85 10.16 13.73 L10.16 13.73 Q11.15 13.61 11.57 12.71 Z\"/>";
const M1 = "<path d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z\"/><path d=\"M13.25 3.35 L13.4 6.6  Q13.4 8.6 15.4 8.6  L18.4 8.6\"/><path d=\"M11.59 13.08 Q12 12.2 12.41 13.08 L12.41 13.08 Q12.82 13.95 13.78 14.07 L13.79 14.07 Q14.74 14.19 14.04 14.85 L14.04 14.85 Q13.33 15.5 13.51 16.45 L13.51 16.45 Q13.69 17.4 12.85 16.93 L12.85 16.93 Q12 16.47 11.16 16.93 L11.16 16.93 Q10.31 17.4 10.49 16.45 L10.49 16.45 Q10.67 15.5 9.97 14.85 L9.97 14.85 Q9.26 14.19 10.21 14.07 L10.22 14.07 Q11.18 13.95 11.59 13.08 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FileStar({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
