// iconaut-react — file-pdf (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z M11.15 12.6H11.4A1.9 1.9 0 0 1 11.4 16.4H11.15Z\"/><g class=\"primary\"><path d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z\"/><path d=\"M13.25 3.35 L13.4 6.6  Q13.4 8.6 15.4 8.6  L18.4 8.6\"/><path d=\"M6.8 16.4 L6.8 13.1 Q6.8 12.6 7.3 12.6 L7.8 12.6 A1.03 1.03 0 0 1 7.8 14.66 L6.8 14.66\"/><path d=\"M11.28 12.6 L11.4 12.6 A1.9 1.9 0 0 1 11.4 16.4 L11.28 16.4 Q11.15 16.4 11.15 16.27 L11.15 12.73 Q11.15 12.6 11.28 12.6 Z\"/><path d=\"M17.05 12.6 L16.33 12.6 Q15.6 12.6 15.6 13.33 L15.6 16.4 M15.6 14.3 L 16.95 14.3\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function FilePdfDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
