// iconaut-react — file-user (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 5.5 Q5.5 3.5 7.5 3.5 L11.3 3.5 Q13.3 3.5 14.71 4.91 L17.09 7.29 Q18.5 8.7 18.5 10.7 L18.5 18.5 Q18.5 20.5 16.5 20.5 L7.5 20.5 Q5.5 20.5 5.5 18.5 Z\"/><path d=\"M13.15 3.85 L13.3 6.7  Q13.3 8.7 15.3 8.7  L17.9 8.7\"/><path d=\"M10.3 14 A1.7 1.7 0 1 0 13.7 14 A1.7 1.7 0 1 0 10.3 14 Z\"/><path d=\"M9.3 18.2 A2.7 2.7 0 0 1 14.7 18.2\"/>";
const M1 = "<path d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z\"/><path d=\"M13.25 3.35 L13.4 6.6  Q13.4 8.6 15.4 8.6  L18.4 8.6\"/><path d=\"M10.5 13.7 A1.5 1.5 0 1 0 13.5 13.7 A1.5 1.5 0 1 0 10.5 13.7 Z\"/><path d=\"M9.62 17.4 A2.38 2.38 0 0 1 14.38 17.4\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FileUser({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
