// iconaut-react — file-code (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 5.5 Q5.5 3.5 7.5 3.5 L11.3 3.5 Q13.3 3.5 14.71 4.91 L17.09 7.29 Q18.5 8.7 18.5 10.7 L18.5 18.5 Q18.5 20.5 16.5 20.5 L7.5 20.5 Q5.5 20.5 5.5 18.5 Z\"/><path d=\"M13.15 3.85 L13.3 6.7  Q13.3 8.7 15.3 8.7  L17.9 8.7\"/><path d=\"M10.66 12.71 L9.77 13.61 Q8.88 14.5 9.77 15.4 L10.66 16.29\"/><path d=\"M13.34 12.71 L14.24 13.61 Q15.13 14.5 14.24 15.4 L13.34 16.29\"/>";
const M1 = "<path d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z\"/><path d=\"M13.25 3.35 L13.4 6.6  Q13.4 8.6 15.4 8.6  L18.4 8.6\"/><path d=\"M10.46 12.44 L9.43 13.47 Q8.4 14.5 9.43 15.53 L10.46 16.56\"/><path d=\"M13.54 12.44 L14.57 13.47 Q15.6 14.5 14.57 15.53 L13.54 16.56\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function FileCode({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
