// iconaut-react — file-image (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 5.5 Q5.5 3.5 7.5 3.5 L11.3 3.5 Q13.3 3.5 14.71 4.91 L17.09 7.29 Q18.5 8.7 18.5 10.7 L18.5 18.5 Q18.5 20.5 16.5 20.5 L7.5 20.5 Q5.5 20.5 5.5 18.5 Z\"/><path d=\"M13.15 3.85 L13.3 6.7  Q13.3 8.7 15.3 8.7  L17.9 8.7\"/><path d=\"M8.6 12.8 A1 1 0 1 0 10.6 12.8 A1 1 0 1 0 8.6 12.8 Z\"/><path d=\"M8 17 L9.52 15.22 Q10.3 14.3 11.15 15.15 L11.15 15.15 Q12 16 12.72 15.03 L13 14.65 Q14 13.3 14.8 14.78 L16 17\"/>";
const M1 = "<path d=\"M5 5 Q5 3 7 3 L11.4 3 Q13.4 3 14.81 4.41 L17.59 7.19 Q19 8.6 19 10.6 L19 19 Q19 21 17 21 L7 21 Q5 21 5 19 Z\"/><path d=\"M13.25 3.35 L13.4 6.6  Q13.4 8.6 15.4 8.6  L18.4 8.6\"/><path d=\"M9.11 13.05 A0.85 0.85 0 1 0 10.81 13.05 A0.85 0.85 0 1 0 9.11 13.05 Z\"/><path d=\"M8.6 16.62 L9.9 15.1 Q10.56 14.33 11.28 15.05 L11.28 15.05 Q12 15.77 12.61 14.95 L12.85 14.63 Q13.7 13.48 14.38 14.73 L15.4 16.62\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FileImage({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
