// iconaut-react — filter (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.31 7.01 Q4 5.5 6 5.5 L18 5.5 Q20 5.5 18.69 7.01 L14.81 11.49 Q13.5 13 13.5 15 L13.5 17.2 Q13.5 19 12 18 L12 18 Q10.5 17 10.5 15.2 L10.5 15 Q10.5 13 9.19 11.49 Z\"/>";
const M1 = "<path d=\"M4.76 6.55 Q3.5 5 5.5 5 L18.5 5 Q20.5 5 19.24 6.55 L15.26 11.45 Q14 13 14 15 L14 17.5 Q14 19.5 12.21 18.61 L11.79 18.39 Q10 17.5 10 15.5 L10 15 Q10 13 8.74 11.45 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Filter({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
