// iconaut-react — fire-truck (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4 16 A2 2 0 1 0 8 16 A2 2 0 1 0 4 16 Z\"/><path d=\"M14.5 16 A2 2 0 1 0 18.5 16 A2 2 0 1 0 14.5 16 Z\"/><path d=\"M2 14 L2 10 Q2 8 4 8 L11 8 Q13 8 13 10 L13 14\"/><path d=\"M13 14 L13 12 Q13 10 15 10 L16 10 Q18 10 19.41 11.41 L20.65 12.65 Q21 13 21 13.5 L21 14\"/><path d=\"M2 14 L 21 14\"/><path d=\"M4 8 L4 6.75 Q4 5.5 5.25 5.5 L10.75 5.5 Q12 5.5 12 6.75 L12 8\"/><path d=\"M6.5 5.5 L 6.5 8\"/><path d=\"M9.5 5.5 L 9.5 8\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function FireTruck({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
