// iconaut-react — first-aid (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3.4 9.1 Q3.4 7.1 5.4 7.1 L18.6 7.1 Q20.6 7.1 20.6 9.1 L20.6 16.9 Q20.6 18.9 18.6 18.9 L5.4 18.9 Q3.4 18.9 3.4 16.9 Z M11.93 9.45L12.08 9.45A0.68 0.68 0 0 1 12.75 10.13L12.75 16.55L11.25 16.55L11.25 10.13A0.68 0.68 0 0 1 11.93 9.45Z M9.13 12.25L14.88 12.25A0.68 0.68 0 0 1 15.55 12.93L15.55 13.75L8.45 13.75L8.45 12.93A0.68 0.68 0 0 1 9.13 12.25Z\"/><g class=\"primary\"><path d=\"M3.4 9.1 Q3.4 7.1 5.4 7.1 L18.6 7.1 Q20.6 7.1 20.6 9.1 L20.6 16.9 Q20.6 18.9 18.6 18.9 L5.4 18.9 Q3.4 18.9 3.4 16.9 Z\"/><path d=\"M9.3 7.1 L9.3 5.4 A1.3 1.3 0 0 1 10.6 4.1 L13.4 4.1 A1.3 1.3 0 0 1 14.7 5.4 L14.7 7.1\"/><path d=\"M12 10.2 L 12 15.8 M9.2 13 L 14.8 13\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function FirstAidDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
