// iconaut-react — folder-pen (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 7.5 Q3 5.5 5 5.5 L7.38 5.5 Q8.8 5.5 9.7 6.6 L9.7 6.6 Q10.6 7.7 12.02 7.7 L19 7.7 Q21 7.7 21 9.7 L21 18.5 Q21 20.5 19 20.5 L5 20.5 Q3 20.5 3 18.5 Z M13.9 12.06L14.03 12.19A0.83 0.83 0 0 1 14.02 13.37L10.7 16.69L9.39 16.69L9.39 15.98A1.41 1.41 0 0 1 9.8 14.98L12.72 12.06A0.83 0.83 0 0 1 13.9 12.06Z\"/><g class=\"primary\"><path d=\"M3 7.5 Q3 5.5 5 5.5 L7.38 5.5 Q8.8 5.5 9.7 6.6 L9.7 6.6 Q10.6 7.7 12.02 7.7 L19 7.7 Q21 7.7 21 9.7 L21 18.5 Q21 20.5 19 20.5 L5 20.5 Q3 20.5 3 18.5 Z\"/><path d=\"M12.66 12.12 Q13.31 11.47 13.96 12.13 L13.96 12.13 Q14.61 12.78 13.96 13.43 L11.16 16.23 Q10.7 16.69 10.05 16.69 L10.04 16.69 Q9.39 16.69 9.39 16.04 L9.39 16.04 Q9.39 15.39 9.85 14.93 Z\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M2.5 7 Q2.5 5 4.5 5 L7.4 5 Q9 5 10 6.25 L10 6.25 Q11 7.5 12.6 7.5 L19.5 7.5 Q21.5 7.5 21.5 9.5 L21.5 19 Q21.5 21 19.5 21 L4.5 21 Q2.5 21 2.5 19 Z M14.18 11.8L14.33 11.94A0.95 0.95 0 0 1 14.33 13.3L10.5 17.12L9 17.12L9 16.3A1.63 1.63 0 0 1 9.48 15.14L12.83 11.8A0.95 0.95 0 0 1 14.18 11.8Z\"/><g class=\"primary\"><path d=\"M2.5 7 Q2.5 5 4.5 5 L7.4 5 Q9 5 10 6.25 L10 6.25 Q11 7.5 12.6 7.5 L19.5 7.5 Q21.5 7.5 21.5 9.5 L21.5 19 Q21.5 21 19.5 21 L4.5 21 Q2.5 21 2.5 19 Z\"/><path d=\"M12.75 11.87 Q13.5 11.12 14.25 11.87 L14.25 11.87 Q15 12.62 14.25 13.37 L11.03 16.59 Q10.5 17.12 9.75 17.12 L9.75 17.12 Q9 17.12 9 16.37 L9 16.37 Q9 15.62 9.53 15.09 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FolderPenDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
