// iconaut-react — folder-git (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 7.5 Q3 5.5 5 5.5 L7.38 5.5 Q8.8 5.5 9.7 6.6 L9.7 6.6 Q10.6 7.7 12.02 7.7 L19 7.7 Q21 7.7 21 9.7 L21 18.5 Q21 20.5 19 20.5 L5 20.5 Q3 20.5 3 18.5 Z M6.1 11.74A1.12 1.12 0 1 0 8.34 11.74A1.12 1.12 0 1 0 6.1 11.74Z M6.1 15.61A1.12 1.12 0 1 0 8.34 15.61A1.12 1.12 0 1 0 6.1 15.61Z M11.26 12.6A1.12 1.12 0 1 0 13.5 12.6A1.12 1.12 0 1 0 11.26 12.6Z\"/><g class=\"primary\"><path d=\"M3 7.5 Q3 5.5 5 5.5 L7.38 5.5 Q8.8 5.5 9.7 6.6 L9.7 6.6 Q10.6 7.7 12.02 7.7 L19 7.7 Q21 7.7 21 9.7 L21 18.5 Q21 20.5 19 20.5 L5 20.5 Q3 20.5 3 18.5 Z\"/><path d=\"M6.1 11.74 A1.12 1.12 0 1 0 8.34 11.74 A1.12 1.12 0 1 0 6.1 11.74 Z\"/><path d=\"M6.1 15.61 A1.12 1.12 0 1 0 8.34 15.61 A1.12 1.12 0 1 0 6.1 15.61 Z\"/><path d=\"M11.26 12.6 A1.12 1.12 0 1 0 13.5 12.6 A1.12 1.12 0 1 0 11.26 12.6 Z\"/><path d=\"M7.22 12.86 L 7.22 14.49\"/><path d=\"M7.22 12.86 A4.3 4.3 0 0 0 11.35 13.29\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M2.5 7 Q2.5 5 4.5 5 L7.4 5 Q9 5 10 6.25 L10 6.25 Q11 7.5 12.6 7.5 L19.5 7.5 Q21.5 7.5 21.5 9.5 L21.5 19 Q21.5 21 19.5 21 L4.5 21 Q2.5 21 2.5 19 Z M6.42 11.58A1.3 1.3 0 1 0 9.02 11.58A1.3 1.3 0 1 0 6.42 11.58Z M6.42 16.08A1.3 1.3 0 1 0 9.02 16.08A1.3 1.3 0 1 0 6.42 16.08Z M12.42 12.58A1.3 1.3 0 1 0 15.02 12.58A1.3 1.3 0 1 0 12.42 12.58Z\"/><g class=\"primary\"><path d=\"M2.5 7 Q2.5 5 4.5 5 L7.4 5 Q9 5 10 6.25 L10 6.25 Q11 7.5 12.6 7.5 L19.5 7.5 Q21.5 7.5 21.5 9.5 L21.5 19 Q21.5 21 19.5 21 L4.5 21 Q2.5 21 2.5 19 Z\"/><path d=\"M6.42 11.58 A1.3 1.3 0 1 0 9.02 11.58 A1.3 1.3 0 1 0 6.42 11.58 Z\"/><path d=\"M6.42 16.08 A1.3 1.3 0 1 0 9.02 16.08 A1.3 1.3 0 1 0 6.42 16.08 Z\"/><path d=\"M12.42 12.58 A1.3 1.3 0 1 0 15.02 12.58 A1.3 1.3 0 1 0 12.42 12.58 Z\"/><path d=\"M7.72 12.88 L 7.72 14.78\"/><path d=\"M7.72 12.88 A5 5 0 0 0 12.52 13.38\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FolderGitDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
