// iconaut-react — folder-star (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 7.5 Q3 5.5 5 5.5 L7.38 5.5 Q8.8 5.5 9.7 6.6 L9.7 6.6 Q10.6 7.7 12.02 7.7 L19 7.7 Q21 7.7 21 9.7 L21 18.5 Q21 20.5 19 20.5 L5 20.5 Q3 20.5 3 18.5 Z\"/><path d=\"M11.55 12.09 Q12 11.12 12.45 12.09 L12.45 12.09 Q12.9 13.05 13.96 13.18 L13.96 13.18 Q15.01 13.31 14.24 14.04 L14.24 14.04 Q13.46 14.76 13.66 15.8 L13.66 15.81 Q13.86 16.85 12.93 16.34 L12.93 16.34 Q12 15.82 11.07 16.34 L11.07 16.34 Q10.14 16.85 10.34 15.81 L10.34 15.8 Q10.54 14.76 9.77 14.04 L9.77 14.04 Q8.99 13.31 10.04 13.18 L10.05 13.18 Q11.1 13.05 11.55 12.09 Z\"/>";
const M1 = "<path d=\"M2.5 7 Q2.5 5 4.5 5 L7.4 5 Q9 5 10 6.25 L10 6.25 Q11 7.5 12.6 7.5 L19.5 7.5 Q21.5 7.5 21.5 9.5 L21.5 19 Q21.5 21 19.5 21 L4.5 21 Q2.5 21 2.5 19 Z\"/><path d=\"M11.53 12.01 Q12 11 12.47 12.01 L12.47 12.01 Q12.94 13.01 14.04 13.15 L14.04 13.15 Q15.14 13.28 14.33 14.04 L14.33 14.04 Q13.52 14.79 13.73 15.88 L13.73 15.88 Q13.94 16.97 12.97 16.43 L12.97 16.43 Q12 15.9 11.03 16.43 L11.03 16.43 Q10.06 16.97 10.27 15.88 L10.27 15.88 Q10.48 14.79 9.67 14.04 L9.67 14.04 Q8.86 13.28 9.96 13.15 L9.96 13.15 Q11.06 13.01 11.53 12.01 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function FolderStar({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
