// iconaut-react — folder-symlink (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 7.5 Q3 5.5 5 5.5 L7.38 5.5 Q8.8 5.5 9.7 6.6 L9.7 6.6 Q10.6 7.7 12.02 7.7 L19 7.7 Q21 7.7 21 9.7 L21 18.5 Q21 20.5 19 20.5 L5 20.5 Q3 20.5 3 18.5 Z\"/><path d=\"M9.39 16.69 L9.39 14.52 A1.31 1.31 0 0 1 10.7 13.21 L14.61 13.21\"/><path d=\"M12.87 11.47 L13.74 12.34 Q14.61 13.21 13.74 14.08 L12.87 14.95\"/>";
const M1 = "<path d=\"M2.5 7 Q2.5 5 4.5 5 L7.4 5 Q9 5 10 6.25 L10 6.25 Q11 7.5 12.6 7.5 L19.5 7.5 Q21.5 7.5 21.5 9.5 L21.5 19 Q21.5 21 19.5 21 L4.5 21 Q2.5 21 2.5 19 Z\"/><path d=\"M9 17.12 L9 14.62 A1.5 1.5 0 0 1 10.5 13.12 L15 13.12\"/><path d=\"M13 11.12 L14 12.12 Q15 13.12 14 14.12 L13 15.12\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FolderSymlink({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
