// iconaut-react — folder-heart (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 7.5 Q3 5.5 5 5.5 L7.38 5.5 Q8.8 5.5 9.7 6.6 L9.7 6.6 Q10.6 7.7 12.02 7.7 L19 7.7 Q21 7.7 21 9.7 L21 18.5 Q21 20.5 19 20.5 L5 20.5 Q3 20.5 3 18.5 Z\"/><path d=\"M12 16.68 C11.59 16.41 9.21 14.91 9.21 12.96 A1.58 1.58 0 0 1 12 12.04 A1.58 1.58 0 0 1 14.79 12.96 C14.79 14.91 12.42 16.41 12 16.68 Z\"/>";
const M1 = "<path d=\"M2.5 7 Q2.5 5 4.5 5 L7.4 5 Q9 5 10 6.25 L10 6.25 Q11 7.5 12.6 7.5 L19.5 7.5 Q21.5 7.5 21.5 9.5 L21.5 19 Q21.5 21 19.5 21 L4.5 21 Q2.5 21 2.5 19 Z\"/><path d=\"M12 16.87 C11.54 16.57 8.93 14.92 8.93 12.78 A1.73 1.73 0 0 1 12 11.77 A1.73 1.73 0 0 1 15.07 12.78 C15.07 14.92 12.47 16.57 12 16.87 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FolderHeart({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
