// iconaut-react — freight-car (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M2.5 7.5 Q2.5 5.5 4.5 5.5 L19.5 5.5 Q21.5 5.5 21.5 7.5 L21.5 13 Q21.5 15 19.5 15 L4.5 15 Q2.5 15 2.5 13 Z\"/><path d=\"M4.5 17 A2 2 0 1 0 8.5 17 A2 2 0 1 0 4.5 17 Z\"/><path d=\"M15.5 17 A2 2 0 1 0 19.5 17 A2 2 0 1 0 15.5 17 Z\"/><path d=\"M2.5 19 L 21.5 19\"/><path d=\"M8.4 5.5 L 8.4 15\"/><path d=\"M15.6 5.5 L 15.6 15\"/>";
const M1 = "<path d=\"M2.5 7.5 Q2.5 5.5 4.5 5.5 L19.5 5.5 Q21.5 5.5 21.5 7.5 L21.5 13 Q21.5 15 19.5 15 L4.5 15 Q2.5 15 2.5 13 Z\"/><path d=\"M4.5 17 A2 2 0 1 0 8.5 17 A2 2 0 1 0 4.5 17 Z\"/><path d=\"M15.5 17 A2 2 0 1 0 19.5 17 A2 2 0 1 0 15.5 17 Z\"/><path d=\"M2.5 19 L 21.5 19\"/><path d=\"M8.4 5.5 L 8.4 15\"/><path d=\"M12 5.5 L 12 15\"/><path d=\"M15.6 5.5 L 15.6 15\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function FreightCar({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
