// iconaut-react — frog (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.5 13 C4.5 10.5 6.5 8.5 9 7.6 A2.4 2.4 0 0 1 5.6 7 C6 6.7 6.4 6.5 6.8 6.4 A2.4 2.4 0 1 1 10.3 6.7 C10.9 6.6 11.4 6.5 12 6.5 C12.6 6.5 13.2 6.6 13.7 6.7 A2.4 2.4 0 1 1 17.2 6.4 C17.6 6.5 18 6.7 18.4 7 A2.4 2.4 0 0 1 15 7.6 C17.5 8.5 19.5 10.5 19.5 13 C19.5 16.5 16.5 18.5 12 18.5 C7.5 18.5 4.5 16.5 4.5 13 Z\"/><path d=\"M9 13.5 C10 14.5 14 14.5 15 13.5\"/><path d=\"M8 6.6 L 8.01 6.6\"/><path d=\"M16 6.6 L 16.01 6.6\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function Frog({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
