// iconaut-react — gas-pump (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.5 5.5 Q4.5 3.5 6.5 3.5 L10.5 3.5 Q12.5 3.5 12.5 5.5 L12.5 18.5 Q12.5 20.5 10.5 20.5 L6.5 20.5 Q4.5 20.5 4.5 18.5 Z\"/><path d=\"M4.5 9.5 L 12.5 9.5\"/><path d=\"M3.5 20.5 L 13.5 20.5\"/><path d=\"M12.5 13.25 L14.75 13.25 A1.5 1.5 0 0 1 16.25 14.75 L16.25 17.25 A1.5 1.5 0 0 0 19.25 17.25 L19.25 10.91 Q19.25 9.5 18.25 8.5 L17.25 7.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function GasPump({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
