// iconaut-react — gift (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4.5 10 Q4.5 8 6.5 8 L17.5 8 Q19.5 8 19.5 10 L19.5 17.5 Q19.5 19.5 17.5 19.5 L6.5 19.5 Q4.5 19.5 4.5 17.5 Z M5.8 7.5L18.2 7.5A1.8 1.8 0 0 1 20 9.3L20 11.5L4 11.5L4 9.3A1.8 1.8 0 0 1 5.8 7.5Z\"/><g class=\"primary\"><path d=\"M4.5 10 Q4.5 8 6.5 8 L17.5 8 Q19.5 8 19.5 10 L19.5 17.5 Q19.5 19.5 17.5 19.5 L6.5 19.5 Q4.5 19.5 4.5 17.5 Z\"/><path d=\"M4.5 11.7 L 19.5 11.7\"/><path d=\"M12 8 L 12 19.5\"/><path d=\"M8 8 A2.1 2.1 0 0 1 8 3.7 A4.2 7 0 0 1 12 8 A4.2 7 0 0 1 16 3.7 A2.1 2.1 0 0 1 16 8\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 9.5 Q4 7.5 6 7.5 L18 7.5 Q20 7.5 20 9.5 L20 18 Q20 20 18 20 L6 20 Q4 20 4 18 Z M5.8 7.5L18.2 7.5A1.8 1.8 0 0 1 20 9.3L20 11.5L4 11.5L4 9.3A1.8 1.8 0 0 1 5.8 7.5Z\"/><g class=\"primary\"><path d=\"M4 9.5 Q4 7.5 6 7.5 L18 7.5 Q20 7.5 20 9.5 L20 18 Q20 20 18 20 L6 20 Q4 20 4 18 Z\"/><path d=\"M4 11.5 L 20 11.5\"/><path d=\"M12 7.5 L 12 20\"/><path d=\"M7.6 7.5 A2.3 2.3 0 0 1 7.6 3 A4.5 7.5 0 0 1 12 7.5 A4.5 7.5 0 0 1 16.4 3 A2.3 2.3 0 0 1 16.4 7.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function GiftDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
