// iconaut-react — git-branch (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.25 17.25 A2.25 2.25 0 1 0 8.75 17.25 A2.25 2.25 0 1 0 4.25 17.25 Z\"/><path d=\"M15.25 6.25 A2.25 2.25 0 1 0 19.75 6.25 A2.25 2.25 0 1 0 15.25 6.25 Z\"/><path d=\"M6.5 4.5 L 6.5 15\"/><path d=\"M17.5 8.5 A8.75 8.75 0 0 1 8.75 17.25\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function GitBranch({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
