// iconaut-react — globe-arrow (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3.5 14.25 A6.25 6.25 0 1 0 16 14.25 A6.25 6.25 0 1 0 3.5 14.25 Z\"/><path d=\"M3.5 14.25 L 16 14.25\"/><path d=\"M9.75 8 A2.25 6.25 0 0 0 9.75 20.5 M9.75 8 A2.25 6.25 0 0 1 9.75 20.5\"/><path d=\"M17 7 L 20.5 3.5\"/><path d=\"M17 3.5 L18.75 3.5 Q20.5 3.5 20.5 5.25 L20.5 7\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function GlobeArrow({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
