// iconaut-react — goal (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5 19.5 L5 6.5 Q5 5.5 6 5.5 L18 5.5 Q19 5.5 19 6.5 L19 19.5\"/><path d=\"M9.67 5.5 L 9.67 19.5 M14.33 5.5 L 14.33 19.5\"/><path d=\"M5 12.5 L 19 12.5\"/><path d=\"M3 19.5 L 21 19.5\"/>";
const M1 = "<path d=\"M5 19.5 L5 6.5 Q5 5.5 6 5.5 L18 5.5 Q19 5.5 19 6.5 L19 19.5\"/><path d=\"M9.67 5.5 L 9.67 19.5 M14.33 5.5 L 14.33 19.5\"/><path d=\"M5 10.17 L 19 10.17 M5 14.83 L 19 14.83\"/><path d=\"M3 19.5 L 21 19.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Goal({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
