// iconaut-react — grapevine (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6.2 10.2 A1.9 1.9 0 1 0 10 10.2 A1.9 1.9 0 1 0 6.2 10.2 Z\"/><path d=\"M10.1 10.2 A1.9 1.9 0 1 0 13.9 10.2 A1.9 1.9 0 1 0 10.1 10.2 Z\"/><path d=\"M14 10.2 A1.9 1.9 0 1 0 17.8 10.2 A1.9 1.9 0 1 0 14 10.2 Z\"/><path d=\"M8.15 13.6 A1.9 1.9 0 1 0 11.95 13.6 A1.9 1.9 0 1 0 8.15 13.6 Z\"/><path d=\"M12.05 13.6 A1.9 1.9 0 1 0 15.85 13.6 A1.9 1.9 0 1 0 12.05 13.6 Z\"/><path d=\"M10.1 17 A1.9 1.9 0 1 0 13.9 17 A1.9 1.9 0 1 0 10.1 17 Z\"/><path d=\"M12 8.3 L 12 3.8\"/><path d=\"M12 4.6 C13.4 2.8 16 2.8 17.6 4.4 C16 6 13.4 6.1 12 4.6 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Grapevine({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
