// iconaut-react — hammer (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12.48 8.73 Q11.07 7.31 12.48 5.9 L12.82 5.56 Q14.23 4.15 15.65 5.56 L18.76 8.68 Q20.18 10.09 18.77 11.5 L18.42 11.85 Q17.01 13.26 15.6 11.84 Z\"/><g class=\"primary\"><path d=\"M11.78 8.02 Q11.07 7.31 11.78 6.6 L13.52 4.86 Q14.23 4.15 14.94 4.86 L19.47 9.38 Q20.18 10.09 19.47 10.8 L17.72 12.55 Q17.01 13.26 16.3 12.55 Z\"/><path d=\"M3.82 20.5 L 14.04 10.28\"/><path d=\"M12.65 5.73 Q9.77 2.29 5.69 4.15\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function HammerDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
