// iconaut-react — headphones-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.5 14L4.5 12.5A7.5 7.5 0 0 1 5.09 9.59M6.95 6.95A7.5 7.5 0 0 1 19.5 12.5L19.5 14\"/><path d=\"M5.5 14L5.8 14Q6.8 14 6.8 15L6.8 18.3Q6.8 19 6.1 19L5.4 19A0.9 0.9 0 0 1 4.5 18.1L4.5 15Q4.5 14 5.5 14Z\"/><path d=\"M18.94 18.94A0.9 0.9 0 0 0 19.5 18.1L19.5 15Q19.5 14 18.5 14L18.2 14Q17.2 14 17.2 15L17.2 17.2\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M4 14L4 12A8 8 0 0 1 4.56 9.06M6.34 6.34A8 8 0 0 1 20 12L20 14\"/><path d=\"M5 14L5.5 14Q6.5 14 6.5 15L6.5 18.75Q6.5 19.5 5.75 19.5L5 19.5A1 1 0 0 1 4 18.5L4 15Q4 14 5 14Z\"/><path d=\"M19.41 19.41A1 1 0 0 0 20 18.5L20 15Q20 14 19 14L18.5 14Q17.5 14 17.5 15L17.5 17.5\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M2 = "<path d=\"M4 14L4 12A8 8 0 0 1 4.55 9.08M6.34 6.34A8 8 0 0 1 20 12L20 14\"/><path d=\"M5 14L5.5 14Q6.5 14 6.5 15L6.5 18.75Q6.5 19.5 5.75 19.5L5 19.5A1 1 0 0 1 4 18.5L4 15Q4 14 5 14Z\"/><path d=\"M19.41 19.41A1 1 0 0 0 20 18.5L20 15Q20 14 19 14L18.5 14Q17.5 14 17.5 15L17.5 17.5\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M2, 1.7]
};
const S = [16, 20, 24];

export default function HeadphonesOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
