// iconaut-react — heart-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.78 5.78A4.6 4.6 0 0 1 12 6.7A4.6 4.6 0 0 1 20.2 9.4C20.2 12.22 18.5 14.72 16.63 16.63M13.98 18.93C13.07 19.62 12.33 20.09 12 20.3C10.77 19.52 3.8 15.1 3.8 9.4A4.6 4.6 0 0 1 3.86 8.81\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M5.78 5.78A4.6 4.6 0 0 1 12 6.7A4.6 4.6 0 0 1 20.2 9.4C20.2 12.22 18.5 14.72 16.63 16.63M14.23 18.74C13.21 19.53 12.36 20.07 12 20.3C10.77 19.52 3.8 15.1 3.8 9.4A4.6 4.6 0 0 1 3.93 8.44\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M2 = "<path d=\"M5.24 5.24A4.8 4.8 0 0 1 12 6.3A4.8 4.8 0 0 1 20.7 9.1C20.7 12.08 18.81 14.75 16.77 16.77M14.36 18.86C13.28 19.69 12.38 20.26 12 20.5C10.69 19.67 3.3 15 3.3 9.1A4.8 4.8 0 0 1 3.44 7.94\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M3 = "<path d=\"M5.24 5.24A4.8 4.8 0 0 1 12 6.3A4.8 4.8 0 0 1 20.7 9.1C20.7 12.08 18.81 14.75 16.77 16.77M14.35 18.87C13.27 19.7 12.38 20.26 12 20.5C10.69 19.67 3.3 15 3.3 9.1A4.8 4.8 0 0 1 3.44 7.96\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M1, 1.688],
  20: [M2, 1.68],
  24: [M3, 1.7]
};
const S = [12, 16, 20, 24];

export default function HeartOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
