// iconaut-react — highlighter (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M9 12 L 12 15\"/><path d=\"M13.29 5.71 Q14 5 14.71 5.71 L16.79 7.79 Q17.5 8.5 16.79 9.21 L10.71 15.29 Q10 16 9 16 L7.5 16 Q6.5 16 6.5 15 L6.5 13.5 Q6.5 12.5 7.21 11.79 Z\"/><path d=\"M4 20 L 10 20\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Highlighter({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
