// iconaut-react — home (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M4.82 8.71L10 4.37A3.11 3.11 0 0 1 14 4.37L19.18 8.71A5.08 5.08 0 0 1 21 12.6L21 18.79A2.71 2.71 0 0 1 18.29 21.5L5.71 21.5A2.71 2.71 0 0 1 3 18.79L3 12.6A5.08 5.08 0 0 1 4.82 8.71Z M9.5 21.5L9.5 16.5A2 2 0 0 1 11.5 14.5L12.5 14.5A2 2 0 0 1 14.5 16.5L14.5 21.5L9.5 21.5Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M4.92 8.83L10.1 4.49A2.95 2.95 0 0 1 13.9 4.49L19.08 8.83A4.93 4.93 0 0 1 20.84 12.61L20.84 18.79A2.55 2.55 0 0 1 18.29 21.34L5.71 21.34A2.55 2.55 0 0 1 3.16 18.79L3.16 12.61A4.93 4.93 0 0 1 4.92 8.83Z M9.5 21.34L9.5 16.5A2 2 0 0 1 11.5 14.5L12.5 14.5A2 2 0 0 1 14.5 16.5L14.5 21.34L9.5 21.34Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M4.45 8.55L10.09 3.97A3.03 3.03 0 0 1 13.91 3.97L19.55 8.55A4.83 4.83 0 0 1 21.34 12.3L21.34 18.79A2.55 2.55 0 0 1 18.79 21.34L5.21 21.34A2.55 2.55 0 0 1 2.66 18.79L2.66 12.3A4.83 4.83 0 0 1 4.45 8.55Z M9.5 21.34L9.5 16.5A2 2 0 0 1 11.5 14.5L12.5 14.5A2 2 0 0 1 14.5 16.5L14.5 21.34L9.5 21.34Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M4.44 8.55L10.09 3.96A3.04 3.04 0 0 1 13.91 3.96L19.56 8.55A4.85 4.85 0 0 1 21.35 12.31L21.35 18.79A2.56 2.56 0 0 1 18.79 21.35L5.21 21.35A2.56 2.56 0 0 1 2.65 18.79L2.65 12.31A4.85 4.85 0 0 1 4.44 8.55Z M9.5 21.35L9.5 16.5A2 2 0 0 1 11.5 14.5L12.5 14.5A2 2 0 0 1 14.5 16.5L14.5 21.35L9.5 21.35Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function HomeSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
