// iconaut-react — hospital (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 20.5 Q3.5 20.5 3.5 18.5 L3.5 12.5 Q3.5 10.5 5.5 10.5 L6 10.5 Q8 10.5 8 8.5 L8 7.5 Q8 5.5 10 5.5 L14 5.5 Q16 5.5 16 7.5 L16 8.5 Q16 10.5 18 10.5 L18.5 10.5 Q20.5 10.5 20.5 12.5 L20.5 18.5 Q20.5 20.5 18.5 20.5 Z\"/><path d=\"M12 8.75 L 12 12.25 M10.25 10.5 L 13.75 10.5\"/><path d=\"M9.5 20.5 L9.5 17.5 Q9.5 15.5 11.5 15.5 L12.5 15.5 Q14.5 15.5 14.5 17.5 L14.5 20.5\"/>";
const M1 = "<path d=\"M5.5 20.5 Q3.5 20.5 3.5 18.5 L3.5 12.5 Q3.5 10.5 5.5 10.5 L6 10.5 Q8 10.5 8 8.5 L8 7.5 Q8 5.5 10 5.5 L14 5.5 Q16 5.5 16 7.5 L16 8.5 Q16 10.5 18 10.5 L18.5 10.5 Q20.5 10.5 20.5 12.5 L20.5 18.5 Q20.5 20.5 18.5 20.5 Z\"/><path d=\"M12 8.25 L 12 12.25 M10 10.25 L 14 10.25\"/><path d=\"M9.5 20.5 L9.5 17.5 Q9.5 15.5 11.5 15.5 L12.5 15.5 Q14.5 15.5 14.5 17.5 L14.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Hospital({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
