// iconaut-react — hourglass (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7 4.5 Q7 4 7.5 4 L16.5 4 Q17 4 17 4.5 L17 4.5 Q17 5 16.75 5.43 L13.99 10.26 Q13 12 13.99 13.74 L16.75 18.57 Q17 19 17 19.5 L17 19.5 Q17 20 16.5 20 L7.5 20 Q7 20 7 19.5 L7 19.5 Q7 19 7.25 18.57 L10.01 13.74 Q11 12 10.01 10.26 L7.25 5.43 Q7 5 7 4.5 Z\"/><path d=\"M8.9 20 L10.59 18.31 Q12 16.9 13.41 18.31 L15.1 20\"/>";
const M1 = "<path d=\"M6.5 4 Q6.5 3.5 7 3.5 L17 3.5 Q17.5 3.5 17.5 4 L17.5 4 Q17.5 4.5 17.24 4.93 L14.03 10.29 Q13 12 14.03 13.71 L17.24 19.07 Q17.5 19.5 17.5 20 L17.5 20 Q17.5 20.5 17 20.5 L7 20.5 Q6.5 20.5 6.5 20 L6.5 20 Q6.5 19.5 6.76 19.07 L9.97 13.71 Q11 12 9.97 10.29 L6.76 4.93 Q6.5 4.5 6.5 4 Z\"/><path d=\"M12 13 L 12 17.2\"/><path d=\"M8.7 20.5 L10.59 18.61 Q12 17.2 13.41 18.61 L15.3 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Hourglass({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
