// iconaut-react — id-badge (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6 9 Q6 7 8 7 L16 7 Q18 7 18 9 L18 18.5 Q18 20.5 16 20.5 L8 20.5 Q6 20.5 6 18.5 Z\"/><path d=\"M10.6 7 L10.6 5.5 C10.6 4.2 11.2 3.5 12 3.5 C12.8 3.5 13.4 4.2 13.4 5.5 L13.4 7\"/><circle cx=\"12\" cy=\"11.2\" r=\"1.9\"/><path d=\"M8.2 20.5 C8.8 17.9 10.1 16.5 12 16.5 C13.9 16.5 15.2 17.9 15.8 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function IdBadge({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
