// iconaut-react — incognito (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M8.2 8.2 L8.2 7 A2.8 2.8 0 0 1 11 4.2 L13 4.2 A2.8 2.8 0 0 1 15.8 7 L15.8 8.2 Q15.8 9.4 14.6 9.4 L9.4 9.4 Q8.2 9.4 8.2 8.2 Z M4.8 16 Q4.8 14 6.8 14 L8.9 14 Q10.9 14 10.9 16 L10.9 16.2 Q10.9 18.2 8.9 18.2 L6.8 18.2 Q4.8 18.2 4.8 16.2 Z M13.1 16 Q13.1 14 15.1 14 L17.2 14 Q19.2 14 19.2 16 L19.2 16.2 Q19.2 18.2 17.2 18.2 L15.1 18.2 Q13.1 18.2 13.1 16.2 Z\"/><g class=\"primary\"><path d=\"M8.2 8.4 L8.2 7 A2.8 2.8 0 0 1 11 4.2 L13 4.2 A2.8 2.8 0 0 1 15.8 7 L15.8 8.4 Q15.8 9.4 14.8 9.4 L9.2 9.4 Q8.2 9.4 8.2 8.4 Z\"/><path d=\"M3.6 9.4 L 20.4 9.4\"/><path d=\"M4.8 15 Q4.8 14 5.8 14 L9.9 14 Q10.9 14 10.9 15 L10.9 17.2 Q10.9 18.2 9.9 18.2 L5.8 18.2 Q4.8 18.2 4.8 17.2 Z\"/><path d=\"M10.9 15.1 L 13.1 15.1\"/><path d=\"M13.1 15 Q13.1 14 14.1 14 L18.2 14 Q19.2 14 19.2 15 L19.2 17.2 Q19.2 18.2 18.2 18.2 L14.1 18.2 Q13.1 18.2 13.1 17.2 Z\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M8 8.6 L8 7.2 A3 3 0 0 1 11 4.2 L13 4.2 A3 3 0 0 1 16 7.2 L16 8.6 Q16 10 14.6 10 L9.4 10 Q8 10 8 8.6 Z M5.7 13.9 L9.8 13.9 Q10.9 13.9 10.9 15 L10.9 16.1 Q10.9 19 7.75 19 Q4.6 19 4.6 16.1 L4.6 15 Q4.6 13.9 5.7 13.9 Z M14.2 13.9 L18.3 13.9 Q19.4 13.9 19.4 15 L19.4 16.1 Q19.4 19 16.25 19 Q13.1 19 13.1 16.1 L13.1 15 Q13.1 13.9 14.2 13.9 Z\"/><g class=\"primary\"><path d=\"M8 9 L8 7.2 A3 3 0 0 1 11 4.2 L13 4.2 A3 3 0 0 1 16 7.2 L16 9 Q16 10 15 10 L9 10 Q8 10 8 9 Z\"/><path d=\"M3.4 10 L 20.6 10\"/><path d=\"M5.6 13.9 L9.9 13.9 Q10.9 13.9 10.9 14.9 L10.9 16.1 Q10.9 19 7.75 19 Q4.6 19 4.6 16.1 L4.6 14.9 Q4.6 13.9 5.6 13.9 Z\"/><path d=\"M10.9 15 L 13.1 15\"/><path d=\"M14.1 13.9 L18.4 13.9 Q19.4 13.9 19.4 14.9 L19.4 16.1 Q19.4 19 16.25 19 Q13.1 19 13.1 16.1 L13.1 14.9 Q13.1 13.9 14.1 13.9 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function IncognitoDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
