// iconaut-react — infinity (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M7.45 8.1 A3.9 3.9 0 1 0 7.45 15.9 C10.7 15.9 13.3 8.1 16.55 8.1 A3.9 3.9 0 1 1 16.55 15.9 C13.3 15.9 10.7 8.1 7.45 8.1 Z\"/><g class=\"primary\"><path d=\"M7.45 8.1 A3.9 3.9 0 1 0 7.45 15.9 C10.7 15.9 13.3 8.1 16.55 8.1 A3.9 3.9 0 1 1 16.55 15.9 C13.3 15.9 10.7 8.1 7.45 8.1 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function InfinityDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
