// iconaut-react — intersect (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M15 9.02 L15 13 Q15 15 13 15 L9.02 15 A5.5 5.5 0 0 1 15 9.02 Z\"/><g class=\"primary\"><path d=\"M15 9.02 L15 13 Q15 15 13 15 L9.02 15 A5.5 5.5 0 0 1 15 9.02 Z\"/><path d=\"M15 9.02 L15 6 Q15 4 13 4 L6 4 Q4 4 4 6 L4 13 Q4 15 6 15 L9.02 15\"/><path d=\"M15 9.02 A5.5 5.5 0 1 1 9.02 15\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function IntersectDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
