// iconaut-react — invoice (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 5 Q5.5 3 7.5 3 L16.5 3 Q18.5 3 18.5 5 L18.5 19 Q18.5 21 16.5 21 L7.5 21 Q5.5 21 5.5 19 Z\"/><path d=\"M8.5 7.5 L 12.5 7.5\"/><path d=\"M8.5 11.5 L 15.5 11.5\"/><path d=\"M12.5 16.5 L 15.5 16.5\"/>";
const M1 = "<path d=\"M5.5 5 Q5.5 3 7.5 3 L16.5 3 Q18.5 3 18.5 5 L18.5 19 Q18.5 21 16.5 21 L7.5 21 Q5.5 21 5.5 19 Z\"/><path d=\"M8.5 7 L 12.5 7\"/><path d=\"M8.5 10.5 L 15.5 10.5\"/><path d=\"M8.5 14 L 15.5 14\"/><path d=\"M12.5 17.5 L 15.5 17.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function Invoice({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
