// iconaut-react — lamp (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M9.82 2L14.18 2A3.63 3.63 0 0 1 17.57 4.35L19.38 9.18A2.09 2.09 0 0 1 17.43 12L6.57 12A2.09 2.09 0 0 1 4.62 9.18L6.43 4.35A3.63 3.63 0 0 1 9.82 2Z\"/><path d=\"M11 12 Q11 11 12 11 L12 11 Q13 11 13 12 L13 18 Q13 19 12 19 L12 19 Q11 19 11 18 Z M9 19.75 L15 19.75 A0.75 0.75 0 0 0 15 18.25 L9 18.25 A0.75 0.75 0 0 0 9 19.75 Z M10 21.75 L14 21.75 A0.75 0.75 0 0 0 14 20.25 L10 20.25 A0.75 0.75 0 0 0 10 21.75 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M9.83 2.16L14.17 2.16A3.48 3.48 0 0 1 17.43 4.41L19.24 9.23A1.93 1.93 0 0 1 17.43 11.84L6.57 11.84A1.93 1.93 0 0 1 4.76 9.23L6.57 4.41A3.48 3.48 0 0 1 9.83 2.16Z\"/><path d=\"M11 12 Q11 11 12 11 L12 11 Q13 11 13 12 L13 18 Q13 19 12 19 L12 19 Q11 19 11 18 Z M9 19.75 L15 19.75 A0.75 0.75 0 0 0 15 18.25 L9 18.25 A0.75 0.75 0 0 0 9 19.75 Z M10 21.75 L14 21.75 A0.75 0.75 0 0 0 14 20.25 L10 20.25 A0.75 0.75 0 0 0 10 21.75 Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M9.82 2.16L14.18 2.16A3.47 3.47 0 0 1 17.42 4.41L19.23 9.24A1.93 1.93 0 0 1 17.43 11.84L6.57 11.84A1.93 1.93 0 0 1 4.77 9.24L6.58 4.41A3.47 3.47 0 0 1 9.82 2.16Z\"/><path d=\"M11 12 Q11 11 12 11 L12 11 Q13 11 13 12 L13 18 Q13 19 12 19 L12 19 Q11 19 11 18 Z M9 19.75 L15 19.75 A0.75 0.75 0 0 0 15 18.25 L9 18.25 A0.75 0.75 0 0 0 9 19.75 Z M10 21.75 L14 21.75 A0.75 0.75 0 0 0 14 20.25 L10 20.25 A0.75 0.75 0 0 0 10 21.75 Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M9.82 2.15L14.18 2.15A3.48 3.48 0 0 1 17.44 4.41L19.25 9.23A1.94 1.94 0 0 1 17.43 11.85L6.57 11.85A1.94 1.94 0 0 1 4.75 9.23L6.56 4.41A3.48 3.48 0 0 1 9.82 2.15Z\"/><path d=\"M11 12 Q11 11 12 11 L12 11 Q13 11 13 12 L13 18 Q13 19 12 19 L12 19 Q11 19 11 18 Z M9 19.75 L15 19.75 A0.75 0.75 0 0 0 15 18.25 L9 18.25 A0.75 0.75 0 0 0 9 19.75 Z M10 21.75 L14 21.75 A0.75 0.75 0 0 0 14 20.25 L10 20.25 A0.75 0.75 0 0 0 10 21.75 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function LampSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
