// iconaut-react — laptop (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M7.2 4.56L16.8 4.56A2.64 2.64 0 0 1 19.44 7.2L19.44 13.3A2.64 2.64 0 0 1 16.8 15.94L7.2 15.94A2.64 2.64 0 0 1 4.56 13.3L4.56 7.2A2.64 2.64 0 0 1 7.2 4.56Z\"/><path d=\"M2.55 18 Q2.55 17.05 3.5 17.05 L20.5 17.05 Q21.45 17.05 21.45 18 L21.45 18 Q21.45 18.95 20.5 18.95 L3.5 18.95 Q2.55 18.95 2.55 18 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M6.71 4.1L17.29 4.1A2.61 2.61 0 0 1 19.9 6.71L19.9 13.29A2.61 2.61 0 0 1 17.29 15.9L6.71 15.9A2.61 2.61 0 0 1 4.1 13.29L4.1 6.71A2.61 2.61 0 0 1 6.71 4.1Z\"/><path d=\"M2.25 18.5 Q2.25 17.75 3 17.75 L21 17.75 Q21.75 17.75 21.75 18.5 L21.75 18.5 Q21.75 19.25 21 19.25 L3 19.25 Q2.25 19.25 2.25 18.5 Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M6.71 4.13L17.3 4.13A2.58 2.58 0 0 1 19.88 6.71L19.88 13.3A2.58 2.58 0 0 1 17.3 15.88L6.71 15.88A2.58 2.58 0 0 1 4.13 13.3L4.13 6.71A2.58 2.58 0 0 1 6.71 4.13Z\"/><path d=\"M2.25 18.5 Q2.25 17.75 3 17.75 L21 17.75 Q21.75 17.75 21.75 18.5 L21.75 18.5 Q21.75 19.25 21 19.25 L3 19.25 Q2.25 19.25 2.25 18.5 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function LaptopSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
