// iconaut-react — laptop (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M7.21 4.5L16.79 4.5A2.71 2.71 0 0 1 19.5 7.21L19.5 13.29A2.71 2.71 0 0 1 16.79 16L7.21 16A2.71 2.71 0 0 1 4.5 13.29L4.5 7.21A2.71 2.71 0 0 1 7.21 4.5Z\"/><path d=\"M2.55 18 Q2.55 17.05 3.5 17.05 L20.5 17.05 Q21.45 17.05 21.45 18 L21.45 18 Q21.45 18.95 20.5 18.95 L3.5 18.95 Q2.55 18.95 2.55 18 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M7.21 4.66L16.79 4.66A2.55 2.55 0 0 1 19.34 7.21L19.34 13.29A2.55 2.55 0 0 1 16.79 15.84L7.21 15.84A2.55 2.55 0 0 1 4.66 13.29L4.66 7.21A2.55 2.55 0 0 1 7.21 4.66Z\"/><path d=\"M2.55 18 Q2.55 17.05 3.5 17.05 L20.5 17.05 Q21.45 17.05 21.45 18 L21.45 18 Q21.45 18.95 20.5 18.95 L3.5 18.95 Q2.55 18.95 2.55 18 Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M6.71 4.16L17.29 4.16A2.55 2.55 0 0 1 19.84 6.71L19.84 13.29A2.55 2.55 0 0 1 17.29 15.84L6.71 15.84A2.55 2.55 0 0 1 4.16 13.29L4.16 6.71A2.55 2.55 0 0 1 6.71 4.16Z\"/><path d=\"M2.25 18.5 Q2.25 17.75 3 17.75 L21 17.75 Q21.75 17.75 21.75 18.5 L21.75 18.5 Q21.75 19.25 21 19.25 L3 19.25 Q2.25 19.25 2.25 18.5 Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M6.71 4.15L17.29 4.15A2.56 2.56 0 0 1 19.85 6.71L19.85 13.29A2.56 2.56 0 0 1 17.29 15.85L6.71 15.85A2.56 2.56 0 0 1 4.15 13.29L4.15 6.71A2.56 2.56 0 0 1 6.71 4.15Z\"/><path d=\"M2.25 18.5 Q2.25 17.75 3 17.75 L21 17.75 Q21.75 17.75 21.75 18.5 L21.75 18.5 Q21.75 19.25 21 19.25 L3 19.25 Q2.25 19.25 2.25 18.5 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function LaptopSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
