// iconaut-react — layout-rows (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3.75 7.25 Q3.75 5.25 5.75 5.25 L18.25 5.25 Q20.25 5.25 20.25 7.25 L20.25 16.75 Q20.25 18.75 18.25 18.75 L5.75 18.75 Q3.75 18.75 3.75 16.75 Z\"/><path d=\"M3.5 12 L 20.5 12\"/>";
const M1 = "<path d=\"M3 6.8 Q3 4.8 5 4.8 L19 4.8 Q21 4.8 21 6.8 L21 17.2 Q21 19.2 19 19.2 L5 19.2 Q3 19.2 3 17.2 Z\"/><path d=\"M3 12 L 21 12\"/>";
const M2 = "<path d=\"M3 7 Q3 5 5 5 L19 5 Q21 5 21 7 L21 17 Q21 19 19 19 L5 19 Q3 19 3 17 Z\"/><path d=\"M3 12 L 21 12\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M2, 1.75]
};
const S = [16, 20, 24];

export default function LayoutRows({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
