// iconaut-react — level (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 10 Q3 9 4 9 L20 9 Q21 9 21 10 L21 14 Q21 15 20 15 L4 15 Q3 15 3 14 Z\"/><path d=\"M9 11.5 Q9 10.5 10 10.5 L14 10.5 Q15 10.5 15 11.5 L15 12.5 Q15 13.5 14 13.5 L10 13.5 Q9 13.5 9 12.5 Z\"/><path d=\"M11 12 A1 1 0 1 0 13 12 A1 1 0 1 0 11 12 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Level({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
