// iconaut-react — locate (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.75 12 A7.25 7.25 0 1 0 19.25 12 A7.25 7.25 0 1 0 4.75 12 M8.5 12 A3.5 3.5 0 1 1 15.5 12 A3.5 3.5 0 1 1 8.5 12 M12 1.9 Q11.25 1.9 11.25 2.65 L11.25 4.85 Q11.25 5.6 12 5.6 L12 5.6 Q12.75 5.6 12.75 4.85 L12.75 2.65 Q12.75 1.9 12 1.9 Z M12 18.4 Q11.25 18.4 11.25 19.15 L11.25 21.35 Q11.25 22.1 12 22.1 L12 22.1 Q12.75 22.1 12.75 21.35 L12.75 19.15 Q12.75 18.4 12 18.4 Z M2.65 11.25 Q1.9 11.25 1.9 12 L1.9 12 Q1.9 12.75 2.65 12.75 L4.85 12.75 Q5.6 12.75 5.6 12 L5.6 12 Q5.6 11.25 4.85 11.25 Z M19.15 11.25 Q18.4 11.25 18.4 12 L18.4 12 Q18.4 12.75 19.15 12.75 L21.35 12.75 Q22.1 12.75 22.1 12 L22.1 12 Q22.1 11.25 21.35 11.25 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M0, null],
  20: [M0, null],
  24: [M0, null]
};
const S = [12, 16, 20, 24];

export default function LocateSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
