// iconaut-react — lungs (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M8.3 7.4 L8.3 17.9 C8.3 19.1 7.5 19.9 6.3 19.9 C4.3 19.9 3.2 18.4 3.3 16.1 C3.4 12.5 5.1 8.7 6.9 6.9 C7.5 6.3 8.3 6.5 8.3 7.4 Z\"/><path d=\"M15.7 7.4 L15.7 17.9 C15.7 19.1 16.5 19.9 17.7 19.9 C19.7 19.9 20.8 18.4 20.7 16.1 C20.6 12.5 18.9 8.7 17.1 6.9 C16.5 6.3 15.7 6.5 15.7 7.4 Z\"/><path d=\"M12 3.6 L12 8.8 C12 10.6 10.4 11.6 8.3 12.2\"/><path d=\"M12 8.8 C12 10.6 13.6 11.6 15.7 12.2\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Lungs({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
