// iconaut-react — mail (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M5.2 5.06L18.8 5.06A2.64 2.64 0 0 1 21.44 7.7L21.44 16.3A2.64 2.64 0 0 1 18.8 18.94L5.2 18.94A2.64 2.64 0 0 1 2.56 16.3L2.56 7.7A2.64 2.64 0 0 1 5.2 5.06Z M12 11.56L19.4 6.56L19.94 6.56L19.94 8.57L19.9 8.6L12.2 13.8L12.09 13.85L11.97 13.86L11.86 13.83L11.8 13.8L4.1 8.6L4.06 8.57L4.06 6.56L4.6 6.56Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M4.71 4.6L19.29 4.6A2.61 2.61 0 0 1 21.9 7.21L21.9 16.79A2.61 2.61 0 0 1 19.29 19.4L4.71 19.4A2.61 2.61 0 0 1 2.1 16.79L2.1 7.21A2.61 2.61 0 0 1 4.71 4.6Z M3.96 6.06L12 11.46L20.04 6.06L20.1 6.04L20.31 6.04L20.35 6.05L20.43 6.13L20.46 6.19L20.46 8.01L20.41 8.1L20.36 8.14L12.16 13.64L12.06 13.68L11.96 13.68L11.84 13.64L3.64 8.14L3.57 8.06L3.54 8.01L3.54 6.19L3.59 6.11L3.68 6.04L3.69 6.04L3.91 6.04Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M4.71 4.63L19.3 4.63A2.58 2.58 0 0 1 21.88 7.21L21.88 16.8A2.58 2.58 0 0 1 19.3 19.38L4.71 19.38A2.58 2.58 0 0 1 2.13 16.8L2.13 7.21A2.58 2.58 0 0 1 4.71 4.63Z M3.9 6.06L3.95 6.08L12 11.49L20.06 6.08L20.15 6.05L20.25 6.04L20.34 6.08L20.42 6.16L20.45 6.25L20.46 6.3L20.46 7.9L20.44 8L20.35 8.12L12.15 13.62L12.05 13.66L11.95 13.66L11.86 13.62L3.66 8.12L3.58 8.04L3.54 7.9L3.54 6.3L3.56 6.2L3.62 6.12L3.7 6.06L3.8 6.04Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function MailSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
