// iconaut-react — mail (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M5.21 5L18.79 5A2.71 2.71 0 0 1 21.5 7.71L21.5 16.29A2.71 2.71 0 0 1 18.79 19L5.21 19A2.71 2.71 0 0 1 2.5 16.29L2.5 7.71A2.71 2.71 0 0 1 5.21 5Z M12 11.49L19.24 6.6L19.9 6.6L19.9 8.68L12.24 13.85L12.12 13.91L11.99 13.93L11.86 13.9L11.76 13.85L4.1 8.68L4.1 6.6L4.76 6.6Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M5.21 5.16L18.79 5.16A2.55 2.55 0 0 1 21.34 7.71L21.34 16.29A2.55 2.55 0 0 1 18.79 18.84L5.21 18.84A2.55 2.55 0 0 1 2.66 16.29L2.66 7.71A2.55 2.55 0 0 1 5.21 5.16Z M4.39 6.55L4.45 6.58L12 11.68L19.55 6.58L19.65 6.54L19.75 6.54L19.84 6.57L19.92 6.64L19.96 6.74L19.97 6.8L19.97 8.3L19.95 8.4L19.89 8.49L19.85 8.52L12.15 13.72L12.06 13.76L11.95 13.76L11.85 13.72L4.15 8.52L4.08 8.45L4.04 8.35L4.03 8.3L4.03 6.8L4.05 6.7L4.11 6.61L4.19 6.55L4.29 6.53Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M4.71 4.66L19.29 4.66A2.55 2.55 0 0 1 21.84 7.21L21.84 16.79A2.55 2.55 0 0 1 19.29 19.34L4.71 19.34A2.55 2.55 0 0 1 2.16 16.79L2.16 7.21A2.55 2.55 0 0 1 4.71 4.66Z M3.93 6.11L12 11.53L20.07 6.11L20.16 6.08L20.26 6.08L20.34 6.12L20.4 6.2L20.43 6.3L20.43 7.9L20.41 7.99L20.33 8.09L12.13 13.59L12.04 13.62L11.94 13.62L11.87 13.59L3.67 8.09L3.61 8.02L3.58 7.9L3.58 6.3L3.59 6.21L3.65 6.13L3.73 6.09L3.83 6.08Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M4.71 4.65L19.29 4.65A2.56 2.56 0 0 1 21.85 7.21L21.85 16.79A2.56 2.56 0 0 1 19.29 19.35L4.71 19.35A2.56 2.56 0 0 1 2.15 16.79L2.15 7.21A2.56 2.56 0 0 1 4.71 4.65Z M3.93 6.1L12 11.52L20.07 6.1L20.16 6.07L20.26 6.07L20.34 6.11L20.41 6.19L20.43 6.3L20.43 7.9L20.42 7.99L20.33 8.1L12.13 13.6L12.04 13.63L11.95 13.63L11.87 13.6L3.67 8.1L3.6 8.03L3.57 7.9L3.57 6.3L3.58 6.21L3.64 6.13L3.72 6.08L3.82 6.07Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function MailSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
