// iconaut-react — mastodon (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4.5 14.5 L4.5 10.2 A3.75 3.75 0 0 1 12 10.2 A3.75 3.75 0 0 1 19.5 10.2 L19.5 14.5 Q19.5 16.5 17.5 16.5 L6.5 16.5 Q4.5 16.5 4.5 14.5 Z M9.33 12.6L9.48 12.6A0.68 0.68 0 0 1 10.15 13.28L10.15 16.5L8.65 16.5L8.65 13.28A0.68 0.68 0 0 1 9.33 12.6Z M14.53 12.6L14.68 12.6A0.68 0.68 0 0 1 15.35 13.28L15.35 16.5L13.85 16.5L13.85 13.28A0.68 0.68 0 0 1 14.53 12.6Z\"/><g class=\"primary\"><path d=\"M4.5 14.5 L4.5 10.2 A3.75 3.75 0 0 1 12 10.2 A3.75 3.75 0 0 1 19.5 10.2 L19.5 14.5 Q19.5 16.5 17.5 16.5 L6.5 16.5 Q4.5 16.5 4.5 14.5 Z\"/><path d=\"M9.4 16.5 L 9.4 12.6 M14.6 16.5 L 14.6 12.6\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function MastodonDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
