// iconaut-react — messages-circle (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7.35 18.15 A5.4 5.4 0 1 0 4.99 15.91 L4.14 18.32 Q3.47 20.21 5.24 19.27 L7.35 18.15 Z\"/><path d=\"M10.78 8 A4.9 4.9 0 1 1 15.12 13.71\"/>";
const M1 = "<path d=\"M7.01 18.65 A5.7 5.7 0 1 0 4.5 16.29 L3.59 18.86 Q2.93 20.75 4.71 19.83 L7.01 18.65 Z\"/><path d=\"M10.67 7.91 A5.2 5.2 0 1 1 15.23 13.91\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function MessagesCircle({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
