// iconaut-react — message-off (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 6 Q4 4 6 4 L18 4 Q20 4 20 6 L20 14.8 Q20 16.8 18 16.8 L9.8 16.8 Q7.8 16.8 6.39 18.21 L5.41 19.19 Q4 20.6 4 18.6 Z\"/><g class=\"primary\"><path d=\"M4.5 4.5Q5 4 6 4L18 4Q20 4 20 6L20 14.8Q20 16.8 18 16.8L16.8 16.8M11.85 16.8L9.8 16.8Q7.8 16.8 6.39 18.21L5.41 19.19Q4 20.6 4 18.6L4 8.95\"/><path d=\"M4.25 4.25L20.25 20.25\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 6 Q4 4 6 4 L18 4 Q20 4 20 6 L20 14.8 Q20 16.8 18 16.8 L9.8 16.8 Q7.8 16.8 6.39 18.21 L5.41 19.19 Q4 20.6 4 18.6 Z\"/><g class=\"primary\"><path d=\"M4.5 4.5Q5 4 6 4L18 4Q20 4 20 6L20 14.8Q20 16.8 18 16.8L16.8 16.8M12.29 16.8L9.8 16.8Q7.8 16.8 6.39 18.21L5.41 19.19Q4 20.6 4 18.6L4 8.51\"/><path d=\"M4.25 4.25L20.25 20.25\"/></g>";
const M2 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 6 Q4 4 6 4 L18 4 Q20 4 20 6 L20 14.8 Q20 16.8 18 16.8 L9.8 16.8 Q7.8 16.8 6.39 18.21 L5.41 19.19 Q4 20.6 4 18.6 Z\"/><g class=\"primary\"><path d=\"M4.5 4.5Q5 4 6 4L18 4Q20 4 20 6L20 14.8Q20 16.8 18 16.8L16.8 16.8M12.3 16.8L9.8 16.8Q7.8 16.8 6.39 18.21L5.41 19.19Q4 20.6 4 18.6L4 8.5\"/><path d=\"M4 4L20.5 20.5\"/></g>";
const M3 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 6 Q4 4 6 4 L18 4 Q20 4 20 6 L20 14.8 Q20 16.8 18 16.8 L9.8 16.8 Q7.8 16.8 6.39 18.21 L5.41 19.19 Q4 20.6 4 18.6 Z\"/><g class=\"primary\"><path d=\"M4.5 4.5Q5 4 6 4L18 4Q20 4 20 6L20 14.8Q20 16.8 18 16.8L16.8 16.8M12.27 16.8L9.8 16.8Q7.8 16.8 6.39 18.21L5.41 19.19Q4 20.6 4 18.6L4 8.53\"/><path d=\"M4 4L20.5 20.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M1, 1.688],
  20: [M2, 1.68],
  24: [M3, 1.7]
};
const S = [12, 16, 20, 24];

export default function MessageOffDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
