// iconaut-react — mic (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M12 3 A2.8 2.8 0 0 0 9.2 5.8 L9.2 10.8 A2.8 2.8 0 0 0 14.8 10.8 L14.8 5.8 A2.8 2.8 0 0 0 12 3 Z\"/><path d=\"M6.8 10.5 L6.8 10.8 A5.2 5.2 0 0 0 17.2 10.8 L17.2 10.5\"/><path d=\"M12 16 L 12 19.5\"/><path d=\"M8.5 19.5 L 15.5 19.5\"/>";
const M1 = "<path d=\"M12 2.8 A2.9 2.9 0 0 0 9.1 5.7 L9.1 11.1 A2.9 2.9 0 0 0 14.9 11.1 L14.9 5.7 A2.9 2.9 0 0 0 12 2.8 Z\"/><path d=\"M6.5 10.8 L6.5 11 A5.5 5.5 0 0 0 17.5 11 L17.5 10.8\"/><path d=\"M12 16.5 L 12 20\"/><path d=\"M8.3 20 L 15.7 20\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function Mic({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
