// iconaut-react — milk (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M7.16 18.29L7.16 9.97A9.2 9.2 0 0 1 8.13 5.86L8.47 5.19A3.67 3.67 0 0 1 11.75 3.16L12.25 3.16A3.67 3.67 0 0 1 15.53 5.19L15.87 5.86A9.2 9.2 0 0 1 16.84 9.97L16.84 18.29A2.55 2.55 0 0 1 14.29 20.84L9.71 20.84A2.55 2.55 0 0 1 7.16 18.29Z M15 13L9 13L9 11L15 11ZM13.98 6.2L13.98 6.2L13.92 6.39L13.83 6.57L13.7 6.72L13.54 6.84L13.36 6.93L13.17 6.99L13 7L11 7L10.8 6.98L10.61 6.92L10.44 6.83L10.28 6.7L10.16 6.54L10.07 6.36L10.02 6.19L10.62 5L13.38 5Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M7.15 18.29L7.15 9.97A9.23 9.23 0 0 1 8.12 5.86L8.45 5.19A3.68 3.68 0 0 1 11.75 3.15L12.25 3.15A3.68 3.68 0 0 1 15.55 5.19L15.88 5.86A9.23 9.23 0 0 1 16.85 9.97L16.85 18.29A2.56 2.56 0 0 1 14.29 20.85L9.71 20.85A2.56 2.56 0 0 1 7.15 18.29Z M15 13L9 13L9 11L15 11ZM13.98 6.2L13.98 6.2L13.92 6.39L13.83 6.57L13.7 6.72L13.54 6.84L13.36 6.93L13.17 6.99L13 7L11 7L10.8 6.98L10.61 6.92L10.44 6.83L10.28 6.7L10.16 6.54L10.07 6.36L10.02 6.19L10.62 5L13.38 5Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M0, null],
  24: [M1, null]
};
const S = [16, 20, 24];

export default function MilkSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
