// iconaut-react — motorcycle (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M2.5 16.5 A3 3 0 1 0 8.5 16.5 A3 3 0 1 0 2.5 16.5 Z\"/><path d=\"M15.5 16.5 A3 3 0 1 0 21.5 16.5 A3 3 0 1 0 15.5 16.5 Z\"/><path d=\"M3.38 14.38 L3.69 12.69 Q4 11 5.72 11 L8.75 11 Q10 11 10.75 10 L10.75 10 Q11.5 9 12.75 9 L14.33 9 Q16.33 9 14.91 10.41 L13.22 12.09 Q11.8 13.5 9.95 14.25 L8.1 15 A3 3 0 0 0 3.38 14.38 Z\"/><path d=\"M18.5 16.5 L15.89 7.46 Q15.61 6.5 16.61 6.5 L17.6 6.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Motorcycle({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
