// iconaut-react — mushroom (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 11 A8 6 0 0 1 20 11 L17 11 Q15 11 15 13 L15 18 A3 3 0 0 1 9 18 L9 13 Q9 11 7 11 L4 11 Z\"/><g class=\"primary\"><path d=\"M4 11 A8 6 0 0 1 20 11 L17 11 Q15 11 15 13 L15 18 A3 3 0 0 1 9 18 L9 13 Q9 11 7 11 L4 11 Z\"/><path d=\"M9 8 L 9.01 8 M14 8 L 14.01 8 M12 9.5 L 12.01 9.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function MushroomDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
