// iconaut-react — navigation (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M13.43 3.4L20.32 18.91A1.39 1.39 0 0 1 18.39 20.7L13.21 17.91A2.56 2.56 0 0 0 10.79 17.91L5.61 20.7A1.39 1.39 0 0 1 3.68 18.91L10.57 3.4A1.56 1.56 0 0 1 13.43 3.4Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M13.39 3.42L20.28 18.93A1.35 1.35 0 0 1 18.41 20.67L13.23 17.88A2.6 2.6 0 0 0 10.77 17.88L5.59 20.67A1.35 1.35 0 0 1 3.72 18.93L10.61 3.42A1.52 1.52 0 0 1 13.39 3.42Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M13.37 3.43L20.26 18.93A1.33 1.33 0 0 1 18.42 20.64L13.24 17.86A2.62 2.62 0 0 0 10.76 17.86L5.58 20.64A1.33 1.33 0 0 1 3.74 18.93L10.63 3.43A1.5 1.5 0 0 1 13.37 3.43Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function NavigationSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
