// iconaut-react — octagon (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M10.27 2.26L13.73 2.26A5.58 5.58 0 0 1 17.67 3.89L20.11 6.33A5.58 5.58 0 0 1 21.74 10.27L21.74 13.73A5.58 5.58 0 0 1 20.11 17.67L17.67 20.11A5.58 5.58 0 0 1 13.73 21.74L10.27 21.74A5.58 5.58 0 0 1 6.33 20.11L3.89 17.67A5.58 5.58 0 0 1 2.26 13.73L2.26 10.27A5.58 5.58 0 0 1 3.89 6.33L6.33 3.89A5.58 5.58 0 0 1 10.27 2.26Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M10.28 2.3L13.72 2.3A5.54 5.54 0 0 1 17.64 3.92L20.08 6.36A5.54 5.54 0 0 1 21.7 10.28L21.7 13.72A5.54 5.54 0 0 1 20.08 17.64L17.64 20.08A5.54 5.54 0 0 1 13.72 21.7L10.28 21.7A5.54 5.54 0 0 1 6.36 20.08L3.92 17.64A5.54 5.54 0 0 1 2.3 13.72L2.3 10.28A5.54 5.54 0 0 1 3.92 6.36L6.36 3.92A5.54 5.54 0 0 1 10.28 2.3Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M10.28 2.32L13.72 2.33A5.53 5.53 0 0 1 17.63 3.94L20.06 6.37A5.51 5.51 0 0 1 21.68 10.28L21.68 13.72A5.52 5.52 0 0 1 20.06 17.63L17.63 20.06A5.52 5.52 0 0 1 13.72 21.68L10.28 21.68A5.52 5.52 0 0 1 6.37 20.06L3.94 17.63A5.51 5.51 0 0 1 2.32 13.72L2.33 10.28A5.53 5.53 0 0 1 3.94 6.37L6.37 3.94A5.5 5.5 0 0 1 10.28 2.32Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function OctagonSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
