// iconaut-react — owl (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6.25 7.63 L6.86 5.42 Q7.4 3.49 8.79 4.93 L10.28 6.48 A6.9 8.05 0 0 1 13.73 6.48 L15.22 4.93 Q16.6 3.49 17.14 5.42 L17.75 7.63 A6.9 8.05 0 1 1 6.25 7.63 Z\"/><path d=\"M5.79 13.15 A2.53 2.53 0 1 0 10.85 13.15 A2.53 2.53 0 1 0 5.79 13.15\"/><path d=\"M13.15 13.15 A2.53 2.53 0 1 0 18.21 13.15 A2.53 2.53 0 1 0 13.15 13.15\"/><path d=\"M8.32 13.15 L 8.33 13.15\"/><path d=\"M15.68 13.15 L 15.69 13.15\"/>";
const M1 = "<path d=\"M6.25 7.63 L6.86 5.42 Q7.4 3.49 8.79 4.93 L10.28 6.48 A6.9 8.05 0 0 1 13.73 6.48 L15.22 4.93 Q16.6 3.49 17.14 5.42 L17.75 7.63 A6.9 8.05 0 1 1 6.25 7.63 Z\"/><path d=\"M5.79 13.15 A2.53 2.53 0 1 0 10.85 13.15 A2.53 2.53 0 1 0 5.79 13.15\"/><path d=\"M13.15 13.15 A2.53 2.53 0 1 0 18.21 13.15 A2.53 2.53 0 1 0 13.15 13.15\"/><path d=\"M8.32 13.15 L 8.33 13.15\"/><path d=\"M15.68 13.15 L 15.69 13.15\"/><path d=\"M10.85 15.68 L11.43 16.37 Q12 17.06 12.58 16.37 L13.15 15.68\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Owl({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
