// iconaut-react — paintbrush (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6.2 5.4 Q6.2 3.4 8.2 3.4 L15.8 3.4 Q17.8 3.4 17.8 5.4 L17.8 9 Q17.8 11 15.8 11 L8.2 11 Q6.2 11 6.2 9 Z M6.2 11.9 L6.2 12.8 A2 2 0 0 0 8.2 14.8 L9.1 14.8 Q10 14.8 10 15.7 L10 18.6 A2 2 0 0 0 14 18.6 L14 15.7 Q14 14.8 14.9 14.8 L15.8 14.8 A2 2 0 0 0 17.8 12.8 L17.8 11.9 Q17.8 11 16.9 11 L7.1 11 Q6.2 11 6.2 11.9 Z\"/><g class=\"primary\"><path d=\"M6.2 4.4 Q6.2 3.4 7.2 3.4 L16.8 3.4 Q17.8 3.4 17.8 4.4 L17.8 10 Q17.8 11 16.8 11 L7.2 11 Q6.2 11 6.2 10 Z\"/><path d=\"M10.2 3.4 L 10.2 6.4 M13.8 3.4 L 13.8 7.2\"/><path d=\"M6.2 11.9 L6.2 12.8 A2 2 0 0 0 8.2 14.8 L9.1 14.8 Q10 14.8 10 15.7 L10 18.6 A2 2 0 0 0 14 18.6 L14 15.7 Q14 14.8 14.9 14.8 L15.8 14.8 A2 2 0 0 0 17.8 12.8 L17.8 11.9 Q17.8 11 16.9 11 L7.1 11 Q6.2 11 6.2 11.9 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function PaintbrushDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
