// iconaut-react — parallelogram (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M9.81 3.16L19.41 3.16A2.01 2.01 0 0 1 21.33 5.78L17.34 18.52A3.3 3.3 0 0 1 14.19 20.84L4.59 20.84A2.01 2.01 0 0 1 2.67 18.22L6.66 5.48A3.3 3.3 0 0 1 9.81 3.16Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M9.8 3.16L19.41 3.16A2.01 2.01 0 0 1 21.32 5.77L17.34 18.53A3.3 3.3 0 0 1 14.2 20.84L4.59 20.84A2.01 2.01 0 0 1 2.68 18.23L6.66 5.47A3.3 3.3 0 0 1 9.8 3.16Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M9.81 3.15L19.41 3.15A2.02 2.02 0 0 1 21.34 5.77L17.35 18.53A3.31 3.31 0 0 1 14.19 20.85L4.59 20.85A2.02 2.02 0 0 1 2.66 18.23L6.65 5.47A3.31 3.31 0 0 1 9.81 3.15Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function ParallelogramSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
