// iconaut-react — pennant (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M7.78 4.11L19.4 7.26A1.19 1.19 0 0 1 19.4 9.54L7.78 12.69A2.07 2.07 0 0 1 5.16 10.69L5.16 6.11A2.07 2.07 0 0 1 7.78 4.11Z\"/><path d=\"M5.25 4 Q5.25 3.25 6 3.25 L6 3.25 Q6.75 3.25 6.75 4 L6.75 20.5 Q6.75 21.25 6 21.25 L6 21.25 Q5.25 21.25 5.25 20.5 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M7.77 4.11L19.4 7.26A1.18 1.18 0 0 1 19.4 9.54L7.77 12.69A2.07 2.07 0 0 1 5.16 10.69L5.16 6.11A2.07 2.07 0 0 1 7.77 4.11Z\"/><path d=\"M5.25 4 Q5.25 3.25 6 3.25 L6 3.25 Q6.75 3.25 6.75 4 L6.75 20.5 Q6.75 21.25 6 21.25 L6 21.25 Q5.25 21.25 5.25 20.5 Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M7.77 4.1L19.4 7.25A1.19 1.19 0 0 1 19.4 9.55L7.77 12.7A2.08 2.08 0 0 1 5.15 10.69L5.15 6.11A2.08 2.08 0 0 1 7.77 4.1Z\"/><path d=\"M5.25 4 Q5.25 3.25 6 3.25 L6 3.25 Q6.75 3.25 6.75 4 L6.75 20.5 Q6.75 21.25 6 21.25 L6 21.25 Q5.25 21.25 5.25 20.5 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function PennantSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
