// iconaut-react — pentagon (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M14.01 2.81L20.09 7.27A3.45 3.45 0 0 1 21.34 11.11L19.04 18.27A3.42 3.42 0 0 1 15.79 20.64L8.21 20.64A3.42 3.42 0 0 1 4.96 18.27L2.66 11.11A3.45 3.45 0 0 1 3.91 7.27L9.99 2.81A3.4 3.4 0 0 1 14.01 2.81Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M13.99 2.84L20.07 7.3A3.42 3.42 0 0 1 21.3 11.1L19.01 18.25A3.38 3.38 0 0 1 15.8 20.6L8.2 20.6A3.38 3.38 0 0 1 4.99 18.25L2.7 11.1A3.42 3.42 0 0 1 3.93 7.3L10.01 2.84A3.36 3.36 0 0 1 13.99 2.84Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M13.97 2.86L20.06 7.33A3.39 3.39 0 0 1 21.28 11.09L18.99 18.25A3.35 3.35 0 0 1 15.79 20.58L8.21 20.58A3.35 3.35 0 0 1 5.01 18.25L2.72 11.09A3.39 3.39 0 0 1 3.94 7.33L10.03 2.86A3.34 3.34 0 0 1 13.97 2.86Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function PentagonSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
