// iconaut-react — phone (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M20.4 16.13 L20.4 18.65 A1.68 1.68 0 0 1 18.57 20.33 A16.62 16.62 0 0 1 11.32 17.75 A16.38 16.38 0 0 1 6.28 12.71 A16.62 16.62 0 0 1 3.7 5.43 A1.68 1.68 0 0 1 5.37 3.6 L7.89 3.6 A1.68 1.68 0 0 1 9.57 5.04 A10.79 10.79 0 0 0 10.16 7.4 A1.68 1.68 0 0 1 9.78 9.17 L8.72 10.24 A13.44 13.44 0 0 0 13.76 15.28 L14.83 14.21 A1.68 1.68 0 0 1 16.6 13.83 A10.79 10.79 0 0 0 18.96 14.42 A1.68 1.68 0 0 1 20.4 16.13 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Phone({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
