// iconaut-react — pig (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5 12 A7 7 0 1 0 19 12 A7 7 0 1 0 5 12 Z\"/><path d=\"M7 6 L 5 3 M17 6 L 19 3\"/><path d=\"M9.5 14 A2.5 2.5 0 1 1 14.5 14 A2.5 2.5 0 1 1 9.5 14 Z\"/><path d=\"M11 14 L 11.01 14 M13 14 L 13.01 14\"/><path d=\"M9 10 L 9.01 10 M15 10 L 15.01 10\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Pig({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
