// iconaut-react — pig (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M12 5.2 C13.6 5.2 15.1 5.6 16.3 6.4 L17.6 5 Q18.9 3.6 18.98 5.51 L19.1 8.6 C19.6 9.7 19.8 11.1 19.8 12.6 C19.8 17.1 16.4 20.2 12 20.2 C7.6 20.2 4.2 17.1 4.2 12.6 C4.2 11.1 4.4 9.7 4.9 8.6 L5.02 5.51 Q5.1 3.6 6.4 5 L7.7 6.4 C8.9 5.6 10.4 5.2 12 5.2 Z\"/><path d=\"M9 15.4 A3 2.3 0 1 0 15 15.4 A3 2.3 0 1 0 9 15.4 Z\"/><path d=\"M10.9 15.4 L 10.91 15.4\"/><path d=\"M13.1 15.4 L 13.11 15.4\"/><path d=\"M9 11 L 9.01 11\"/><path d=\"M15 11 L 15.01 11\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Pig({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
