// iconaut-react — pills (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.71 8.39 L8.39 4.71 A2.9 2.9 0 0 1 12.49 8.81 L8.81 12.49 A2.9 2.9 0 0 1 4.71 8.39 Z\"/><path d=\"M13.3 17.2 A3.9 3.9 0 1 0 21.1 17.2 A3.9 3.9 0 1 0 13.3 17.2 Z\"/><path d=\"M6.55 6.55 L 10.65 10.65\"/><path d=\"M19.29 15.11 L 15.11 19.29\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Pills({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
