// iconaut-react — pill (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6.14 12.34 L12.34 6.14 A3.9 3.9 0 0 1 17.86 11.66 L11.66 17.86 A3.9 3.9 0 0 1 6.14 12.34 Z M9.24 9.24 14.76 14.76 11.66 17.86A3.9 3.9 0 0 1 6.14 12.34Z\"/><g class=\"primary\"><path d=\"M6.14 12.34 L12.34 6.14 A3.9 3.9 0 0 1 17.86 11.66 L11.66 17.86 A3.9 3.9 0 0 1 6.14 12.34 Z\"/><path d=\"M9.24 9.24 L 14.76 14.76\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function PillDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
