// iconaut-react — pin (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M12 15.85 L 12 20.45\"/><path d=\"M9.85 2.75 L14.15 2.75 A2 2 0 0 1 16.15 4.75 L16.15 6.6 C16.15 7.5 14.35 7.4 14.35 8.5 L14.35 9.5 C14.35 11.3 18.15 11.6 18.15 13.6 L18.15 14.85 Q18.15 15.85 17.15 15.85 L6.85 15.85 Q5.85 15.85 5.85 14.85 L5.85 13.6 C5.85 11.6 9.65 11.3 9.65 9.5 L9.65 8.5 C9.65 7.4 7.85 7.5 7.85 6.6 L7.85 4.75 A2 2 0 0 1 9.85 2.75 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function Pin({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
