// iconaut-react — pinterest (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M2.88 12 A9.12 9.12 0 1 0 21.12 12 A9.12 9.12 0 1 0 2.88 12 Z\"/><path d=\"M7.55 14.45 C6.35 12.9 6.3 10.35 7.75 8.55 C9.05 6.95 10.95 6.6 12.65 6.6 C15.5 6.6 17.2 8.85 17.2 11.75 C17.2 14.75 15.1 16.85 12.8 16.85 C11.95 16.85 11.15 16.45 10.45 15.7\"/><path d=\"M11.05 11.15 C10.6 12.5 10.5 14 10.35 15.6 L8.88 20.58\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Pinterest({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
