// iconaut-react — play (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M9.29 4.95L17.74 10.33A1.98 1.98 0 0 1 17.74 13.67L9.29 19.05A1.81 1.81 0 0 1 6.5 17.52L6.5 6.48A1.81 1.81 0 0 1 9.29 4.95Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M9.21 5.08L17.66 10.46A1.82 1.82 0 0 1 17.66 13.54L9.21 18.92A1.66 1.66 0 0 1 6.66 17.52L6.66 6.48A1.66 1.66 0 0 1 9.21 5.08Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M8.69 4.12L18.17 10.44A1.88 1.88 0 0 1 18.17 13.56L8.69 19.88A1.63 1.63 0 0 1 6.16 18.53L6.16 5.47A1.63 1.63 0 0 1 8.69 4.12Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M8.7 4.11L18.18 10.43A1.89 1.89 0 0 1 18.18 13.57L8.7 19.89A1.64 1.64 0 0 1 6.15 18.53L6.15 5.47A1.64 1.64 0 0 1 8.7 4.11Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function PlaySolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
