// iconaut-react — podium (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M2.5 18.79L2.5 11.53A2.03 2.03 0 0 1 4.53 9.5L6.29 9.5A0.71 0.71 0 0 0 7 8.79L7 7.03A2.03 2.03 0 0 1 9.03 5L14.29 5A2.71 2.71 0 0 1 17 7.71L17 11.79A0.71 0.71 0 0 0 17.71 12.5L19.48 12.5A2.03 2.03 0 0 1 21.5 14.53L21.5 18.79A2.71 2.71 0 0 1 18.79 21.5L5.21 21.5A2.71 2.71 0 0 1 2.5 18.79Z M16.7 18.9L15.3 18.9L15.3 15.1L16.7 15.1ZM8.7 18.9L7.3 18.9L7.3 12.1L8.7 12.1ZM12.9 15.5L11.5 15.5L11.5 9.9L12.9 9.9Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M2.66 18.79L2.66 11.69A2.03 2.03 0 0 1 4.69 9.66L6.3 9.66A0.86 0.86 0 0 0 7.16 8.8L7.16 7.19A2.03 2.03 0 0 1 9.19 5.16L14.29 5.16A2.55 2.55 0 0 1 16.84 7.71L16.84 11.8A0.86 0.86 0 0 0 17.7 12.66L19.32 12.66A2.03 2.03 0 0 1 21.34 14.69L21.34 18.79A2.55 2.55 0 0 1 18.79 21.34L5.21 21.34A2.55 2.55 0 0 1 2.66 18.79Z M16.7 18.9L15.3 18.9L15.3 15.1L16.7 15.1ZM8.7 18.9L7.3 18.9L7.3 12.1L8.7 12.1ZM12.9 15.5L11.5 15.5L11.5 9.9L12.9 9.9Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M2.66 18.79L2.66 11.69A2.03 2.03 0 0 1 4.69 9.66L6.29 9.66A0.87 0.87 0 0 0 7.16 8.79L7.16 7.19A2.03 2.03 0 0 1 9.19 5.16L14.29 5.16A2.55 2.55 0 0 1 16.84 7.71L16.84 11.79A0.87 0.87 0 0 0 17.71 12.66L19.32 12.66A2.03 2.03 0 0 1 21.34 14.69L21.34 18.79A2.55 2.55 0 0 1 18.79 21.34L5.21 21.34A2.55 2.55 0 0 1 2.66 18.79Z M16.7 18.9L15.3 18.9L15.3 15.1L16.7 15.1ZM8.7 18.9L7.3 18.9L7.3 12.1L8.7 12.1ZM12.9 15.5L11.5 15.5L11.5 9.9L12.9 9.9Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M2.65 18.79L2.65 11.68A2.03 2.03 0 0 1 4.68 9.65L6.29 9.65A0.86 0.86 0 0 0 7.15 8.79L7.15 7.18A2.03 2.03 0 0 1 9.18 5.15L14.29 5.15A2.56 2.56 0 0 1 16.85 7.71L16.85 11.79A0.86 0.86 0 0 0 17.71 12.65L19.33 12.65A2.03 2.03 0 0 1 21.35 14.68L21.35 18.79A2.56 2.56 0 0 1 18.79 21.35L5.21 21.35A2.56 2.56 0 0 1 2.65 18.79Z M16.7 18.9L15.3 18.9L15.3 15.1L16.7 15.1ZM8.7 18.9L7.3 18.9L7.3 12.1L8.7 12.1ZM12.9 15.5L11.5 15.5L11.5 9.9L12.9 9.9Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function PodiumSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
