// iconaut-react — point-down (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M15.3 12.4 L15.3 18.7 A1.6 1.6 180 0 1 12.1 18.7 L12.1 12.4\"/><path d=\"M15.3 12.4 L15.8 12.4 Q17.7 12.4 17.7 10.5 L17.7 6.7 Q17.7 3.7 14.7 3.7 L9.5 3.7 Q6.3 3.7 6.3 6.9 L6.3 10.3 Q6.3 12.4 8.4 12.4 L12.1 12.4\"/>";
const M1 = "<path d=\"M15.3 12.4 L15.3 18.7 A1.6 1.6 180 0 1 12.1 18.7 L12.1 12.4\"/><path d=\"M15.3 12.4 L15.8 12.4 Q17.7 12.4 17.7 10.5 L17.7 6.7 Q17.7 3.7 14.7 3.7 L9.5 3.7 Q6.3 3.7 6.3 6.9 L6.3 10.3 Q6.3 12.4 8.4 12.4 L12.1 12.4\"/><path d=\"M10.6 12.4 L 10.6 10.1\"/><path d=\"M8.4 12.4 L 8.4 9.9\"/><path d=\"M16.5 8.9 Q14.8 8.6 14.5 6.9\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function PointDown({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
