// iconaut-react — printer (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 11 Q4 9 6 9 L18 9 Q20 9 20 11 L20 16 Q20 18 18 18 L6 18 Q4 18 4 16 Z\"/><g class=\"primary\"><path d=\"M4 11 Q4 9 6 9 L18 9 Q20 9 20 11 L20 16 Q20 18 18 18 L6 18 Q4 18 4 16 Z\"/><path d=\"M7 9 L7 7 Q7 5 9 5 L15 5 Q17 5 17 7 L17 9\"/><path d=\"M7.5 13.5 L 16.5 13.5\"/><path d=\"M6.5 11.8 L 6.51 11.8\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3.5 10.5 Q3.5 8.5 5.5 8.5 L18.5 8.5 Q20.5 8.5 20.5 10.5 L20.5 16 Q20.5 18 18.5 18 L5.5 18 Q3.5 18 3.5 16 Z\"/><g class=\"primary\"><path d=\"M3.5 10.5 Q3.5 8.5 5.5 8.5 L18.5 8.5 Q20.5 8.5 20.5 10.5 L20.5 16 Q20.5 18 18.5 18 L5.5 18 Q3.5 18 3.5 16 Z\"/><path d=\"M6.5 8.5 L6.5 6.5 Q6.5 4.5 8.5 4.5 L15.5 4.5 Q17.5 4.5 17.5 6.5 L17.5 8.5\"/><path d=\"M7 13.5 L 17 13.5\"/><path d=\"M6.2 11.5 L 6.21 11.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function PrinterDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
