// iconaut-react — pyramid (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M13.43 3.91L21.03 18.26A1.76 1.76 0 0 1 19.48 20.84L4.52 20.84A1.76 1.76 0 0 1 2.97 18.26L10.57 3.91A1.62 1.62 0 0 1 13.43 3.91Z M13 7.03L13 19L11 19L11 7.03L12 5.14Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M13.43 3.9L21.04 18.27A1.75 1.75 0 0 1 19.49 20.84L4.51 20.84A1.75 1.75 0 0 1 2.96 18.27L10.57 3.9A1.62 1.62 0 0 1 13.43 3.9Z M13 7.03L13 19L11 19L11 7.03L12 5.14Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M13.44 3.9L21.04 18.26A1.76 1.76 0 0 1 19.48 20.85L4.52 20.85A1.76 1.76 0 0 1 2.96 18.26L10.56 3.9A1.63 1.63 0 0 1 13.44 3.9Z M13 7.03L13 19L11 19L11 7.03L12 5.14Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function PyramidSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
