// iconaut-react — radio (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 10 Q3 8 5 8 L19 8 Q21 8 21 10 L21 18 Q21 20 19 20 L5 20 Q3 20 3 18 Z\"/><path d=\"M7.3 8 L 16 3\"/><path d=\"M13.5 14 A2.3 2.3 0 1 0 18.1 14 A2.3 2.3 0 1 0 13.5 14 Z\"/><path d=\"M6 14 L 11.2 14\"/>";
const M1 = "<path d=\"M3 10 Q3 8 5 8 L19 8 Q21 8 21 10 L21 18 Q21 20 19 20 L5 20 Q3 20 3 18 Z\"/><path d=\"M7.3 8 L 16 3\"/><path d=\"M13.5 14 A2.3 2.3 0 1 0 18.1 14 A2.3 2.3 0 1 0 13.5 14 Z\"/><path d=\"M6 11.5 L 11.2 11.5\"/><path d=\"M6 16.5 L 11.2 16.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Radio({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
