// iconaut-react — rainbow (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M2 17 A10 10 0 0 1 22 17 L20 17 A8 8 0 0 0 4 17 Z M5.5 17 A6.5 6.5 0 0 1 18.5 17 L16.5 17 A4.5 4.5 0 0 0 7.5 17 Z M9 17 A3 3 0 0 1 15 17 L13 17 A1 1 0 0 0 11 17 Z\"/>";
const M1 = "<path d=\"M1.55 17 A10.45 10.45 0 0 1 22.45 17 L20.55 17 A8.55 8.55 0 0 0 3.45 17 Z M5.35 17 A6.65 6.65 0 0 1 18.65 17 L16.75 17 A4.75 4.75 0 0 0 7.25 17 Z M9.05 17 A2.95 2.95 0 0 1 14.95 17 L13.05 17 A1.05 1.05 0 0 0 10.95 17 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M1, null]
};
const S = [16, 20, 24];

export default function RainbowSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
