// iconaut-react — refresh (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5.5 11.5a6.5 6.5 0 1 0 13 0a6.5 6.5 0 1 0 -13 0\"/><g class=\"primary\"><path d=\"M18.5 11.5 A6.5 6.5 0 1 1 16.6 6.4 L18.25 7.75\"/><path d=\"M18.5 4 L18.5 7 Q18.5 8 17.5 8 L14.5 8\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 12a8 8 0 1 0 16 0a8 8 0 1 0 -16 0\"/><g class=\"primary\"><path d=\"M20 12 A8 8 0 1 1 17.66 6.34 L19.75 8.25\"/><path d=\"M20 3.5 L20 7.5 Q20 8.5 19 8.5 L15 8.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function RefreshDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
