// iconaut-react — ribbon-star (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6.36 9.18 A5.64 5.64 0 1 0 17.64 9.18 A5.64 5.64 0 1 0 6.36 9.18 Z\"/><path d=\"M11.71 7.83 Q12 7.08 12.3 7.83 L12.3 7.83 Q12.59 8.57 13.39 8.62 L13.39 8.62 Q14.19 8.67 13.57 9.18 L13.57 9.18 Q12.95 9.69 13.15 10.47 L13.15 10.47 Q13.35 11.24 12.68 10.81 L12.68 10.81 Q12 10.38 11.33 10.81 L11.33 10.81 Q10.65 11.24 10.85 10.47 L10.85 10.47 Q11.05 9.69 10.43 9.18 L10.43 9.18 Q9.81 8.67 10.61 8.62 L10.61 8.62 Q11.41 8.57 11.71 7.83 Z\"/><path d=\"M7.11 12 L4.77 16.07 Q3.92 17.54 5.61 17.43 L5.61 17.43 Q7.3 17.32 8.05 18.84 L8.05 18.84 Q8.8 20.36 9.65 18.89 L12 14.82 A5.64 5.64 0 0 1 7.11 12 Z\"/><path d=\"M12 14.82 L14.35 18.89 Q15.2 20.36 15.95 18.84 L15.95 18.84 Q16.7 17.32 18.39 17.43 L18.39 17.43 Q20.08 17.54 19.23 16.07 L16.89 12 A5.64 5.64 0 0 1 12 14.82 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function RibbonStar({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
