// iconaut-react — rosette (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 4.08 A1.45 1.45 0 0 1 14.55 4.76 A1.45 1.45 0 0 1 16.42 6.63 A1.45 1.45 0 0 1 17.1 9.18 A1.45 1.45 0 0 1 16.42 11.73 A1.45 1.45 0 0 1 14.55 13.6 A1.45 1.45 0 0 1 12 14.28 A1.45 1.45 0 0 1 9.45 13.6 A1.45 1.45 0 0 1 7.58 11.73 A1.45 1.45 0 0 1 6.9 9.18 A1.45 1.45 0 0 1 7.58 6.63 A1.45 1.45 0 0 1 9.45 4.76 A1.45 1.45 0 0 1 12 4.08 Z\"/><g class=\"primary\"><path d=\"M12 4.08 A1.45 1.45 0 0 1 14.55 4.76 A1.45 1.45 0 0 1 16.42 6.63 A1.45 1.45 0 0 1 17.1 9.18 A1.45 1.45 0 0 1 16.42 11.73 A1.45 1.45 0 0 1 14.55 13.6 A1.45 1.45 0 0 1 12 14.28 A1.45 1.45 0 0 1 9.45 13.6 A1.45 1.45 0 0 1 7.58 11.73 A1.45 1.45 0 0 1 6.9 9.18 A1.45 1.45 0 0 1 7.58 6.63 A1.45 1.45 0 0 1 9.45 4.76 A1.45 1.45 0 0 1 12 4.08 Z\"/><path d=\"M12 9.18 L 12.01 9.18\"/><path d=\"M9.45 13.6 L9.45 19.09 Q9.45 20.6 10.73 19.8 L10.73 19.8 Q12 19 13.28 19.8 L13.28 19.8 Q14.55 20.6 14.55 19.09 L14.55 13.6\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function RosetteDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
