// iconaut-react — route (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<circle cx=\"5\" cy=\"19\" r=\"1.8\"/><path d=\"M6.8 19 L14.5 19 A3.75 3.75 0 0 0 14.5 11.5 L9.5 11.5 A3.75 3.75 0 0 1 9.5 4 L17.2 4\"/><circle cx=\"19\" cy=\"4\" r=\"1.8\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Route({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
