// iconaut-react — satellite (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M11.29 9.88 Q12 9.17 12.71 9.88 L14.12 11.29 Q14.83 12 14.12 12.71 L12.71 14.12 Q12 14.83 11.29 14.12 L9.88 12.71 Q9.17 12 9.88 11.29 Z\"/><path d=\"M7.12 3.16 Q7.83 2.45 8.54 3.16 L9.95 4.57 Q10.66 5.28 9.95 5.99 L5.99 9.95 Q5.28 10.66 4.57 9.95 L3.16 8.54 Q2.45 7.83 3.16 7.12 Z\"/><path d=\"M18.01 14.05 Q18.72 13.34 19.43 14.05 L20.84 15.46 Q21.55 16.17 20.84 16.88 L16.88 20.84 Q16.17 21.55 15.46 20.84 L14.05 19.43 Q13.34 18.72 14.05 18.01 Z\"/><path d=\"M7.97 7.97 L 10.59 10.59 M13.41 13.41 L 16.03 16.03\"/><path d=\"M4.93 14.72 A5.8 5.8 0 0 0 9.28 19.07\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Satellite({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
