// iconaut-react — scooter (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 18 A2.5 2.5 0 1 0 8 18 A2.5 2.5 0 1 0 3 18 Z M15 18 A2.5 2.5 0 1 0 20 18 A2.5 2.5 0 1 0 15 18 Z\"/><g class=\"primary\"><path d=\"M3 18 A2.5 2.5 0 1 0 8 18 A2.5 2.5 0 1 0 3 18 Z\"/><path d=\"M15 18 A2.5 2.5 0 1 0 20 18 A2.5 2.5 0 1 0 15 18 Z\"/><path d=\"M8 18 L 15 18\"/><path d=\"M14 18 L 16.5 6\"/><path d=\"M13.5 6 L 19 6\"/><path d=\"M16.5 8 L 17.5 15.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function ScooterDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
