// iconaut-react — screen-share (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 6 Q3 4 5 4 L19 4 Q21 4 21 6 L21 14.5 Q21 16.5 19 16.5 L5 16.5 Q3 16.5 3 14.5 Z\"/><path d=\"M12 16.5 L 12 20 M8 20 L 16 20\"/><path d=\"M9.4 13.1 L 14.6 7.9\"/><path d=\"M10.6 7.9 L12.6 7.9 Q14.6 7.9 14.6 9.9 L14.6 11.9\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function ScreenShare({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
