// iconaut-react — send (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M20.38 5.69L14.85 19.12A1.53 1.53 0 0 1 11.99 19.07L10.32 14.54A3.13 3.13 0 0 0 8.46 12.68L3.9 11A1.46 1.46 0 0 1 3.95 8.24L18.34 3.49A1.65 1.65 0 0 1 20.38 5.69Z M18.54 5.96L18.04 7.18L12.13 12.68L12.01 12.76L11.88 12.8L11.73 12.81L11.6 12.78L11.47 12.71L11.41 12.65L11.28 12.52L11.16 12.19L11.09 12.06L10.99 11.94L10.81 11.84L10.59 11.76L10.57 11.73L10.53 11.6L10.52 11.46L10.55 11.32L10.62 11.19L10.68 11.12L16.38 5.82L17.93 5.31Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M20.24 5.63L14.7 19.06A1.38 1.38 0 0 1 12.14 19.01L10.47 14.49A3.29 3.29 0 0 0 8.51 12.53L3.96 10.86A1.31 1.31 0 0 1 4 8.39L18.39 3.64A1.49 1.49 0 0 1 20.24 5.63Z M17.7 5.3L18.45 6.1L18.52 6.2L18.53 6.24L18.35 6.68L12.02 12.56L11.92 12.63L11.81 12.66L11.69 12.65L11.58 12.6L11.52 12.54L10.77 11.74L10.7 11.65L10.68 11.53L10.69 11.41L10.73 11.3L10.79 11.24L16.9 5.55L17.7 5.29Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M20.74 5.13L14.89 19.56A1.37 1.37 0 0 1 12.34 19.52L10.58 14.79A3.43 3.43 0 0 0 8.61 12.79L3.44 10.77A1.32 1.32 0 0 1 3.5 8.28L18.89 3.15A1.49 1.49 0 0 1 20.74 5.13Z M18.23 4.85L19.05 5.73L18.77 6.41L12.12 12.71L12.03 12.77L11.92 12.8L11.81 12.78L11.69 12.7L10.87 11.82L10.81 11.73L10.78 11.62L10.8 11.51L10.88 11.39L17.65 4.98L18.17 4.81Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M20.75 5.13L14.9 19.56A1.38 1.38 0 0 1 12.33 19.52L10.57 14.79A3.41 3.41 0 0 0 8.61 12.79L3.44 10.78A1.33 1.33 0 0 1 3.5 8.27L18.88 3.14A1.5 1.5 0 0 1 20.75 5.13Z M18.24 4.85L19.05 5.71L18.75 6.45L12.13 12.72L12.03 12.78L11.92 12.81L11.81 12.79L11.68 12.71L10.86 11.83L10.8 11.73L10.77 11.62L10.79 11.51L10.87 11.38L17.61 5L18.18 4.81Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function SendSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
