// iconaut-react — shelf (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4 5.4 Q4 3.4 6 3.4 L18 3.4 Q20 3.4 20 5.4 L20 9 Q20 11 18 11 L6 11 Q4 11 4 9 Z\"/><g class=\"primary\"><path d=\"M4 5.4 Q4 3.4 6 3.4 L18 3.4 Q20 3.4 20 5.4 L20 18.6 Q20 20.6 18 20.6 L6 20.6 Q4 20.6 4 18.6 Z\"/><path d=\"M4 11 L 20 11 M4 16 L 20 16\"/><path d=\"M7.7 11 L 7.7 7 M11.4 11 L 11.4 7.8\"/><path d=\"M15.1 11 L 16.2 7.9\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function ShelfDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
