// iconaut-react — shield-lock (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M12 2.9 C14.1 4.4 16.6 5.35 19.4 5.6 L19.4 11.9 C19.4 16.6 16.5 19.7 12 21.1 C7.5 19.7 4.6 16.6 4.6 11.9 L4.6 5.6 C7.4 5.35 9.9 4.4 12 2.9 Z\"/><path d=\"M10.4 10.5 A1.6 1.6 0 1 0 13.6 10.5 A1.6 1.6 0 1 0 10.4 10.5 Z\"/><path d=\"M12 11.9 L 12 14.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function ShieldLock({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
