// iconaut-react — shower (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M6.13 9.75 Q7 8 8.96 8 L15.04 8 Q17 8 17.88 9.75 L17.88 9.75 Q18.75 11.5 16.79 11.5 L7.21 11.5 Q5.25 11.5 6.13 9.75 Z\"/><path d=\"M12 8 L12 6 Q12 4 10 4 L6.5 4\"/><path d=\"M9 15.5 L 9 17.5 M15 15.5 L 15 17.5\"/>";
const M1 = "<path d=\"M6.13 9.75 Q7 8 8.96 8 L15.04 8 Q17 8 17.88 9.75 L17.88 9.75 Q18.75 11.5 16.79 11.5 L7.21 11.5 Q5.25 11.5 6.13 9.75 Z\"/><path d=\"M12 8 L12 6 Q12 4 10 4 L6.5 4\"/><path d=\"M7.5 15.5 L 7.5 17.5 M12 17 L 12 19 M16.5 15.5 L 16.5 17.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function Shower({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
