// iconaut-react — signal (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3.5 20 L 3.5 16.5\"/><path d=\"M8.5 20 L 8.5 12.5\"/><path d=\"M13.5 20 L 13.5 8.5\"/><path d=\"M18.5 20 L 18.5 4.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function SignalDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
