// iconaut-react — signpost (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M6.7 5.56L14.58 5.56A5.58 5.58 0 0 1 18.52 7.19L19.06 7.73A2.51 2.51 0 0 1 19.06 11.27L18.52 11.81A5.58 5.58 0 0 1 14.58 13.44L6.7 13.44A2.64 2.64 0 0 1 4.06 10.8L4.06 8.2A2.64 2.64 0 0 1 6.7 5.56Z\"/><path d=\"M11.2 4.3 Q11.2 3.5 12 3.5 L12 3.5 Q12.8 3.5 12.8 4.3 L12.8 5.7 Q12.8 6.5 12 6.5 L12 6.5 Q11.2 6.5 11.2 5.7 Z M11.2 13.3 Q11.2 12.5 12 12.5 L12 12.5 Q12.8 12.5 12.8 13.3 L12.8 19.7 Q12.8 20.5 12 20.5 L12 20.5 Q11.2 20.5 11.2 19.7 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M6.71 5.6L14.57 5.6A5.54 5.54 0 0 1 18.49 7.22L19.02 7.75A2.48 2.48 0 0 1 19.02 11.26L18.49 11.78A5.54 5.54 0 0 1 14.57 13.4L6.71 13.4A2.61 2.61 0 0 1 4.1 10.79L4.1 8.21A2.61 2.61 0 0 1 6.71 5.6Z\"/><path d=\"M11.2 4.3 Q11.2 3.5 12 3.5 L12 3.5 Q12.8 3.5 12.8 4.3 L12.8 5.7 Q12.8 6.5 12 6.5 L12 6.5 Q11.2 6.5 11.2 5.7 Z M11.2 13.3 Q11.2 12.5 12 12.5 L12 12.5 Q12.8 12.5 12.8 13.3 L12.8 19.7 Q12.8 20.5 12 20.5 L12 20.5 Q11.2 20.5 11.2 19.7 Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M6.71 5.63L14.57 5.63A5.53 5.53 0 0 1 18.48 7.24L18.99 7.76A2.46 2.46 0 0 1 19 11.24L18.48 11.76A5.52 5.52 0 0 1 14.57 13.38L6.71 13.38A2.58 2.58 0 0 1 4.13 10.8L4.13 8.21A2.58 2.58 0 0 1 6.71 5.63Z\"/><path d=\"M11.2 4.3 Q11.2 3.5 12 3.5 L12 3.5 Q12.8 3.5 12.8 4.3 L12.8 5.7 Q12.8 6.5 12 6.5 L12 6.5 Q11.2 6.5 11.2 5.7 Z M11.2 13.3 Q11.2 12.5 12 12.5 L12 12.5 Q12.8 12.5 12.8 13.3 L12.8 19.7 Q12.8 20.5 12 20.5 L12 20.5 Q11.2 20.5 11.2 19.7 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function SignpostSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
