// iconaut-react — ski (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M15.9 3.7 L 15.91 3.7\"/><path d=\"M13.8 6.9 L10.84 10.43 Q10.2 11.2 10.91 11.91 L12.69 13.69 Q13.4 14.4 12.98 15.31 L11.6 18.33\"/><path d=\"M13.8 6.9 L16.03 8.76 Q16.8 9.4 17.79 9.56 L19.2 9.8\"/><path d=\"M13.8 6.9 L10.3 8.57 Q9.4 9 8.93 9.88 L8.07 11.52 Q7.6 12.4 7.18 13.31 L5 18\"/><path d=\"M3.4 15.4 L17.4 20.4 C18.6 20.8 19.6 20.4 20.2 19.4\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function SkiDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
