// iconaut-react — skip-back (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M18.5 6 Q18.5 5 17.71 5.61 L10.29 11.39 Q9.5 12 10.29 12.61 L17.71 18.39 Q18.5 19 18.5 18 Z\"/><path d=\"M6 5 L 6 19\"/>";
const M1 = "<path d=\"M19 5.5 Q19 4.5 18.22 5.12 L10.28 11.38 Q9.5 12 10.28 12.62 L18.22 18.88 Q19 19.5 19 18.5 Z\"/><path d=\"M5.5 4.5 L 5.5 19.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function SkipBack({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
