// iconaut-react — sliders (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6.1 8a1.9 1.9 0 1 0 3.8 0a1.9 1.9 0 1 0 -3.8 0M14.1 16a1.9 1.9 0 1 0 3.8 0a1.9 1.9 0 1 0 -3.8 0\"/><g class=\"primary\"><path d=\"M3 8 L 6.1 8 M9.9 8 L 21 8\"/><circle cx=\"8\" cy=\"8\" r=\"1.9\"/><path d=\"M3 16 L 14.1 16 M17.9 16 L 21 16\"/><circle cx=\"16\" cy=\"16\" r=\"1.9\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M6 8a2 2 0 1 0 4 0a2 2 0 1 0 -4 0M14 16a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\"/><g class=\"primary\"><path d=\"M3 8 L 6 8 M10 8 L 21 8\"/><circle cx=\"8\" cy=\"8\" r=\"2\"/><path d=\"M3 16 L 14 16 M18 16 L 21 16\"/><circle cx=\"16\" cy=\"16\" r=\"2\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function SlidersDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
