// iconaut-react — snail (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M8.5 11 A5.5 5.5 0 1 0 19.5 11 A5.5 5.5 0 1 0 8.5 11 Z\"/><path d=\"M14 11 A2.5 2.5 0 0 1 16.5 13.5\"/><path d=\"M8.5 12.5 A4 4 0 0 0 5 18.5 L16 18.5 A2 2 0 0 0 16 14.5\"/><path d=\"M5 18.5 L 3.5 21\"/><path d=\"M6 15 L 4 13\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Snail({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
