// iconaut-react — snail (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3.8 11.6 A6.6 6.6 0 1 0 17 11.6 A6.6 6.6 0 1 0 3.8 11.6 Z\"/><g class=\"primary\"><path d=\"M2.6 18.2 L16.8 18.2 C19.2 18.2 21 16.6 21 14.2 L21 10.6 A1.9 1.9 0 0 0 17.2 10.6 L17.2 12.92 Q17.2 13.1 17.02 13.1 L16.83 13.1 A6.6 6.6 0 1 0 4.03 13.31 C3.4 14.8 3 16.6 2.6 18.2 Z\"/><path d=\"M4.03 13.31 A6.6 6.6 0 0 0 16.83 13.1\"/><path d=\"M3.8 11.6 A4.95 4.95 0 0 0 13.7 11.6 A3.3 3.3 0 0 0 7.1 11.6 A1.65 1.65 0 0 0 10.4 11.6\"/><path d=\"M17.2 6.2 L18.15 7.45 Q19.1 8.7 20.05 7.45 L21 6.2\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function SnailDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
