// iconaut-react — sofa (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5.5 17 Q3.5 17 3.5 15 L3.5 10.5 Q3.5 9 5 9 L5 9 Q6.5 9 6.5 7.5 L6.5 7.5 Q6.5 6 8 6 L16 6 Q17.5 6 17.5 7.5 L17.5 7.5 Q17.5 9 19 9 L19 9 Q20.5 9 20.5 10.5 L20.5 15 Q20.5 17 18.5 17 Z\"/><g class=\"primary\"><path d=\"M5.5 17 Q3.5 17 3.5 15 L3.5 10.5 Q3.5 9 5 9 L5 9 Q6.5 9 6.5 7.5 L6.5 7.5 Q6.5 6 8 6 L16 6 Q17.5 6 17.5 7.5 L17.5 7.5 Q17.5 9 19 9 L19 9 Q20.5 9 20.5 10.5 L20.5 15 Q20.5 17 18.5 17 Z\"/><path d=\"M3.5 13 L 20.5 13\"/><path d=\"M6 17 L 6 19 M18 17 L 18 19\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5.5 17 Q3.5 17 3.5 15 L3.5 10.5 Q3.5 9 5 9 L5 9 Q6.5 9 6.5 7.5 L6.5 7.5 Q6.5 6 8 6 L16 6 Q17.5 6 17.5 7.5 L17.5 7.5 Q17.5 9 19 9 L19 9 Q20.5 9 20.5 10.5 L20.5 15 Q20.5 17 18.5 17 Z\"/><g class=\"primary\"><path d=\"M5.5 17 Q3.5 17 3.5 15 L3.5 10.5 Q3.5 9 5 9 L5 9 Q6.5 9 6.5 7.5 L6.5 7.5 Q6.5 6 8 6 L16 6 Q17.5 6 17.5 7.5 L17.5 7.5 Q17.5 9 19 9 L19 9 Q20.5 9 20.5 10.5 L20.5 15 Q20.5 17 18.5 17 Z\"/><path d=\"M3.5 13 L 20.5 13\"/><path d=\"M12 13 L 12 17\"/><path d=\"M6 17 L 6 19 M18 17 L 18 19\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function SofaDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
