// iconaut-react — sparkle (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M11.3 5.38 Q12 3.5 12.7 5.38 L13.6 7.82 Q14.3 9.7 16.18 10.4 L18.62 11.3 Q20.5 12 18.62 12.7 L16.18 13.6 Q14.3 14.3 13.6 16.18 L12.7 18.62 Q12 20.5 11.3 18.62 L10.4 16.18 Q9.7 14.3 7.82 13.6 L5.38 12.7 Q3.5 12 5.38 11.3 L7.82 10.4 Q9.7 9.7 10.4 7.82 Z\"/><g class=\"primary\"><path d=\"M11.3 5.38 Q12 3.5 12.7 5.38 L13.6 7.82 Q14.3 9.7 16.18 10.4 L18.62 11.3 Q20.5 12 18.62 12.7 L16.18 13.6 Q14.3 14.3 13.6 16.18 L12.7 18.62 Q12 20.5 11.3 18.62 L10.4 16.18 Q9.7 14.3 7.82 13.6 L5.38 12.7 Q3.5 12 5.38 11.3 L7.82 10.4 Q9.7 9.7 10.4 7.82 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function SparkleDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
