// iconaut-react — speaker (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 5 Q5.5 3 7.5 3 L16.5 3 Q18.5 3 18.5 5 L18.5 19 Q18.5 21 16.5 21 L7.5 21 Q5.5 21 5.5 19 Z\"/><path d=\"M8.5 15 A3.5 3.5 0 1 0 15.5 15 A3.5 3.5 0 1 0 8.5 15 Z\"/><path d=\"M12 6.5 L 12.01 6.5\"/>";
const M1 = "<path d=\"M5 4.5 Q5 2.5 7 2.5 L17 2.5 Q19 2.5 19 4.5 L19 19.5 Q19 21.5 17 21.5 L7 21.5 Q5 21.5 5 19.5 Z\"/><path d=\"M8.2 15 A3.8 3.8 0 1 0 15.8 15 A3.8 3.8 0 1 0 8.2 15 Z\"/><path d=\"M12 6.5 L 12.01 6.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function Speaker({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
