// iconaut-react — spray-can (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M10 8 L14 8 Q16 8 16 10 L16 20 A1 1 0 0 1 15 21 L9 21 A1 1 0 0 1 8 20 L8 10 Q8 8 10 8 Z M9 6.5 Q9 5 10.5 5 L13.5 5 Q15 5 15 6.5 L15 6.5 Q15 8 13.5 8 L10.5 8 Q9 8 9 6.5 Z\"/><g class=\"primary\"><path d=\"M9 8 L15 8 Q16 8 16 9 L16 20 A1 1 0 0 1 15 21 L9 21 A1 1 0 0 1 8 20 L8 9 Q8 8 9 8 Z\"/><path d=\"M9 6 Q9 5 10 5 L14 5 Q15 5 15 6 L15 7 Q15 8 14 8 L10 8 Q9 8 9 7 Z\"/><path d=\"M12 3 L13 3 Q14 3 14 4 L14 5\"/><path d=\"M17 4 L 17.01 4 M19 3 L 19.01 3 M18 6 L 18.01 6\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function SprayCanDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
