// iconaut-react — square (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M5.71 3.16L18.29 3.16A2.55 2.55 0 0 1 20.84 5.71L20.84 18.29A2.55 2.55 0 0 1 18.29 20.84L5.71 20.84A2.55 2.55 0 0 1 3.16 18.29L3.16 5.71A2.55 2.55 0 0 1 5.71 3.16Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M5.71 3.15L18.29 3.15A2.56 2.56 0 0 1 20.85 5.71L20.85 18.29A2.56 2.56 0 0 1 18.29 20.85L5.71 20.85A2.56 2.56 0 0 1 3.15 18.29L3.15 5.71A2.56 2.56 0 0 1 5.71 3.15Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M0, null],
  24: [M1, null]
};
const S = [16, 20, 24];

export default function SquareSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
