// iconaut-react — stairs (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M3.06 20L3.06 17.28A2.22 2.22 0 0 1 5.28 15.06L7.29 15.06A0.77 0.77 0 0 0 8.06 14.29L8.06 12.86A1.8 1.8 0 0 1 9.86 11.06L12.29 11.06A0.77 0.77 0 0 0 13.06 10.29L13.06 8.86A1.8 1.8 0 0 1 14.86 7.06L17.29 7.06A0.77 0.77 0 0 0 18.06 6.29L18.06 4.81A1.75 1.75 0 0 1 19.81 3.06L20.19 3.06A1.75 1.75 0 0 1 21.94 4.81L21.94 20.3A2.64 2.64 0 0 1 19.3 22.94L4.38 22.94A1.32 1.32 0 0 1 3.06 21.62L3.06 20Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M3.1 20L3.1 17.31A2.21 2.21 0 0 1 5.31 15.1L7.29 15.1A0.81 0.81 0 0 0 8.1 14.29L8.1 12.9A1.8 1.8 0 0 1 9.9 11.1L12.29 11.1A0.81 0.81 0 0 0 13.1 10.29L13.1 8.9A1.8 1.8 0 0 1 14.9 7.1L17.29 7.1A0.81 0.81 0 0 0 18.1 6.29L18.1 4.81A1.71 1.71 0 0 1 19.81 3.1L20.19 3.1A1.71 1.71 0 0 1 21.9 4.81L21.9 20.29A2.61 2.61 0 0 1 19.29 22.9L4.4 22.9A1.3 1.3 0 0 1 3.1 21.6L3.1 20Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M3.13 20L3.13 17.32A2.19 2.19 0 0 1 5.32 15.13L7.3 15.13A0.83 0.83 0 0 0 8.13 14.3L8.13 12.93A1.8 1.8 0 0 1 9.93 11.13L12.3 11.13A0.83 0.83 0 0 0 13.13 10.3L13.13 8.93A1.8 1.8 0 0 1 14.93 7.13L17.3 7.13A0.83 0.83 0 0 0 18.13 6.3L18.13 4.82A1.69 1.69 0 0 1 19.82 3.13L20.19 3.13A1.69 1.69 0 0 1 21.88 4.82L21.88 20.3A2.58 2.58 0 0 1 19.3 22.88L4.43 22.88A1.3 1.3 0 0 1 3.13 21.58L3.13 20Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function StairsSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
