// iconaut-react — stairs (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M3 20L3 17.25A2.25 2.25 0 0 1 5.25 15L7.29 15A0.71 0.71 0 0 0 8 14.29L8 12.8A1.8 1.8 0 0 1 9.8 11L12.29 11A0.71 0.71 0 0 0 13 10.29L13 8.8A1.8 1.8 0 0 1 14.8 7L17.29 7A0.71 0.71 0 0 0 18 6.29L18 4.8A1.8 1.8 0 0 1 19.8 3L20.2 3A1.8 1.8 0 0 1 22 4.8L22 20.29A2.71 2.71 0 0 1 19.29 23L4.35 23A1.35 1.35 0 0 1 3 21.65L3 20Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M3.16 20L3.16 17.34A2.18 2.18 0 0 1 5.34 15.16L7.3 15.16A0.86 0.86 0 0 0 8.16 14.3L8.16 12.96A1.8 1.8 0 0 1 9.96 11.16L12.3 11.16A0.86 0.86 0 0 0 13.16 10.3L13.16 8.96A1.8 1.8 0 0 1 14.96 7.16L17.3 7.16A0.86 0.86 0 0 0 18.16 6.3L18.16 4.82A1.66 1.66 0 0 1 19.82 3.16L20.18 3.16A1.66 1.66 0 0 1 21.84 4.82L21.84 20.29A2.55 2.55 0 0 1 19.29 22.84L4.44 22.84A1.28 1.28 0 0 1 3.16 21.56L3.16 20Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M3.16 20L3.16 17.34A2.18 2.18 0 0 1 5.34 15.16L7.29 15.16A0.87 0.87 0 0 0 8.16 14.29L8.16 12.96A1.8 1.8 0 0 1 9.96 11.16L12.29 11.16A0.87 0.87 0 0 0 13.16 10.29L13.16 8.96A1.8 1.8 0 0 1 14.96 7.16L17.29 7.16A0.87 0.87 0 0 0 18.16 6.29L18.16 4.82A1.66 1.66 0 0 1 19.82 3.16L20.18 3.16A1.66 1.66 0 0 1 21.84 4.82L21.84 20.29A2.55 2.55 0 0 1 19.29 22.84L4.44 22.84A1.28 1.28 0 0 1 3.16 21.56L3.16 20Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M3.15 20L3.15 17.33A2.18 2.18 0 0 1 5.33 15.15L7.29 15.15A0.86 0.86 0 0 0 8.15 14.29L8.15 12.95A1.8 1.8 0 0 1 9.95 11.15L12.29 11.15A0.86 0.86 0 0 0 13.15 10.29L13.15 8.95A1.8 1.8 0 0 1 14.95 7.15L17.29 7.15A0.86 0.86 0 0 0 18.15 6.29L18.15 4.82A1.67 1.67 0 0 1 19.82 3.15L20.18 3.15A1.67 1.67 0 0 1 21.85 4.82L21.85 20.29A2.56 2.56 0 0 1 19.29 22.85L4.43 22.85A1.28 1.28 0 0 1 3.15 21.57L3.15 20Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function StairsSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
