// iconaut-react — stop (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5.5 7.5 Q5.5 5.5 7.5 5.5 L16.5 5.5 Q18.5 5.5 18.5 7.5 L18.5 16.5 Q18.5 18.5 16.5 18.5 L7.5 18.5 Q5.5 18.5 5.5 16.5 Z\"/><g class=\"primary\"><path d=\"M5.5 7.5 Q5.5 5.5 7.5 5.5 L16.5 5.5 Q18.5 5.5 18.5 7.5 L18.5 16.5 Q18.5 18.5 16.5 18.5 L7.5 18.5 Q5.5 18.5 5.5 16.5 Z\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5 7 Q5 5 7 5 L17 5 Q19 5 19 7 L19 17 Q19 19 17 19 L7 19 Q5 19 5 17 Z\"/><g class=\"primary\"><path d=\"M5 7 Q5 5 7 5 L17 5 Q19 5 19 7 L19 17 Q19 19 17 19 L7 19 Q5 19 5 17 Z\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function StopDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
