// iconaut-react — strawberry (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 20.6 C8.5 20.6 4.5 16.1 4.5 11.8 C4.5 9.3 6.3 7.6 8.6 7.6 L15.4 7.6 C17.7 7.6 19.5 9.3 19.5 11.8 C19.5 16.1 15.5 20.6 12 20.6 Z\"/><g class=\"primary\"><path d=\"M12 20.6 C8.5 20.6 4.5 16.1 4.5 11.8 C4.5 9.3 6.3 7.6 8.6 7.6 L15.4 7.6 C17.7 7.6 19.5 9.3 19.5 11.8 C19.5 16.1 15.5 20.6 12 20.6 Z\"/><path d=\"M12 7.6 C10.5 5 7.4 5 5.91 8.55\"/><path d=\"M12 7.6 C13.5 5 16.6 5 18.09 8.55\"/><path d=\"M12 7.6 L 12 3.4\"/><path d=\"M9.2 12.1 L 9.21 12.1 M14.8 12.1 L 14.81 12.1 M12 15.6 L 12.01 15.6\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 20.6 C8.5 20.6 4.5 16.1 4.5 11.8 C4.5 9.3 6.3 7.6 8.6 7.6 L15.4 7.6 C17.7 7.6 19.5 9.3 19.5 11.8 C19.5 16.1 15.5 20.6 12 20.6 Z\"/><g class=\"primary\"><path d=\"M12 20.6 C8.5 20.6 4.5 16.1 4.5 11.8 C4.5 9.3 6.3 7.6 8.6 7.6 L15.4 7.6 C17.7 7.6 19.5 9.3 19.5 11.8 C19.5 16.1 15.5 20.6 12 20.6 Z\"/><path d=\"M12 7.6 C10.5 5 7.4 5 5.91 8.55\"/><path d=\"M12 7.6 C13.5 5 16.6 5 18.09 8.55\"/><path d=\"M12 7.6 L 12 3.4\"/><path d=\"M8.3 11.4 L 8.31 11.4 M12 11.4 L 12.01 11.4 M15.7 11.4 L 15.71 11.4 M10.15 14.9 L 10.16 14.9 M13.85 14.9 L 13.86 14.9\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function StrawberryDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
