// iconaut-react — sun-medium (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7 12 A5 5 0 1 0 17 12 A5 5 0 1 0 7 12 Z\"/><path d=\"M12 2.5 L 12 4 M12 20 L 12 21.5 M2.5 12 L 4 12 M20 12 L 21.5 12 M4.9 4.9 L 5.9 5.9 M18.1 18.1 L 19.1 19.1 M4.9 19.1 L 5.9 18.1 M18.1 5.9 L 19.1 4.9\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function SunMedium({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
