// iconaut-react — surfboard (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M12 2.9 C15.4 5.4 17.2 9.3 17.2 12.9 C17.2 16.6 15.3 19.9 12 21.1 C8.7 19.9 6.8 16.6 6.8 12.9 C6.8 9.3 8.6 5.4 12 2.9 Z\"/><g class=\"primary\"><path d=\"M12 2.9 C15.4 5.4 17.2 9.3 17.2 12.9 C17.2 16.6 15.3 19.9 12 21.1 C8.7 19.9 6.8 16.6 6.8 12.9 C6.8 9.3 8.6 5.4 12 2.9 Z\"/><path d=\"M12 7 L 12 17\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function SurfboardDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
