// iconaut-react — sword (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M18.06 4.06L18.49 4.06A1.95 1.95 0 0 1 20.44 6.01L20.44 6.44A4.7 4.7 0 0 1 19.06 9.77L11.87 16.96A2.64 2.64 0 0 1 8.13 16.96L7.54 16.37A2.64 2.64 0 0 1 7.54 12.63L14.73 5.44A4.7 4.7 0 0 1 18.06 4.06Z\"/><path d=\"M11.5 17.58 Q12.21 18.29 11.5 19 L11.5 19 Q10.79 19.71 10.08 19 L9.65 18.57 Q8.5 17.42 7.36 18.57 L6.42 19.5 Q5.71 20.21 5 19.5 L5 19.5 Q4.29 18.79 5 18.08 L5.94 17.15 Q7.08 16 5.94 14.86 L5.5 14.42 Q4.79 13.71 5.5 13 L5.5 13 Q6.21 12.29 6.92 13 Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M18.05 4.1L18.48 4.1A1.92 1.92 0 0 1 20.4 6.02L20.4 6.45A4.64 4.64 0 0 1 19.04 9.73L11.84 16.93A2.61 2.61 0 0 1 8.16 16.93L7.57 16.34A2.61 2.61 0 0 1 7.57 12.66L14.77 5.46A4.64 4.64 0 0 1 18.05 4.1Z\"/><path d=\"M11.5 17.58 Q12.21 18.29 11.5 19 L11.5 19 Q10.79 19.71 10.08 19 L9.65 18.57 Q8.5 17.42 7.36 18.57 L6.42 19.5 Q5.71 20.21 5 19.5 L5 19.5 Q4.29 18.79 5 18.08 L5.94 17.15 Q7.08 16 5.94 14.86 L5.5 14.42 Q4.79 13.71 5.5 13 L5.5 13 Q6.21 12.29 6.92 13 Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M18.05 4.13L18.48 4.13A1.9 1.9 0 0 1 20.38 6.03L20.38 6.46A4.6 4.6 0 0 1 19.03 9.71L11.83 16.91A2.58 2.58 0 0 1 8.17 16.91L7.59 16.33A2.58 2.58 0 0 1 7.59 12.67L14.79 5.48A4.61 4.61 0 0 1 18.05 4.13Z\"/><path d=\"M11.5 17.58 Q12.21 18.29 11.5 19 L11.5 19 Q10.79 19.71 10.08 19 L9.65 18.57 Q8.5 17.42 7.36 18.57 L6.42 19.5 Q5.71 20.21 5 19.5 L5 19.5 Q4.29 18.79 5 18.08 L5.94 17.15 Q7.08 16 5.94 14.86 L5.5 14.42 Q4.79 13.71 5.5 13 L5.5 13 Q6.21 12.29 6.92 13 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function SwordSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
