// iconaut-react — sword (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M15.44 6.06 Q16.5 5 18 5 L18 5 Q19.5 5 19.5 6.5 L19.5 6.5 Q19.5 8 18.44 9.06 L11.41 16.09 Q10 17.5 8.59 16.09 L8.41 15.91 Q7 14.5 8.41 13.09 Z\"/><g class=\"primary\"><path d=\"M15.44 6.06 Q16.5 5 18 5 L18 5 Q19.5 5 19.5 6.5 L19.5 6.5 Q19.5 8 18.44 9.06 L11.41 16.09 Q10 17.5 8.59 16.09 L8.41 15.91 Q7 14.5 8.41 13.09 Z\"/><path d=\"M5.5 13 L 11.5 19\"/><path d=\"M8.5 16 L 5 19.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function SwordDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
