// iconaut-react — syringe (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M22 12 L 19 12\"/><path d=\"M19 9 L 19 15\"/><path d=\"M9 9 L 9 15\"/><path d=\"M9 10 L 19 10 M9 14 L 19 14 M19 10 L 19 14\"/><path d=\"M15 10.5 L 15 13.5 M13 10.5 L 13 13.5 M11 10.5 L 11 13.5\"/><path d=\"M9 12 L 3 12\"/><path d=\"M4 10 L3.45 11.11 Q3 12 3.45 12.89 L4 14\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function Syringe({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
