// iconaut-react — tablet (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5 5.5 Q5 3.5 7 3.5 L17 3.5 Q19 3.5 19 5.5 L19 18.5 Q19 20.5 17 20.5 L7 20.5 Q5 20.5 5 18.5 Z\"/><g class=\"primary\"><path d=\"M5 5.5 Q5 3.5 7 3.5 L17 3.5 Q19 3.5 19 5.5 L19 18.5 Q19 20.5 17 20.5 L7 20.5 Q5 20.5 5 18.5 Z\"/><path d=\"M12 17.7 L 12.01 17.7\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M4.5 5 Q4.5 3 6.5 3 L17.5 3 Q19.5 3 19.5 5 L19.5 19 Q19.5 21 17.5 21 L6.5 21 Q4.5 21 4.5 19 Z\"/><g class=\"primary\"><path d=\"M4.5 5 Q4.5 3 6.5 3 L17.5 3 Q19.5 3 19.5 5 L19.5 19 Q19.5 21 17.5 21 L6.5 21 Q4.5 21 4.5 19 Z\"/><path d=\"M12 18 L 12.01 18\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function TabletDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
