// iconaut-react — tag-off (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M11.2 6.5 Q9.2 6.5 7.9 8.02 L5.8 10.48 Q4.5 12 5.8 13.52 L7.9 15.98 Q9.2 17.5 11.2 17.5 L17.5 17.5 Q19.5 17.5 19.5 15.5 L19.5 8.5 Q19.5 6.5 17.5 6.5 Z\"/><g class=\"primary\"><path d=\"M5.68 10.63Q4.56 12.07 5.8 13.52L7.9 15.98Q9.2 17.5 11.2 17.5L12.55 17.5M17.5 17.5Q19.5 17.5 19.5 15.5L19.5 8.5Q19.5 6.5 17.5 6.5L11.2 6.5Q9.24 6.5 7.96 7.96\"/><path d=\"M8.9 12L8.91 12\"/><path d=\"M3.75 3.75L20.25 20.25\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M11.2 6.5 Q9.2 6.5 7.9 8.02 L5.8 10.48 Q4.5 12 5.8 13.52 L7.9 15.98 Q9.2 17.5 11.2 17.5 L17.5 17.5 Q19.5 17.5 19.5 15.5 L19.5 8.5 Q19.5 6.5 17.5 6.5 Z\"/><g class=\"primary\"><path d=\"M5.88 10.39L5.8 10.48Q4.5 12 5.8 13.52L7.9 15.98Q9.2 17.5 11.2 17.5L12.99 17.5M17.5 17.5Q19.5 17.5 19.5 15.5L19.5 8.5Q19.5 6.5 17.5 6.5L11.2 6.5Q9.24 6.5 7.96 7.96\"/><path d=\"M8.9 12L8.91 12\"/><path d=\"M3.75 3.75L20.25 20.25\"/></g>";
const M2 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M11 6 Q9 6 7.72 7.54 L5.28 10.46 Q4 12 5.28 13.54 L7.72 16.46 Q9 18 11 18 L18 18 Q20 18 20 16 L20 8 Q20 6 18 6 Z\"/><g class=\"primary\"><path d=\"M5.59 10.09L5.28 10.46Q4 12 5.28 13.54L7.72 16.46Q9 18 11 18L13.5 18M18 18Q20 18 20 16L20 8Q20 6 18 6L11 6Q9 6 7.72 7.54L7.64 7.64\"/><path d=\"M8.7 12L8.71 12\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
const M3 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M11 6 Q9 6 7.72 7.54 L5.28 10.46 Q4 12 5.28 13.54 L7.72 16.46 Q9 18 11 18 L18 18 Q20 18 20 16 L20 8 Q20 6 18 6 Z\"/><g class=\"primary\"><path d=\"M5.58 10.1L5.28 10.46Q4 12 5.28 13.54L7.72 16.46Q9 18 11 18L13.47 18M18 18Q20 18 20 16L20 8Q20 6 18 6L11 6Q9 6 7.72 7.54L7.64 7.64\"/><path d=\"M8.7 12L8.71 12\"/><path d=\"M3.5 3.5L20.5 20.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M1, 1.688],
  20: [M2, 1.68],
  24: [M3, 1.7]
};
const S = [12, 16, 20, 24];

export default function TagOffDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
