// iconaut-react — tag-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.76 10.53Q4.52 12.03 5.8 13.52L7.9 15.98Q9.2 17.5 11.2 17.5L12.73 17.5M17.5 17.5Q19.5 17.5 19.5 15.5L19.5 8.5Q19.5 6.5 17.5 6.5L11.2 6.5Q9.24 6.5 7.96 7.96\"/><path d=\"M8.9 12L8.91 12\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M5.51 10.18L5.28 10.46Q4 12 5.28 13.54L7.72 16.46Q9 18 11 18L13.33 18M18 18Q20 18 20 16L20 8Q20 6 18 6L11 6Q9 6 7.72 7.54L7.64 7.64\"/><path d=\"M8.7 12L8.71 12\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M2 = "<path d=\"M5.55 10.14L5.28 10.46Q4 12 5.28 13.54L7.72 16.46Q9 18 11 18L13.4 18M18 18Q20 18 20 16L20 8Q20 6 18 6L11 6Q9 6 7.72 7.54L7.64 7.64\"/><path d=\"M8.7 12L8.71 12\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M2, 1.75]
};
const S = [16, 20, 24];

export default function TagOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
