// iconaut-react — tag (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M11.2 6.5 Q9.2 6.5 7.9 8.02 L5.8 10.48 Q4.5 12 5.8 13.52 L7.9 15.98 Q9.2 17.5 11.2 17.5 L17.5 17.5 Q19.5 17.5 19.5 15.5 L19.5 8.5 Q19.5 6.5 17.5 6.5 Z\"/><path d=\"M8.9 12 L 8.91 12\"/>";
const M1 = "<path d=\"M11 6 Q9 6 7.72 7.54 L5.28 10.46 Q4 12 5.28 13.54 L7.72 16.46 Q9 18 11 18 L18 18 Q20 18 20 16 L20 8 Q20 6 18 6 Z\"/><path d=\"M8.7 12 L 8.71 12\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Tag({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
