// iconaut-react — telegram (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z M13.96 8.95L7.87 11.43A0.8 0.8 0 0 0 7.89 12.92L9.3 13.46A2 2 0 0 1 10.49 14.72L11.4 17.6L13.38 15.15A2 2 0 0 0 13.59 14.83L15.7 10.88A1.38 1.38 0 0 0 13.96 8.95Z\"/><g class=\"primary\"><path d=\"M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z\"/><path d=\"M16.56 9.26 Q17.5 7.5 15.65 8.26 L7.85 11.44 Q6 12.2 7.87 12.91 L8.34 13.09 Q10.2 13.8 10.8 15.7 L10.9 16.01 Q11.4 17.6 12.45 16.3 L12.45 16.3 Q13.5 15 14.29 13.53 Z\"/><path d=\"M10.2 13.8 L 17.5 7.5\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function TelegramDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
