// iconaut-react — tennis (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3.25 12 A8.75 8.75 0 1 0 20.75 12 A8.75 8.75 0 1 0 3.25 12 Z\"/><g class=\"primary\"><path d=\"M3.25 12 A8.75 8.75 0 1 0 20.75 12 A8.75 8.75 0 1 0 3.25 12 Z\"/><path d=\"M6.17 5.48 A8.75 8.75 0 0 1 6.17 18.52\"/><path d=\"M17.83 5.48 A8.75 8.75 0 0 0 17.83 18.52\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function TennisDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
