// iconaut-react — thermometer (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M14 5 A2 2 0 0 0 10 5 L10 13.7 A3.8 3.8 0 1 0 14 13.7 Z\"/><path d=\"M12 17 L 12.01 17\"/>";
const M1 = "<path d=\"M14.2 4.8 A2.1 2.1 0 0 0 9.8 4.8 L9.8 13.9 A4 4 0 1 0 14.2 13.9 Z\"/><path d=\"M12 17.2 L 12.01 17.2\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Thermometer({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
