// iconaut-react — toolbox (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M3 10 Q3 9 4 9 L20 9 Q21 9 21 10 L21 18 Q21 19 20 19 L4 19 Q3 19 3 18 Z\"/><path d=\"M8 9 L8 7 Q8 6 9 6 L15 6 Q16 6 16 7 L16 9\"/><path d=\"M10 10 Q10 9 11 9 L13 9 Q14 9 14 10 L14 11 Q14 12 13 12 L11 12 Q10 12 10 11 Z\"/><path d=\"M3 13 L 21 13\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function Toolbox({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
