// iconaut-react — toolbox (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M4.7 8.06L19.3 8.06A2.64 2.64 0 0 1 21.94 10.7L21.94 17.3A2.64 2.64 0 0 1 19.3 19.94L4.7 19.94A2.64 2.64 0 0 1 2.06 17.3L2.06 10.7A2.64 2.64 0 0 1 4.7 8.06Z M14 9L14 12L20 12L20 14L4 14L4 12L10 12L10 9Z\"/><path d=\"M16.19 5.08L16.38 5.14L16.55 5.24L16.69 5.37L16.81 5.52L16.89 5.7L16.93 5.88L16.94 6L16.94 8.06L15.06 8.06L15.06 6.94L8.94 6.94L8.94 8.06L7.06 8.06L7.06 6L7.08 5.81L7.14 5.62L7.24 5.46L7.37 5.31L7.52 5.2L7.7 5.11L7.88 5.07L8 5.06L16 5.06Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M4.71 8.1L19.29 8.1A2.61 2.61 0 0 1 21.9 10.71L21.9 17.29A2.61 2.61 0 0 1 19.29 19.9L4.71 19.9A2.61 2.61 0 0 1 2.1 17.29L2.1 10.71A2.61 2.61 0 0 1 4.71 8.1Z M14 9L14 12L20 12L20 14L4 14L4 12L10 12L10 9Z\"/><path d=\"M16.19 5.12L16.37 5.18L16.53 5.27L16.67 5.4L16.78 5.56L16.86 5.73L16.9 6L16.9 8.1L15.1 8.1L15.1 6.9L8.9 6.9L8.9 8.1L7.1 8.1L7.1 6L7.12 5.81L7.18 5.63L7.27 5.47L7.4 5.33L7.56 5.22L7.73 5.14L8 5.1L16 5.1Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M4.71 8.13L19.3 8.13A2.58 2.58 0 0 1 21.88 10.71L21.88 17.3A2.58 2.58 0 0 1 19.3 19.88L4.71 19.88A2.58 2.58 0 0 1 2.13 17.3L2.13 10.71A2.58 2.58 0 0 1 4.71 8.13Z M14 9L14 12L20 12L20 14L4 14L4 12L10 12L10 9Z\"/><path d=\"M16.19 5.15L16.36 5.2L16.52 5.3L16.66 5.43L16.77 5.58L16.84 5.75L16.88 6L16.88 8.13L15.13 8.13L15.13 6.88L8.88 6.88L8.88 8.13L7.13 8.13L7.13 6L7.15 5.81L7.2 5.64L7.3 5.48L7.43 5.34L7.58 5.23L7.75 5.16L8 5.13L16 5.13Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function ToolboxSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
