// iconaut-react — trash-can (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7 7 L17 7 Q18 7 17.92 8 L17 20 A1 1 0 0 1 16 20.92 L8 21 A1 1 0 0 1 6.99 20.08 L6.08 8 Q6 7 7 7 Z\"/><path d=\"M4 7 L 20 7\"/><path d=\"M9 7 L9 6 Q9 5 10 5 L14 5 Q15 5 15 6 L15 7\"/><path d=\"M10 11 L 10 17 M14 11 L 14 17\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function TrashCan({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
