// iconaut-react — tv (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M4.2 6.06L19.8 6.06A2.64 2.64 0 0 1 22.44 8.7L22.44 17.3A2.64 2.64 0 0 1 19.8 19.94L4.2 19.94A2.64 2.64 0 0 1 1.56 17.3L1.56 8.7A2.64 2.64 0 0 1 4.2 6.06Z\"/><path d=\"M16.17 3.08L16.36 3.13L16.53 3.22L16.68 3.35L16.79 3.5L16.88 3.68L16.93 3.86L16.94 4.06L16.91 4.25L16.84 4.43L16.73 4.59L16.56 4.75L14.82 6.06L9.19 6.06L7.44 4.75L7.3 4.62L7.18 4.46L7.11 4.28L7.07 4.09L7.07 3.9L7.11 3.71L7.19 3.54L7.3 3.38L7.44 3.25L7.61 3.15L7.79 3.09L7.98 3.06L8.18 3.08L8.36 3.14L8.56 3.25L12 5.83L15.44 3.25L15.6 3.15L15.79 3.09L15.98 3.06Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M4.21 6.1L19.79 6.1A2.61 2.61 0 0 1 22.4 8.71L22.4 17.29A2.61 2.61 0 0 1 19.79 19.9L4.21 19.9A2.61 2.61 0 0 1 1.6 17.29L1.6 8.71A2.61 2.61 0 0 1 4.21 6.1Z\"/><path d=\"M16.18 3.12L16.36 3.18L16.52 3.27L16.67 3.4L16.78 3.55L16.86 3.72L16.9 3.91L16.9 4.1L16.86 4.28L16.78 4.45L16.67 4.61L16.54 4.72L14.7 6.1L9.3 6.1L7.46 4.72L7.32 4.59L7.21 4.44L7.14 4.26L7.1 4.08L7.11 3.89L7.15 3.7L7.23 3.53L7.35 3.38L7.49 3.26L7.66 3.17L7.84 3.11L8.03 3.1L8.22 3.13L8.4 3.19L8.54 3.28L12 5.88L15.46 3.28L15.62 3.18L15.8 3.12L15.99 3.1Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M4.21 6.13L19.8 6.13A2.58 2.58 0 0 1 22.38 8.71L22.38 17.3A2.58 2.58 0 0 1 19.8 19.88L4.21 19.88A2.58 2.58 0 0 1 1.63 17.3L1.63 8.71A2.58 2.58 0 0 1 4.21 6.13Z\"/><path d=\"M16.18 3.15L16.36 3.2L16.52 3.3L16.66 3.43L16.77 3.58L16.84 3.75L16.87 3.93L16.87 4.12L16.82 4.3L16.74 4.47L16.62 4.62L16.52 4.7L14.62 6.13L9.38 6.13L7.48 4.7L7.34 4.57L7.23 4.42L7.16 4.25L7.13 4.06L7.13 3.88L7.18 3.7L7.26 3.53L7.38 3.38L7.53 3.27L7.69 3.18L7.87 3.13L8.06 3.13L8.24 3.16L8.42 3.23L8.53 3.3L12 5.91L15.48 3.3L15.64 3.21L15.81 3.15L16 3.13Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function TvSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
