// iconaut-react — van (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.25 17.5 A2.25 2.25 0 1 0 8.75 17.5 A2.25 2.25 0 1 0 4.25 17.5 Z\"/><path d=\"M15.25 17.5 A2.25 2.25 0 1 0 19.75 17.5 A2.25 2.25 0 1 0 15.25 17.5 Z\"/><path d=\"M2.5 16.63 L2.5 9 Q2.5 7 4.5 7 L11 7 Q13 7 14.41 8.41 L16.12 10.12 Q17 11 18.25 11 L18.25 11 Q19.5 11 20.38 11.88 L20.5 12 Q21.5 13 21.5 14.41 L21.5 16.63 Q21.5 17.5 20.63 17.5 L19.75 17.5 A2.25 2.25 0 0 0 15.25 17.5 L8.75 17.5 A2.25 2.25 0 0 0 4.25 17.5 L3.38 17.5 Q2.5 17.5 2.5 16.63 Z\"/><path d=\"M10.5 7 L10.5 9 Q10.5 11 12.5 11 L18.3 11\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function Van({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
