// iconaut-react — van (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5 16 Q3 16 3 14 L3 10 Q3 8 5 8 L12 8 Q14 8 15.6 9.2 L16.8 10.1 Q18 11 19.5 11 L19.5 11 Q21 11 21 12.5 L21 14 Q21 16 19 16 Z\"/><path d=\"M13.9 8.3  L14 9.5   Q14 11 15.5 11   L18.08 10.77\"/><path d=\"M5.27 16 A2 2 0 1 0 8.73 16 Z\"/><path d=\"M15.27 16 A2 2 0 1 0 18.73 16 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Van({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
