// iconaut-react — vials (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M10 4.2 L10 4.2 Q12 4.2 12 6.2 L12 17.2 A2 2 0 0 1 8 17.2 L8 6.2 Q8 4.2 10 4.2 Z M16 4.2 L16 4.2 Q18 4.2 18 6.2 L18 17.2 A2 2 0 0 1 14 17.2 L14 6.2 Q14 4.2 16 4.2 Z\"/><g class=\"primary\"><path d=\"M10 4.2 L10 4.2 Q12 4.2 12 6.2 L12 17.2 A2 2 0 0 1 8 17.2 L8 6.2 Q8 4.2 10 4.2 Z\"/><path d=\"M16 4.2 L16 4.2 Q18 4.2 18 6.2 L18 17.2 A2 2 0 0 1 14 17.2 L14 6.2 Q14 4.2 16 4.2 Z\"/><path d=\"M8 9.2 L 12 9.2 M14 9.2 L 18 9.2\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function VialsDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
