// iconaut-react — video-off (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M7 7L12 7Q14 7 14 9L14 14M12.05 17Q12.03 17 12 17L5.5 17Q3.5 17 3.5 15L3.5 9Q3.5 8.72 3.54 8.49\"/><path d=\"M14 10.5L18.24 8.24Q20 7.3 20 9.3L20 14.7Q20 16.7 18.24 15.76L14 13.5\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M1 = "<path d=\"M7 7L12 7Q14 7 14 9L14 14M12.46 16.97Q12.25 17 12 17L5.5 17Q3.5 17 3.5 15L3.5 9Q3.5 8.5 3.62 8.13\"/><path d=\"M14 10.5L18.24 8.24Q20 7.3 20 9.3L20 14.7Q20 16.7 18.24 15.76L14 13.5\"/><path d=\"M3.75 3.75L20.25 20.25\"/>";
const M2 = "<path d=\"M6.5 6.5L12.5 6.5Q14.5 6.5 14.5 8.5L14.5 14.5M12.97 17.47Q12.75 17.5 12.5 17.5L5 17.5Q3 17.5 3 15.5L3 8.5Q3 8 3.13 7.62\"/><path d=\"M14.5 10.3L18.77 7.81Q20.5 6.8 20.5 8.8L20.5 15.2Q20.5 17.2 18.77 16.19L14.5 13.7\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
const M3 = "<path d=\"M6.5 6.5L12.5 6.5Q14.5 6.5 14.5 8.5L14.5 14.5M12.95 17.47Q12.74 17.5 12.5 17.5L5 17.5Q3 17.5 3 15.5L3 8.5Q3 8.01 3.12 7.64\"/><path d=\"M14.5 10.3L18.77 7.81Q20.5 6.8 20.5 8.8L20.5 15.2Q20.5 17.2 18.77 16.19L14.5 13.7\"/><path d=\"M3.5 3.5L20.5 20.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M1, 1.688],
  20: [M2, 1.68],
  24: [M3, 1.7]
};
const S = [12, 16, 20, 24];

export default function VideoOff({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
