// iconaut-react — volume (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 11 Q3 9.2 4.8 9.2 L4.8 9.2 Q6.6 9.2 7.9 7.96 L9.75 6.18 Q11.2 4.8 11.2 6.8 L11.2 17.2 Q11.2 19.2 9.75 17.82 L7.9 16.04 Q6.6 14.8 4.8 14.8 L4.8 14.8 Q3 14.8 3 13 Z\"/><g class=\"primary\"><path d=\"M3 10.2 Q3 9.2 4 9.2 L5.6 9.2 Q6.6 9.2 7.32 8.51 L10.48 5.49 Q11.2 4.8 11.2 5.8 L11.2 18.2 Q11.2 19.2 10.48 18.51 L7.32 15.49 Q6.6 14.8 5.6 14.8 L4 14.8 Q3 14.8 3 13.8 Z\"/><path d=\"M14.7 9.1 A4.2 4.2 0 0 1 14.7 14.9\"/><path d=\"M17.3 6.8 A7.8 7.8 0 0 1 17.3 17.2\"/></g>";
const M1 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M3 11.2 Q3 9.2 5 9.2 L5 9.2 Q7 9.2 8.47 7.85 L10.53 5.95 Q12 4.6 12 6.6 L12 17.4 Q12 19.4 10.53 18.05 L8.47 16.15 Q7 14.8 5 14.8 L5 14.8 Q3 14.8 3 12.8 Z\"/><g class=\"primary\"><path d=\"M3 10.2 Q3 9.2 4 9.2 L6 9.2 Q7 9.2 7.74 8.52 L11.26 5.28 Q12 4.6 12 5.6 L12 18.4 Q12 19.4 11.26 18.72 L7.74 15.48 Q7 14.8 6 14.8 L4 14.8 Q3 14.8 3 13.8 Z\"/><path d=\"M14.9 8.7 A5 5 0 0 1 14.9 15.3\"/><path d=\"M18 6.4 A8.8 8.8 0 0 1 18 17.6\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [12, 16, 20, 24];

export default function VolumeDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
