// iconaut-react — vr-headset (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M5.5 7.5 L18.5 7.5 Q20.5 7.5 20.5 9.5 L20.5 14.5 Q20.5 16.5 18.5 16.5 L14.5 16.5 A2.5 2.5 0 0 0 9.5 16.5 L5.5 16.5 Q3.5 16.5 3.5 14.5 L3.5 9.5 Q3.5 7.5 5.5 7.5 Z\"/><path d=\"M7.5 11.5 L 7.51 11.5\"/><path d=\"M16.5 11.5 L 16.51 11.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function VrHeadset({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
