// iconaut-react — warehouse (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M2.5 18.79L2.5 10.86A4.08 4.08 0 0 1 4.67 7.25L9.87 4.5A4.56 4.56 0 0 1 14.13 4.5L19.33 7.25A4.08 4.08 0 0 1 21.5 10.86L21.5 18.79A2.71 2.71 0 0 1 18.79 21.5L5.21 21.5A2.71 2.71 0 0 1 2.5 18.79Z M8.5 21.5L8.5 16A2 2 0 0 1 10.5 14L13.5 14A2 2 0 0 1 15.5 16L15.5 21.5L8.5 21.5Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M2.66 18.79L2.66 10.85A3.93 3.93 0 0 1 4.75 7.38L9.94 4.64A4.41 4.41 0 0 1 14.06 4.64L19.25 7.38A3.93 3.93 0 0 1 21.34 10.85L21.34 18.79A2.55 2.55 0 0 1 18.79 21.34L5.21 21.34A2.55 2.55 0 0 1 2.66 18.79Z M8.5 21.34L8.5 16A2 2 0 0 1 10.5 14L13.5 14A2 2 0 0 1 15.5 16L15.5 21.34L8.5 21.34Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M2.66 18.79L2.66 10.85A3.92 3.92 0 0 1 4.75 7.39L9.94 4.64A4.4 4.4 0 0 1 14.06 4.64L19.25 7.39A3.92 3.92 0 0 1 21.34 10.85L21.34 18.79A2.55 2.55 0 0 1 18.79 21.34L5.21 21.34A2.55 2.55 0 0 1 2.66 18.79Z M19.5 9.6L19.5 10.36L19.33 10.44L19.14 10.49L19 10.5L5 10.5L4.8 10.48L4.61 10.42L4.5 10.36L4.5 9.6L6.58 8.5L17.42 8.5Z M8.5 21.34L8.5 16A2 2 0 0 1 10.5 14L13.5 14A2 2 0 0 1 15.5 16L15.5 21.34L8.5 21.34Z\"/>";
const M3 = "<path fill-rule=\"evenodd\" d=\"M2.65 18.79L2.65 10.86A3.93 3.93 0 0 1 4.74 7.38L9.94 4.63A4.41 4.41 0 0 1 14.06 4.63L19.26 7.38A3.93 3.93 0 0 1 21.35 10.86L21.35 18.79A2.56 2.56 0 0 1 18.79 21.35L5.21 21.35A2.56 2.56 0 0 1 2.65 18.79Z M19.5 9.6L19.5 10.36L19.33 10.44L19.14 10.49L19 10.5L5 10.5L4.8 10.48L4.61 10.42L4.5 10.36L4.5 9.6L6.58 8.5L17.42 8.5Z M8.5 21.35L8.5 16A2 2 0 0 1 10.5 14L13.5 14A2 2 0 0 1 15.5 16L15.5 21.35L8.5 21.35Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, null],
  16: [M1, null],
  20: [M2, null],
  24: [M3, null]
};
const S = [12, 16, 20, 24];

export default function WarehouseSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
