// iconaut-react — warehouse (solid). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path fill-rule=\"evenodd\" d=\"M2.56 18.8L2.56 10.86A4.02 4.02 0 0 1 4.7 7.31L9.9 4.55A4.49 4.49 0 0 1 14.1 4.55L19.3 7.31A4.02 4.02 0 0 1 21.44 10.86L21.44 18.8A2.64 2.64 0 0 1 18.8 21.44L5.2 21.44A2.64 2.64 0 0 1 2.56 18.8Z M8.5 21.44L8.5 16A2 2 0 0 1 10.5 14L13.5 14A2 2 0 0 1 15.5 16L15.5 21.44L8.5 21.44Z\"/>";
const M1 = "<path fill-rule=\"evenodd\" d=\"M2.6 18.79L2.6 10.86A3.98 3.98 0 0 1 4.72 7.34L9.91 4.59A4.46 4.46 0 0 1 14.09 4.59L19.28 7.34A3.98 3.98 0 0 1 21.4 10.86L21.4 18.79A2.61 2.61 0 0 1 18.79 21.4L5.21 21.4A2.61 2.61 0 0 1 2.6 18.79Z M19.5 9.6L19.5 10.36L19.33 10.44L19.14 10.49L19 10.5L5 10.5L4.8 10.48L4.61 10.42L4.5 10.36L4.5 9.6L6.58 8.5L17.42 8.5Z M8.5 21.4L8.5 16A2 2 0 0 1 10.5 14L13.5 14A2 2 0 0 1 15.5 16L15.5 21.4L8.5 21.4Z\"/>";
const M2 = "<path fill-rule=\"evenodd\" d=\"M2.63 18.8L2.63 10.85A3.96 3.96 0 0 1 4.74 7.35L9.93 4.61A4.44 4.44 0 0 1 14.07 4.61L19.27 7.36A3.96 3.96 0 0 1 21.38 10.85L21.38 18.8A2.58 2.58 0 0 1 18.8 21.38L5.21 21.38A2.58 2.58 0 0 1 2.63 18.8Z M19.5 9.6L19.5 10.36L19.33 10.44L19.14 10.49L19 10.5L5 10.5L4.8 10.48L4.61 10.42L4.5 10.36L4.5 9.6L6.58 8.5L17.42 8.5Z M8.5 21.38L8.5 16A2 2 0 0 1 10.5 14L13.5 14A2 2 0 0 1 15.5 16L15.5 21.38L8.5 21.38Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, null],
  20: [M1, null],
  24: [M2, null]
};
const S = [16, 20, 24];

export default function WarehouseSolid({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "currentColor",
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
