// iconaut-react — washing-machine (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4.5 5 Q4.5 3 6.5 3 L17.5 3 Q19.5 3 19.5 5 L19.5 19 Q19.5 21 17.5 21 L6.5 21 Q4.5 21 4.5 19 Z\"/><path d=\"M8 14 A4 4 0 1 0 16 14 A4 4 0 1 0 8 14 Z\"/><path d=\"M7.5 6 L 7.51 6\"/>";
const M1 = "<path d=\"M4.5 5 Q4.5 3 6.5 3 L17.5 3 Q19.5 3 19.5 5 L19.5 19 Q19.5 21 17.5 21 L6.5 21 Q4.5 21 4.5 19 Z\"/><path d=\"M8 14 A4 4 0 1 0 16 14 A4 4 0 1 0 8 14 Z\"/><path d=\"M7.5 6 L 7.51 6 M11 6 L 11.01 6\"/><path d=\"M12 14 L 12.01 14\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M1, 1.8],
  24: [M1, 1.75]
};
const S = [16, 20, 24];

export default function WashingMachine({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
