// iconaut-react — watch (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M7 12 A5 5 0 1 0 17 12 A5 5 0 1 0 7 12 Z\"/><g class=\"primary\"><path d=\"M7 12 A5 5 0 1 0 17 12 A5 5 0 1 0 7 12 Z\"/><path d=\"M9 7.2 L8.63 4.49 Q8.5 3.5 9.5 3.5 L14.5 3.5 Q15.5 3.5 15.37 4.49 L15 7.2\"/><path d=\"M9 16.8 L8.63 19.51 Q8.5 20.5 9.5 20.5 L14.5 20.5 Q15.5 20.5 15.37 19.51 L15 16.8\"/><path d=\"M12 9.11 L12 11 Q12 12 12.87 12.49 L13.95 13.11\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.875],
  20: [M0, 1.8],
  24: [M0, 1.75]
};
const S = [16, 20, 24];

export default function WatchDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
