// iconaut-react — watermelon (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M4 7 A9 9 0 0 1 20 7 L13.02 18.78 Q12 20.5 10.98 18.78 L4 7 Z\"/><path d=\"M6.2 8.3 A6.5 6.5 0 0 1 17.8 8.3\"/><path d=\"M10 11 L 10.01 11 M14 11 L 14.01 11 M12 14 L 12.01 14 M11.5 17 L 11.51 17\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [16, 20, 24];

export default function Watermelon({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
