// iconaut-react — webcam (duo). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path class=\"secondary\" fill-rule=\"evenodd\" fill=\"currentColor\" fill-opacity=\"0.25\" d=\"M5 10 A7 7 0 1 0 19 10 A7 7 0 1 0 5 10 Z M9.4 10a2.6 2.6 0 1 1 5.2 0a2.6 2.6 0 1 1 -5.2 0Z\"/><g class=\"primary\"><path d=\"M5 10 A7 7 0 1 0 19 10 A7 7 0 1 0 5 10 Z\"/><path d=\"M9.4 10 A2.6 2.6 0 1 1 14.6 10 A2.6 2.6 0 1 1 9.4 10 Z\"/><path d=\"M8 20 L 16 20\"/><path d=\"M12 17 L 12 20\"/></g>";
// size -> [inner markup, optical stroke width]
const F = {
  12: [M0, 2],
  16: [M0, 1.688],
  20: [M0, 1.68],
  24: [M0, 1.7]
};
const S = [12, 16, 20, 24];

export default function WebcamDuo({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
