// iconaut-react — zap (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M12.88 4.5 Q13 2.5 11.78 4.08 L5.72 11.92 Q4.5 13.5 6.5 13.5 L9 13.5 Q11 13.5 10.88 15.5 L10.62 19.5 Q10.5 21.5 11.77 19.95 L18.23 12.05 Q19.5 10.5 17.5 10.5 L14.5 10.5 Q12.5 10.5 12.62 8.5 Z\"/>";
const M1 = "<path d=\"M13.24 4.48 Q13.5 2.5 12.21 4.03 L5.29 12.27 Q4 13.8 6 13.8 L9 13.8 Q11 13.8 10.82 15.79 L10.48 19.51 Q10.3 21.5 11.6 19.98 L18.7 11.72 Q20 10.2 18 10.2 L14.5 10.2 Q12.5 10.2 12.76 8.22 Z\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function Zap({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
