// iconaut-react — zoom-in (line). Generated by scripts/gen-react.mjs; do not edit.
import { createElement } from "react";

const M0 = "<path d=\"M11 4.4 A6.6 6.6 0 1 0 11 17.6 A6.6 6.6 0 0 0 11 4.4 Z\"/><path d=\"M15.9 15.9 L 20 20\"/><path d=\"M11 8 L 11 14 M8 11 L 14 11\"/>";
const M1 = "<path d=\"M10.5 3.9 A6.6 6.6 0 1 0 10.5 17.1 A6.6 6.6 0 0 0 10.5 3.9 Z\"/><path d=\"M15.3 15.3 L 20.5 20.5\"/><path d=\"M10.5 7.5 L 10.5 13.5 M7.5 10.5 L 13.5 10.5\"/>";
// size -> [inner markup, optical stroke width]
const F = {
  16: [M0, 1.688],
  20: [M1, 1.68],
  24: [M1, 1.7]
};
const S = [16, 20, 24];

export default function ZoomIn({ size = 24, strokeWidth, ...props }) {
  const n = Number(size) || 24;
  // an exact native size uses its own hand-tuned fit; anything else uses the nearest fit
  const f = S.indexOf(n) >= 0 ? n : S.reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a));
  return createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: n,
    height: n,
    fill: "none", stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round",
    strokeWidth: strokeWidth == null ? F[f][1] : strokeWidth,
    ...props,
    dangerouslySetInnerHTML: { __html: F[f][0] },
  });
}
